CREATE TABLE  "ADMIN"
   (    "ADMIN_ID" NUMBER,
    "FIRSTNAME" VARCHAR2(20),
    "LASTNAME" VARCHAR2(20),
    "EMAIL" VARCHAR2(30),
    "USERNAME" VARCHAR2(30),
    "PASSWORD" VARCHAR2(30),
    "PHONENUMBER" NUMBER,
     PRIMARY KEY ("ADMIN_ID") ENABLE,
     UNIQUE ("EMAIL") ENABLE
   ) ;

CREATE TABLE  "CUSTOMER"
   (    "CUSTOMER_ID" NUMBER,
    "FIRSTNAME" VARCHAR2(30),
    "LASTNAME" VARCHAR2(30),
    "GENDER" VARCHAR2(20),
    "EMAIL" VARCHAR2(20),
    "USERNAME" VARCHAR2(20),
    "PASSWORD" VARCHAR2(20),
    "PHONENUMBER" NUMBER,
    "AVAILABLE" VARCHAR2(10),
     PRIMARY KEY ("CUSTOMER_ID") ENABLE,
     UNIQUE ("EMAIL") ENABLE
   ) ;

CREATE TABLE  "BUSOPERATOR"
   (    "OPER_ID" NUMBER,
    "BNAME" VARCHAR2(30),
    "FIRSTNAME" VARCHAR2(30),
    "LASTNAME" VARCHAR2(30),
    "EMAIL" VARCHAR2(30),
    "USERNAME" VARCHAR2(20),
    "PASSWORD" VARCHAR2(20),
    "PHONE_NUMBER" VARCHAR2(10),
     PRIMARY KEY ("OPER_ID") ENABLE,
     UNIQUE ("EMAIL") ENABLE
   ) ;

CREATE TABLE  "BUS"
   (    "BUS_ID" NUMBER NOT NULL ENABLE,
    "BUSNAME" VARCHAR2(30),
    "BUSTYPE" VARCHAR2(10),
    "BUSCAPACITY" NUMBER,
    "FARE" NUMBER,
    "ROUTE_ID" NUMBER,
    "OPER_ID" NUMBER,
    "DAYOFROUTE" DATE,
    "ARRIVALTIME" TIMESTAMP (6),
    "DEPARTURETIME" TIMESTAMP (6),
    "BUS_AVAILABILITY" VARCHAR2(10),
     PRIMARY KEY ("BUS_ID") ENABLE
   ) ;

CREATE TABLE  "ROUTE"
   (    "ROUTE_ID" NUMBER NOT NULL ENABLE,
    "STARTLOCATION" VARCHAR2(30),
    "ENDLOCATION" VARCHAR2(30),
    "DISTANCE" NUMBER,
    "ESTIMATEDDURATION" NUMBER,
    "ROUTE_AVAILABILITY" VARCHAR2(1),
     PRIMARY KEY ("ROUTE_ID") ENABLE
   ) ;

CREATE TABLE  "BOOK"
   (    "BOOKINGID" NUMBER,
    "CUSTOMER_ID" NUMBER,
    "SEATNUMBER" NUMBER,
    "BOOKINGSTATUS" VARCHAR2(20),
    "BOOKEDDATE" DATE,
    "BUSID" NUMBER,
    "OPER_ID" NUMBER,
    "TOTALPRICE" NUMBER,
     CONSTRAINT "BOOK_PK" PRIMARY KEY ("BOOKINGID") ENABLE
   ) ;

CREATE TABLE  "PAYMENT"
   (    "PAY_ID" NUMBER,
    "ACCOUNTNUMBER" VARCHAR2(16),
    "PAYMENTMETHOD" VARCHAR2(30),
    "TOTALAMOUNT" NUMBER,
    "BOOKING_ID" NUMBER,
    "PAYMENTSTATUS" VARCHAR2(20),
     PRIMARY KEY ("PAY_ID") ENABLE
   ) ;
   ALTER TABLE  "BOOK" ADD CONSTRAINT "BUS_ID" FOREIGN KEY ("BUSID")
   REFERENCES  "BUS" ("BUS_ID") ENABLE;
   ALTER TABLE  "BOOK" ADD CONSTRAINT "CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
   REFERENCES  "CUSTOMER" ("CUSTOMER_ID") ENABLE;
   ALTER TABLE  "BOOK" ADD CONSTRAINT "OPER_FK" FOREIGN KEY ("OPER_ID")
   REFERENCES  "BUSOPERATOR" ("OPER_ID") ENABLE;
   ALTER TABLE  "PAYMENT" ADD CONSTRAINT "PAYMENT_FK" FOREIGN KEY ("BOOKING_ID")
   REFERENCES  "BOOK" ("BOOKINGID") ENABLE;
   ALTER TABLE  "BUS" ADD FOREIGN KEY ("OPER_ID")
   REFERENCES  "BUSOPERATOR" ("OPER_ID") ENABLE;
   ALTER TABLE  "BUS" ADD FOREIGN KEY ("ROUTE_ID")
   REFERENCES  "ROUTE" ("ROUTE_ID") ENABLE;
   CREATE UNIQUE INDEX  "PAYMENT" ON  "PAYMENTCUSTOMER" ("PAY_ID")