CREATE TABLE  "ADMIN"
   (    "ADMIN_ID" NUMBER,
    "FIRSTNAME" VARCHAR2(20),
    "LASTNAME" VARCHAR2(20),
    "EMAIL" VARCHAR2(30),
    "USERNAME" VARCHAR2(30),
    "PASSWORD" VARCHAR2(30),
    "PHONENUMBER" NUMBER,
     PRIMARY KEY ("ADMIN_ID") ENABLE,
     UNIQUE ("EMAIL") ENABLE
   ) ;

CREATE TABLE  "CUSTOMER"
   (    "CUSTOMER_ID" NUMBER,
    "FIRSTNAME" VARCHAR2(30),
    "LASTNAME" VARCHAR2(30),
    "GENDER" VARCHAR2(20),
    "EMAIL" VARCHAR2(20),
    "USERNAME" VARCHAR2(20),
    "PASSWORD" VARCHAR2(20),
    "PHONENUMBER" NUMBER,
    "AVAILABLE" VARCHAR2(10),
     PRIMARY KEY ("CUSTOMER_ID") ENABLE,
     UNIQUE ("EMAIL") ENABLE
   ) ;

CREATE TABLE  "BUSOPERATOR"
   (    "OPER_ID" NUMBER,
    "BNAME" VARCHAR2(30),
    "FIRSTNAME" VARCHAR2(30),
    "LASTNAME" VARCHAR2(30),
    "EMAIL" VARCHAR2(30),
    "USERNAME" VARCHAR2(20),
    "PASSWORD" VARCHAR2(20),
    "PHONE_NUMBER" VARCHAR2(10),
     PRIMARY KEY ("OPER_ID") ENABLE,
     UNIQUE ("EMAIL") ENABLE
   ) ;

CREATE TABLE  "BUS"
   (    "BUS_ID" NUMBER NOT NULL ENABLE,
    "BUSNAME" VARCHAR2(30),
    "BUSTYPE" VARCHAR2(10),
    "BUSCAPACITY" NUMBER,
    "FARE" NUMBER,
    "ROUTE_ID" NUMBER,
    "OPER_ID" NUMBER,
    "DAYOFROUTE" DATE,
    "ARRIVALTIME" TIMESTAMP (6),
    "DEPARTURETIME" TIMESTAMP (6),
    "BUS_AVAILABILITY" VARCHAR2(10),
     PRIMARY KEY ("BUS_ID") ENABLE
   ) ;

CREATE TABLE  "ROUTE"
   (    "ROUTE_ID" NUMBER NOT NULL ENABLE,
    "STARTLOCATION" VARCHAR2(30),
    "ENDLOCATION" VARCHAR2(30),
    "DISTANCE" NUMBER,
    "ESTIMATEDDURATION" NUMBER,
    "ROUTE_AVAILABILITY" VARCHAR2(1),
     PRIMARY KEY ("ROUTE_ID") ENABLE
   ) ;

CREATE TABLE  "BOOK"
   (    "BOOKINGID" NUMBER,
    "CUSTOMER_ID" NUMBER,
    "SEATNUMBER" NUMBER,
    "BOOKINGSTATUS" VARCHAR2(20),
    "BOOKEDDATE" DATE,
    "BUSID" NUMBER,
    "OPER_ID" NUMBER,
    "TOTALPRICE" NUMBER,
     CONSTRAINT "BOOK_PK" PRIMARY KEY ("BOOKINGID") ENABLE
   ) ;

CREATE TABLE  "PAYMENT"
   (    "PAY_ID" NUMBER,
    "ACCOUNTNUMBER" VARCHAR2(16),
    "PAYMENTMETHOD" VARCHAR2(30),
    "TOTALAMOUNT" NUMBER,
    "BOOKING_ID" NUMBER,
    "PAYMENTSTATUS" VARCHAR2(20),
     PRIMARY KEY ("PAY_ID") ENABLE
   ) ;
   ALTER TABLE  "BOOK" ADD CONSTRAINT "BUS_ID" FOREIGN KEY ("BUSID")
   REFERENCES  "BUS" ("BUS_ID") ENABLE;
   ALTER TABLE  "BOOK" ADD CONSTRAINT "CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
   REFERENCES  "CUSTOMER" ("CUSTOMER_ID") ENABLE;
   ALTER TABLE  "BOOK" ADD CONSTRAINT "OPER_FK" FOREIGN KEY ("OPER_ID")
   REFERENCES  "BUSOPERATOR" ("OPER_ID") ENABLE;
   ALTER TABLE  "PAYMENT" ADD CONSTRAINT "PAYMENT_FK" FOREIGN KEY ("BOOKING_ID")
   REFERENCES  "BOOK" ("BOOKINGID") ENABLE;
   ALTER TABLE  "BUS" ADD FOREIGN KEY ("OPER_ID")
   REFERENCES  "BUSOPERATOR" ("OPER_ID") ENABLE;
   ALTER TABLE  "BUS" ADD FOREIGN KEY ("ROUTE_ID")
   REFERENCES  "ROUTE" ("ROUTE_ID") ENABLE;
   CREATE UNIQUE INDEX  "PAYMENT" ON  "PAYMENTCUSTOMER" ("PAY_ID")


INSERT INTO Admin (ADMIN_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD, PHONENUMBER) VALUES 
(1, 'Raj', 'Kumar', 'Raj@22gmail.com', 'Admin_123', 'Pass@22', '8990790678');
INSERT INTO Admin (ADMIN_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD, PHONENUMBER) VALUES 
(2, 'Charles', 'Harris', 'charles@gmail.com', 'charles Harris', 'charles123', '9087990876');


INSERT INTO Customer (CUSTOMER_ID, FIRSTNAME, LASTNAME, GENDER, EMAIL, USERNAME, PASSWORD, PHONENUMBER, AVAILABLE) VALUES 
(1, 'Bharath', 'S', 'male', 'Bharath@gmail.com', 'Bhar2345', 'BHa@23sb', '9078967890', 'ACTIVE');
INSERT INTO Customer (CUSTOMER_ID, FIRSTNAME, LASTNAME, GENDER, EMAIL, USERNAME, PASSWORD, PHONENUMBER, AVAILABLE) VALUES 
(5, 'Alex', 'Smith', 'male', 'alexsmith@gmail.com', 'alex345', 'AS@123412', '8765432109', 'ACTIVE');
INSERT INTO Customer (CUSTOMER_ID, FIRSTNAME, LASTNAME, GENDER, EMAIL, USERNAME, PASSWORD, PHONENUMBER, AVAILABLE) VALUES 
(14, 'Sophia', 'Martinez', 'female', 'sophia@gmail.com', 'sophia89', 'Sm@7890', '9432109876', 'ACTIVE');


INSERT INTO BusOperator (OPER_ID, BNAME, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD, PHONE_NUMBER) VALUES 
(1, 'primo company', 'John', 'S', 'John@gmail.com', 'John123', 'Joh@23ns', '8980990067');
INSERT INTO BusOperator (OPER_ID, BNAME, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD, PHONE_NUMBER) VALUES 
(2, 'Libertyexpress', 'Liam', 'j', 'Liberty@gmail.com', 'Liberty123', 'lib@Er445', '7878981221');


INSERT INTO Bus (BUS_ID, BUSNAME, BUSTYPE, BUSCAPACITY, FARE, ROUTE_ID, OPER_ID, DAYOFROUTE, ARRIVALTIME, DEPARTURETIME, BUS_AVAILABILITY) VALUES 
(1, 'kMS Travel', 'AC', 44, 600, 98, 1, TO_DATE('08/25/2024', 'MM/DD/YYYY'), TO_TIMESTAMP('25-AUG-24 08.30.00.000000 AM', 'DD-MON-YY HH.MI.SS.FF6 AM'), TO_TIMESTAMP('25-AUG-24 12.30.00.000000 PM', 'DD-MON-YY HH.MI.SS.FF6 PM'), 'Y');
INSERT INTO Bus (BUS_ID, BUSNAME, BUSTYPE, BUSCAPACITY, FARE, ROUTE_ID, OPER_ID, DAYOFROUTE, ARRIVALTIME, DEPARTURETIME, BUS_AVAILABILITY) VALUES 
(2, 'jihan luxary bus', 'Non AC', 44, 900, 1, 2, TO_DATE('08/30/2024', 'MM/DD/YYYY'), TO_TIMESTAMP('30-AUG-24 08.30.00.000000 AM', 'DD-MON-YY HH.MI.SS.FF6 AM'), TO_TIMESTAMP('30-AUG-24 04.30.00.000000 PM', 'DD-MON-YY HH.MI.SS.FF6 PM'), 'Y');
INSERT INTO Bus (BUS_ID, BUSNAME, BUSTYPE, BUSCAPACITY, FARE, ROUTE_ID, OPER_ID, DAYOFROUTE, ARRIVALTIME, DEPARTURETIME, BUS_AVAILABILITY) VALUES 
(4, 'No 1 Air travel', 'AC', 44, 500, 1, 1, TO_DATE('08/30/2024', 'MM/DD/YYYY'), TO_TIMESTAMP('30-AUG-24 10.30.00.000000 AM', 'DD-MON-YY HH.MI.SS.FF6 AM'), TO_TIMESTAMP('30-AUG-24 06.30.00.000000 PM', 'DD-MON-YY HH.MI.SS.FF6 PM'), 'Y');
INSERT INTO Bus (BUS_ID, BUSNAME, BUSTYPE, BUSCAPACITY, FARE, ROUTE_ID, OPER_ID, DAYOFROUTE, ARRIVALTIME, DEPARTURETIME, BUS_AVAILABILITY) VALUES 
(8, 'AST Travel', 'AC', 44, 800, 4, 2, TO_DATE('08/24/2024', 'MM/DD/YYYY'), TO_TIMESTAMP('08-AUG-24 11.00.00.000000 AM', 'DD-MON-YY HH.MI.SS.FF6 AM'), TO_TIMESTAMP('08-AUG-24 03.00.00.000000 PM', 'DD-MON-YY HH.MI.SS.FF6 PM'), 'Y');
INSERT INTO Bus (BUS_ID, BUSNAME, BUSTYPE, BUSCAPACITY, FARE, ROUTE_ID, OPER_ID, DAYOFROUTE, ARRIVALTIME, DEPARTURETIME, BUS_AVAILABILITY) VALUES 
(15, 'Sri Ganesh Travels', 'AC', 44, 1200, 34, 1, TO_DATE('08/04/2024', 'MM/DD/YYYY'), TO_TIMESTAMP('04-AUG-24 09.30.00.000000 AM', 'DD-MON-YY HH.MI.SS.FF6 AM'), TO_TIMESTAMP('04-AUG-24 05.30.00.000000 PM', 'DD-MON-YY HH.MI.SS.FF6 PM'), 'Y');


INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(1, 'Chennai', 'Coimbatore', 510, 2, 'Y');
INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(2, 'Madurai', 'Tiruchirappalli', 130, 2, 'Y');
INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(3, 'Tirunelveli', 'Kanyakumari', 90, 4, 'Y');
INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(4, 'Salem', 'Erode', 120, 4, 'Y');
INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(5, 'Vellore', 'Chennai', 140, 2, 'Y');
INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(98, 'Salem', 'Chennai', 345, 8,'Y');


INSERT INTO Book (BOOKINGID, CUSTOMER_ID, SEATNUMBER, BOOKINGSTATUS, BOOKEDDATE, BUSID) VALUES 
(1, 1, 1, 'confirmed', TO_DATE('07/22/2024', 'MM/DD/YYYY'), 8);
INSERT INTO Book (BOOKINGID, CUSTOMER_ID, SEATNUMBER, BOOKINGSTATUS, BOOKEDDATE, BUSID) VALUES 
(2, 1, 2, 'Refund Requested', TO_DATE('07/21/2024', 'MM/DD/YYYY'), 8);
INSERT INTO Book (BOOKINGID, CUSTOMER_ID, SEATNUMBER, BOOKINGSTATUS, BOOKEDDATE, BUSID) VALUES 
(3, 1, 3, 'Cancelled', TO_DATE('07/28/2024', 'MM/DD/YYYY'), 8);
INSERT INTO Book (BOOKINGID, CUSTOMER_ID, SEATNUMBER, BOOKINGSTATUS, BOOKEDDATE, BUSID) VALUES 
(19, 14, 2, 'Confirmed', TO_DATE('07/29/2024', 'MM/DD/YYYY'), 8);
INSERT INTO Book (BOOKINGID, CUSTOMER_ID, SEATNUMBER, BOOKINGSTATUS, BOOKEDDATE, BUSID) VALUES 
(9, 1, 2, 'Confirmed', TO_DATE('07/24/2024', 'MM/DD/YYYY'), 15);


INSERT INTO Payment (PAY_ID, ACCOUNTNUMBER, PAYMENTMETHOD, TOTALAMOUNT, BOOKING_ID, PAYMENTSTATUS) VALUES 
(1, 78878434443454, 'Card', 500, 19, 'PAID');
INSERT INTO Payment (PAY_ID, ACCOUNTNUMBER, PAYMENTMETHOD, TOTALAMOUNT, BOOKING_ID, PAYMENTSTATUS) VALUES 
(2, 89345672235678, 'Card', 800, 1, 'PAID');








