CREATE TABLE  "ADMIN" 
   (    "ADMIN_ID" NUMBER, 
    "USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(30) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
    "PHONE_NO" NUMBER(10,0) NOT NULL ENABLE, 
    "ADDRESS" VARCHAR2(50), 
    "NAME" VARCHAR2(50), 
     PRIMARY KEY ("ADMIN_ID") ENABLE, 
     UNIQUE ("USERNAME") ENABLE, 
     UNIQUE ("EMAIL") ENABLE, 
     UNIQUE ("PHONE_NO") ENABLE
   ) ;CREATE TABLE  "RT" 
   (    "TYPE_ID" NUMBER, 
    "ROOM_NAME" VARCHAR2(25) NOT NULL ENABLE, 
    "BED_CAPACITY" NUMBER NOT NULL ENABLE, 
    "AMENITY" VARCHAR2(255), 
    "NO_OF_ROOM" NUMBER, 
    "RENT" NUMBER, 
     PRIMARY KEY ("TYPE_ID") ENABLE
   ) ;CREATE TABLE  "ALLROOM" 
   (    "ROOM_ID" NUMBER, 
    "TYPE_ID" NUMBER NOT NULL ENABLE, 
    "ROOM_STATUS" VARCHAR2(20), 
    "ROOM_CONDITION" VARCHAR2(20)
   ) ;CREATE TABLE  "BOOKINGS" 
   (    "ID" NUMBER, 
    "CUSTOMER_NAME" VARCHAR2(50) NOT NULL ENABLE, 
    "GENDER" VARCHAR2(10) NOT NULL ENABLE, 
    "CHECK_IN" DATE NOT NULL ENABLE, 
    "CHECK_OUT" DATE NOT NULL ENABLE, 
    "BOOKING_STATUS" VARCHAR2(20), 
    "PHONE_NO" NUMBER, 
    "ROOM" NUMBER, 
     PRIMARY KEY ("ID") ENABLE
   ) ;CREATE TABLE  "KEEPER" 
   (    "KEEPER_ID" NUMBER, 
    "NAME" VARCHAR2(50) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
    "PHONE_NO" VARCHAR2(20) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(50), 
    "STATUS" VARCHAR2(20), 
     PRIMARY KEY ("KEEPER_ID") ENABLE
   ) ;CREATE TABLE  "PAYMENTS" 
   (    "PAYMENT_ID" NUMBER, 
    "BOOKING_ID" NUMBER, 
    "PAYMENT_AMT" NUMBER, 
    "PAYMENT_DATE" DATE, 
    "PAYMENT_METHOD" VARCHAR2(30), 
    "PAYMENT_STATUS" VARCHAR2(20), 
     PRIMARY KEY ("PAYMENT_ID") ENABLE
   ) ;CREATE TABLE  "REFER" 
   (    "NAME" VARCHAR2(50), 
    "EMAIL" VARCHAR2(50), 
    "MESSAGE" VARCHAR2(255)
   ) ;CREATE TABLE  "STAFF" 
   (    "STAFF_ID" NUMBER, 
    "NAME" VARCHAR2(30) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(30) NOT NULL ENABLE, 
    "PHONE_NO" VARCHAR2(20), 
     PRIMARY KEY ("STAFF_ID") ENABLE
   ) ;CREATE TABLE  "USERS" 
   (    "ID" NUMBER, 
    "FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
    "LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
    "AGE" NUMBER, 
    "GENDER" VARCHAR2(10), 
    "PHONE" VARCHAR2(20) NOT NULL ENABLE, 
    "ADDRESS" VARCHAR2(255) NOT NULL ENABLE, 
    "STATE" VARCHAR2(50) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(100) NOT NULL ENABLE, 
     CHECK (age >= 18) ENABLE, 
     CHECK (gender IN ('Male', 'Female', 'Other')) ENABLE, 
     CONSTRAINT "USERS_AGE_CK" CHECK (age >= 18) ENABLE, 
     CONSTRAINT "USERS_GENDER_CK" CHECK (gender IN ('Male', 'Female', 'Other')) ENABLE, 
     CONSTRAINT "USERS_EMAIL_CK" CHECK (email LIKE '%_@%._%') ENABLE, 
     CONSTRAINT "USERS_PK" PRIMARY KEY ("ID") ENABLE, 
     UNIQUE ("EMAIL") ENABLE
   ) ;ALTER TABLE  "PAYMENTS" ADD CONSTRAINT "FK_BOOKING_ID" FOREIGN KEY ("BOOKING_ID")
      REFERENCES  "BOOKINGS" ("ID") ENABLE;ALTER TABLE  "ALLROOM" ADD FOREIGN KEY ("TYPE_ID")
      REFERENCES  "RT" ("TYPE_ID") ENABLE;CREATE UNIQUE INDEX  "SYS_C007267" ON  "DEPT" ("DEPTNO") 
  ;CREATE UNIQUE INDEX  "SYS_C007269" ON  "EMP" ("EMPNO") 
  ;CREATE UNIQUE INDEX  "SYS_C007358" ON  "CUSTOMER" ("CUSTOMER_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007363" ON  "ADMIN" ("ADMIN_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007364" ON  "ADMIN" ("USERNAME") 
  ;CREATE UNIQUE INDEX  "SYS_C007365" ON  "ADMIN" ("EMAIL") 
  ;CREATE UNIQUE INDEX  "SYS_C007366" ON  "ADMIN" ("PHONE_NO") 
  ;CREATE UNIQUE INDEX  "SYS_C007380" ON  "ACCOUNT" ("USERNAME") 
  ;CREATE UNIQUE INDEX  "SYS_C007383" ON  "ROOMTYPE" ("TYPE_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007386" ON  "ROOM" ("ROOM_NO") 
  ;CREATE UNIQUE INDEX  "SYS_C007388" ON  "BOOKING" ("BOOKING_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007391" ON  "PAYMENT" ("PAYMENT_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007448" ON  "HOUSEKEEPER" ("EMAIL") 
  ;CREATE UNIQUE INDEX  "SYS_C007507" ON  "RECEIPT" ("RECEIPT_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007714" ON  "USERS" ("EMAIL") 
  ;CREATE UNIQUE INDEX  "SYS_C007751" ON  "STAFF" ("STAFF_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007761" ON  "BOOKINGS" ("ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007770" ON  "KEEPER" ("KEEPER_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007777" ON  "ROOMS" ("ROOMID") 
  ;CREATE UNIQUE INDEX  "SYS_C007781" ON  "ROOMTYPES" ("TYPE_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007807" ON  "RT" ("TYPE_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007876" ON  "PAYMENTS" ("PAYMENT_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007878" ON  "BOOKS" ("ISBN") 
  ;CREATE UNIQUE INDEX  "SYS_C007879" ON  "MEMBERS" ("MEMBER_ID") 
  ;CREATE UNIQUE INDEX  "UK_ROOM_NAME" ON  "ROOMTYPES" ("ROOM_NAME") 
  ; CREATE SEQUENCE   "USER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "STAFF_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "PAYMENT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "KEEP_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "BOOK_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;

INSERT INTO ADMIN (ADMIN_ID, USERNAME, PASSWORD, EMAIL, PHONE_NO, ADDRESS, NAME) VALUES 
(1, 'rk', 'ram@1998', 'rk@gmail.com', 9080120120, 'Sivakasi', 'Ram');


INSERT INTO rt (TYPE_ID, ROOM_NAME, BED_CAPACITY, AMENITY, NO_OF_ROOM, RENT) 
VALUES (2, 'Single', 1, 'Tv, Ac, Fridge', 10, 1500);

INSERT INTO rt (TYPE_ID, ROOM_NAME, BED_CAPACITY, AMENITY, NO_OF_ROOM, RENT) 
VALUES (3, 'Double', 2, 'Wifi, CarParking, Free Food', 12, 2500);

INSERT INTO rt (TYPE_ID, ROOM_NAME, BED_CAPACITY, AMENITY, NO_OF_ROOM, RENT) 
VALUES (4, 'Luxury', 3, 'Tv, Wifi, Free Food, Car Parking', 10, 6000);

INSERT INTO rt (TYPE_ID, ROOM_NAME, BED_CAPACITY, AMENITY, NO_OF_ROOM, RENT) 
VALUES (1, 'Deluxe Room', 2, 'WiFi, TV, Minibar', 10, 1500);


INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (2, 2, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (3, 2, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (10, 1, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (101, 1, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (101, 2, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (102, 2, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (103, 2, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (104, 2, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (105, 2, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (202, 3, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (203, 3, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (204, 3, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (205, 3, 'Booked', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (304, 4, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (305, 4, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (401, 1, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (402, 1, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (403, 1, 'Available', 'Clean');

INSERT INTO allroom (ROOM_ID, TYPE_ID, ROOM_STATUS, ROOM_CONDITION) 
VALUES (404, 1, 'Available', 'Clean');


INSERT INTO keeper (KEEPER_ID, NAME, EMAIL, PHONE_NO, PASSWORD, STATUS) 
VALUES (13, 'kailash', 'kailu@gmail.com', '9889908996', 'Welcome@123', 'Available');

INSERT INTO keeper (KEEPER_ID, NAME, EMAIL, PHONE_NO, PASSWORD, STATUS) 
VALUES (12, 'Haritha', 'haritha@gmail.com', '9080280170', 'Welcome@123', 'Available');


INSERT INTO staff (STAFF_ID, NAME, EMAIL, PASSWORD, PHONE_NO) 
VALUES (47, 'raju', 'raju@gmail.com', 'Welcome@123', '9554795589');

INSERT INTO staff (STAFF_ID, NAME, EMAIL, PASSWORD, PHONE_NO) 
VALUES (50, 'Ranjani', 'ranjani@gmail.com', 'Welcome@123', '9887909987');

INSERT INTO users (ID, FIRST_NAME, LAST_NAME, AGE, GENDER, PHONE, ADDRESS, STATE, EMAIL, PASSWORD) VALUES
(5, 'Jana', 'Master', 23, 'Male', '9070280190', 'Coimbatore', 'Punjab', 'jana@gmail.com', 'Jana@123');

INSERT INTO bookings (ID, CUSTOMER_NAME, GENDER, CHECK_IN, CHECK_OUT, BOOKING_STATUS, PHONE_NO, ROOM) VALUES
(45, 'AjithKumar', 'Male', TO_DATE('12-JUL-24', 'DD-MON-YY'), TO_DATE('15-JUL-24', 'DD-MON-YY'), 'Cancelled', '9898767889', 1);

INSERT INTO payments (PAYMENT_ID, BOOKING_ID, PAYMENT_AMT, PAYMENT_D, PAYMENT_METHOD, PAYMENT_STATUS) VALUES
(7, 17, 1500, TO_DATE('07-JUL-24', 'DD-MON-YY'), NULL, 'Paid');

INSERT INTO payments (PAYMENT_ID, BOOKING_ID, PAYMENT_AMT, PAYMENT_D, PAYMENT_METHOD, PAYMENT_STATUS) VALUES
(8, 18, 1500, TO_DATE('07-JUL-24', 'DD-MON-YY'), NULL, 'Paid');
