CREATE TABLE  "CATEGORY" 
   (    "CATEGORY_ID" NUMBER, 
    "CATEGORY_NAME" VARCHAR2(40), 
     PRIMARY KEY ("CATEGORY_ID") ENABLE
   ) ;


   insert into CATEGORY values(1001,'Food');
   
   
   CREATE TABLE  "CSUPERVISOR" 
   (    "C_SID" NUMBER NOT NULL ENABLE, 
    "NAME" VARCHAR2(20), 
    "ROLE" VARCHAR2(20), 
     CONSTRAINT "PK_CSUPERVISOR" PRIMARY KEY ("C_SID") ENABLE
   ) ;

   insert into CSUPERVISOR values(10001,'Ramesh','cleaner');
   
   
   CREATE TABLE  "DEPARTMENT" 
   (    "DEPARTMENT_ID" NUMBER, 
    "DEPARTMENT_NAME" VARCHAR2(10), 
     PRIMARY KEY ("DEPARTMENT_ID") ENABLE
   ) ;

  insert into DEPARTMENT values(10,'CSE');
  insert into DEPARTMENT values(20,'Civil');
  insert into DEPARTMENT values(30,'IT');
  insert into DEPARTMENT values(40,'Mech');

   
   CREATE TABLE  "ESUPERVISOR" 
   (    "E_SID" NUMBER NOT NULL ENABLE, 
    "NAME" VARCHAR2(20), 
    "ROLE" VARCHAR2(20), 
     CONSTRAINT "PK_ESUPERVISOR" PRIMARY KEY ("E_SID") ENABLE
   ) ;

   insert into ESUPERVISOR values(20001,'Suresh','Electrician');
   
   
   CREATE TABLE  "FSUPERVISOR" 
   (    "FU_ID" NUMBER NOT NULL ENABLE, 
    "NAME" VARCHAR2(20), 
    "ROLE" VARCHAR2(20), 
     CONSTRAINT "PK_FSUPERVISOR" PRIMARY KEY ("FU_ID") ENABLE
   ) ;

   insert into ESUPERVISOR values(30001,'Navadeep','Foodsupervisor');

   
   
   CREATE TABLE  "FURSUPERVISOR" 
   (    "FU_SID" NUMBER NOT NULL ENABLE, 
    "NAME" VARCHAR2(20), 
    "ROLE" VARCHAR2(20), 
     CONSTRAINT "PK_FURSUPERVISOR" PRIMARY KEY ("FU_SID") ENABLE
   ) ;

   
   insert into ESUPERVISOR values(40001,'Mithun','Carpenter');
   
   
   CREATE TABLE  "ISSUES" 
   (    "ISSUE_ID" NUMBER NOT NULL ENABLE, 
    "DESCRIPTION" VARCHAR2(100), 
    "TICKET_RAISED_DATE" DATE, 
    "CATEGORY_ID" NUMBER, 
    "RAISED_BY" VARCHAR2(30), 
    "ALLOCATED_TO" VARCHAR2(30), 
    "PRIORITY" VARCHAR2(15), 
    "ISSUETITLE" VARCHAR2(40), 
    "ISSUE_DATE" DATE, 
    "STATUS" VARCHAR2(20), 
     CONSTRAINT "PK_ISSUE" PRIMARY KEY ("ISSUE_ID") ENABLE
   ) ;
   
   
   
   CREATE TABLE  "STUDENT" 
   (    "ID" NUMBER, 
    "USERNAME" VARCHAR2(20), 
    "PASSWORD" VARCHAR2(20), 
    "ROLE" VARCHAR2(20), 
    "DEPARTMENT_ID" NUMBER, 
    "DATE_OF_JOINING" DATE, 
    "MAIL_ID" VARCHAR2(40), 
    "SECTION" VARCHAR2(5), 
    "NAME" VARCHAR2(20), 
    "YEAR" NUMBER, 
     PRIMARY KEY ("ID") ENABLE
   ) ;

   INSERT INTO STUDENT (ID, USERNAME, PASSWORD, ROLE, DEPARTMENT_ID, DATE_OF_JOINING, MAIL_ID, SECTION, NAME, YEAR) 
VALUES (1, 'Madhavaprasad2002', 'Madhava@123', 'Student', 101, TO_DATE('2024-09-01', 'YYYY-MM-DD'), 'Madhavaprasad2002@gmail.com', 'A', 'Madhava', 4);

   
   
   
   

   
   
   CREATE TABLE  "WARDEN" 
   (    "WARDEN_ID" NUMBER NOT NULL ENABLE, 
    "USERNAME" VARCHAR2(20), 
    "PASSWORD" VARCHAR2(20), 
    "MAIL_ID" VARCHAR2(30), 
    "NAME" VARCHAR2(20), 
    "ROLE" VARCHAR2(20), 
     CONSTRAINT "PK_WARDEN" PRIMARY KEY ("WARDEN_ID") ENABLE
   ) ;

   insert into warden values(1001,'jana02@gmail.com','jana@123','jana','warden');
insert into warden values(1002,'gopal02@gmail.com','gopal@123','gopal','warden');


   
   
   
   ALTER TABLE  "STUDENT" ADD FOREIGN KEY ("DEPARTMENT_ID")
      REFERENCES  "DEPARTMENT" ("DEPARTMENT_ID") ENABLE;CREATE UNIQUE INDEX  "PK_CSUPERVISOR" ON  "CSUPERVISOR" ("C_SID") 
  ;CREATE UNIQUE INDEX  "PK_ESUPERVISOR" ON  "ESUPERVISOR" ("E_SID") 
  ;CREATE UNIQUE INDEX  "PK_FSUPERVISOR" ON  "FSUPERVISOR" ("FU_ID") 
  ;CREATE UNIQUE INDEX  "PK_FURSUPERVISOR" ON  "FURSUPERVISOR" ("FU_SID") 
  ;CREATE UNIQUE INDEX  "PK_ISSUE" ON  "ISSUES" ("ISSUE_ID") 
  ;CREATE UNIQUE INDEX  "PK_SUPERVISOR" ON  "SUPERVISOR" ("SUPERID") 
  ;CREATE UNIQUE INDEX  "PK_WARDEN" ON  "WARDEN" ("WARDEN_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C008169" ON  "DEPT" ("DEPTNO") 
  ;CREATE UNIQUE INDEX  "SYS_C008171" ON  "EMP" ("EMPNO") 
  ;CREATE UNIQUE INDEX  "SYS_C008256" ON  "STUDENT" ("ID") 
  ;CREATE UNIQUE INDEX  "SYS_C008259" ON  "DEPARTMENT" ("DEPARTMENT_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C008260" ON  "CATEGORY" ("CATEGORY_ID") 
  ;
