CREATE TABLE  "ADMIN" 
   (    "ADMIN_ID" NUMBER, 
    "USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(30) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
    "PHONE_NO" NUMBER(10,0) NOT NULL ENABLE, 
    "ADDRESS" VARCHAR2(50), 
    "NAME" VARCHAR2(50), 
     PRIMARY KEY ("ADMIN_ID") ENABLE, 
     UNIQUE ("USERNAME") ENABLE, 
     UNIQUE ("EMAIL") ENABLE, 
     UNIQUE ("PHONE_NO") ENABLE
   ) ;CREATE TABLE  "CUSTOMER" 
   (    "CUSTOMER_ID" NUMBER, 
    "F_NAME" VARCHAR2(25) NOT NULL ENABLE, 
    "L_NAME" VARCHAR2(25) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
    "PHONE_NO" NUMBER(10,0), 
    "ADDRESS" VARCHAR2(100) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(30) NOT NULL ENABLE, 
     PRIMARY KEY ("CUSTOMER_ID") ENABLE, 
     CONSTRAINT "E_UNIQUE" UNIQUE ("EMAIL") ENABLE
   ) ;CREATE TABLE  "ROOMTYPE" 
   (    "TYPE_ID" NUMBER, 
    "TYPE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
    "ROOM_CAPACITY" NUMBER NOT NULL ENABLE, 
    "AMENITIES" VARCHAR2(255), 
    "PRICEPERNIGHT" NUMBER(10,2), 
     PRIMARY KEY ("TYPE_ID") ENABLE
   ) ;CREATE TABLE  "ROOM" 
   (    "ROOM_NO" NUMBER, 
    "TYPE_ID" NUMBER, 
    "ROOM_STATUS" VARCHAR2(50) NOT NULL ENABLE, 
    "ROOM_CONDITION" VARCHAR2(30) NOT NULL ENABLE, 
    "HOUSEKEEPING_REQUEST" VARCHAR2(100), 
     PRIMARY KEY ("ROOM_NO") ENABLE
   ) ;CREATE TABLE  "BOOKING" 
   (    "BOOKING_ID" NUMBER, 
    "CUSTOMER_ID" NUMBER, 
    "ROOM_NO" NUMBER, 
    "CHECKIN" DATE NOT NULL ENABLE, 
    "CHECKOUT" DATE NOT NULL ENABLE, 
    "BOOKING_STATUS" VARCHAR2(30), 
     PRIMARY KEY ("BOOKING_ID") ENABLE
   ) ;CREATE TABLE  "HOUSEKEEPER" 
   (    "NAME" VARCHAR2(30), 
    "KEEPER_ID" NUMBER, 
    "EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
    "PHONE_NO" NUMBER(10,0), 
    "PASSWORD" VARCHAR2(30), 
    "LAST_CLEAN" DATE, 
    "NEXT_CLEAN" DATE, 
     UNIQUE ("EMAIL") ENABLE
   ) ;CREATE TABLE  "PAYMENT" 
   (    "PAYMENT_ID" NUMBER, 
    "BOOKING_ID" NUMBER, 
    "PAYMENT_AMT" NUMBER, 
    "PAYMENT_DATE" DATE, 
    "PAYMENT_METHOD" VARCHAR2(30), 
    "PAYMENT_STATUS" VARCHAR2(20) DEFAULT 'Paid', 
     PRIMARY KEY ("PAYMENT_ID") ENABLE
   ) ;CREATE TABLE  "RECEIPT" 
   (    "RECEIPT_ID" NUMBER, 
    "BOOKING_ID" NUMBER NOT NULL ENABLE, 
    "ROOM_NO" NUMBER NOT NULL ENABLE, 
    "AMOUNT" NUMBER NOT NULL ENABLE, 
    "RECEIPT_DATE" DATE NOT NULL ENABLE, 
     PRIMARY KEY ("RECEIPT_ID") ENABLE
   ) ;CREATE TABLE  "RECEPTIONIST" 
   (    "NAME" VARCHAR2(30) NOT NULL ENABLE, 
    "EMPLOYEE_ID" NUMBER NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(30) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
    "PHONE_NO" NUMBER(10,0) NOT NULL ENABLE
   ) ;ALTER TABLE  "ROOM" ADD FOREIGN KEY ("TYPE_ID")
      REFERENCES  "ROOMTYPE" ("TYPE_ID") ENABLE;ALTER TABLE  "BOOKING" ADD FOREIGN KEY ("CUSTOMER_ID")
      REFERENCES  "CUSTOMER" ("CUSTOMER_ID") ENABLE;ALTER TABLE  "BOOKING" ADD FOREIGN KEY ("ROOM_NO")
      REFERENCES  "ROOM" ("ROOM_NO") ENABLE;ALTER TABLE  "PAYMENT" ADD FOREIGN KEY ("BOOKING_ID")
      REFERENCES  "BOOKING" ("BOOKING_ID") ENABLE;ALTER TABLE  "RECEIPT" ADD FOREIGN KEY ("BOOKING_ID")
      REFERENCES  "BOOKING" ("BOOKING_ID") ENABLE;ALTER TABLE  "RECEIPT" ADD FOREIGN KEY ("ROOM_NO")
      REFERENCES  "ROOM" ("ROOM_NO") ENABLE; CREATE SEQUENCE   "RECEIPT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "P_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "HKID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "EMPID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "CUSID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "BOOK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE ;