CREATE TABLE "ADMIN"
(
    "EMAIL" VARCHAR2(20),
    "PASSWORD" VARCHAR2(20)
);

CREATE TABLE "COURSE"
(
    "CID" NUMBER,
    "CNAME" VARCHAR2(20) NOT NULL ENABLE,
    "START_DATE" DATE,
    "END_DATE" DATE,
    PRIMARY KEY ("CID") ENABLE
);

CREATE TABLE "EDUCATOR"
(
    "EID" NUMBER,
    "EMAIL" VARCHAR2(30) NOT NULL ENABLE,
    "PASSWORD" VARCHAR2(20) NOT NULL ENABLE,
    "FNAME" VARCHAR2(20) NOT NULL ENABLE,
    "LNAME" VARCHAR2(20),
    "GENDER" CHAR(1) NOT NULL ENABLE,
    "CITY" VARCHAR2(20) NOT NULL ENABLE,
    "COUNTRY" VARCHAR2(20) NOT NULL ENABLE,
    PRIMARY KEY ("EID") ENABLE,
    CONSTRAINT "UNIQUEEMAILEDU" UNIQUE ("EMAIL") ENABLE
);

CREATE TABLE "ASSESSMENT"
(
    "AID" NUMBER,
    "ANAME" VARCHAR2(20),
    "STTIME" VARCHAR2(10),
    "ENDTIME" VARCHAR2(10),
    "DURATION" NUMBER,
    "TOT_MARK" NUMBER,
    "CID" NUMBER,
    "ADATE" DATE,
    "EID" NUMBER,
    PRIMARY KEY ("AID") ENABLE
);

CREATE TABLE "BOOK"
(
    "ISBN" VARCHAR2(20),
    "NAME" VARCHAR2(20),
    "AUTHOR" VARCHAR2(20),
    "ISAVAILABLE" CHAR(1)
);

CREATE TABLE "DEPT"
(
    "DEPTNO" NUMBER(2,0),
    "DNAME" VARCHAR2(14),
    "LOC" VARCHAR2(13),
    PRIMARY KEY ("DEPTNO") ENABLE
);

CREATE TABLE "EDUCATORCOURSE"
(
    "EID" NUMBER,
    "CID" NUMBER,
    PRIMARY KEY ("EID", "CID") ENABLE
);

CREATE TABLE "EMP"
(
    "EMPNO" NUMBER(4,0) NOT NULL ENABLE,
    "ENAME" VARCHAR2(10),
    "JOB" VARCHAR2(9),
    "MGR" NUMBER(4,0),
    "HIREDATE" DATE,
    "SAL" NUMBER(7,2),
    "COMM" NUMBER(7,2),
    "DEPTNO" NUMBER(2,0),
    PRIMARY KEY ("EMPNO") ENABLE
);

CREATE TABLE "MEMBER"
(
    "MEMBERID" NUMBER,
    "NAME" VARCHAR2(20),
    "EMAIL" VARCHAR2(20),
    "PHONE" VARCHAR2(20)
);

CREATE TABLE "QUESTION"
(
    "QID" NUMBER,
    "QUESTIONS" VARCHAR2(255),
    "C1" VARCHAR2(255),
    "C2" VARCHAR2(255),
    "C3" VARCHAR2(255),
    "C4" VARCHAR2(255),
    "ANSWER" VARCHAR2(10),
    "MARK" NUMBER,
    PRIMARY KEY ("QID") ENABLE
);

CREATE TABLE "QUESTIONASSESSMENT"
(
    "AID" NUMBER,
    "QID" NUMBER
);

CREATE TABLE "SPRING"
(
    "ID" NUMBER,
    "NAME" VARCHAR2(10),
    "AGE" NUMBER
);

CREATE TABLE "STUDENT"
(
    "SID" NUMBER,
    "EMAIL" VARCHAR2(30) NOT NULL ENABLE,
    "PASSWORD" VARCHAR2(20) NOT NULL ENABLE,
    "FNAME" VARCHAR2(20) NOT NULL ENABLE,
    "LNAME" VARCHAR2(20) NOT NULL ENABLE,
    "GENDER" CHAR(1) NOT NULL ENABLE,
    "CITY" VARCHAR2(20) NOT NULL ENABLE,
    "COUNTRY" VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "PK_SID" PRIMARY KEY ("SID") ENABLE,
    CONSTRAINT "UNIQUEEMAIL" UNIQUE ("EMAIL") ENABLE
);

CREATE TABLE "STUDENTANSWER"
(
    "ANSID" NUMBER,
    "SID" NUMBER,
    "QID" NUMBER,
    "STUDANSWER" VARCHAR2(5),
    "AID" NUMBER,
    PRIMARY KEY ("ANSID") ENABLE
);

CREATE TABLE "STUDENTCOURSE"
(
    "SID" NUMBER(*,0),
    "CID" NUMBER(*,0),
    PRIMARY KEY ("SID", "CID") ENABLE
);

CREATE TABLE "STUDENTMARK"
(
    "SID" NUMBER,
    "AID" NUMBER,
    "TOT_MARK" NUMBER
);

-- Adding foreign keys
ALTER TABLE "STUDENTANSWER" ADD CONSTRAINT "FK_AID_2" FOREIGN KEY ("QID") REFERENCES "QUESTION" ("QID") ENABLE;
ALTER TABLE "STUDENTANSWER" ADD CONSTRAINT "FK_AID_ANS" FOREIGN KEY ("SID") REFERENCES "STUDENT" ("SID") ENABLE;
ALTER TABLE "ASSESSMENT" ADD CONSTRAINT "FK_AID_ASSESS" FOREIGN KEY ("EID") REFERENCES "EDUCATOR" ("EID") ENABLE;
ALTER TABLE "STUDENTMARK" ADD CONSTRAINT "FK_AID_STUDENT" FOREIGN KEY ("AID") REFERENCES "ASSESSMENT" ("AID") ENABLE;
ALTER TABLE "STUDENTMARK" ADD CONSTRAINT "FK_AID_STUDENTMARK" FOREIGN KEY ("SID") REFERENCES "STUDENT" ("SID") ENABLE;
ALTER TABLE "ASSESSMENT" ADD CONSTRAINT "FK_CID_A" FOREIGN KEY ("CID") REFERENCES "COURSE" ("CID") ENABLE;
ALTER TABLE "STUDENTANSWER" ADD CONSTRAINT "FK_STUDENTANSWER_AID" FOREIGN KEY ("AID") REFERENCES "ASSESSMENT" ("AID") ENABLE;
ALTER TABLE "EMP" ADD FOREIGN KEY ("MGR") REFERENCES "EMP" ("EMPNO") ENABLE;
ALTER TABLE "EMP" ADD FOREIGN KEY ("DEPTNO") REFERENCES "DEPT" ("DEPTNO") ENABLE;
ALTER TABLE "QUESTIONASSESSMENT" ADD FOREIGN KEY ("AID") REFERENCES "ASSESSMENT" ("AID") ENABLE;
ALTER TABLE "QUESTIONASSESSMENT" ADD FOREIGN KEY ("QID") REFERENCES "QUESTION" ("QID") ENABLE;
ALTER TABLE "STUDENTCOURSE" ADD FOREIGN KEY ("SID") REFERENCES "STUDENT" ("SID") ENABLE;
ALTER TABLE "STUDENTCOURSE" ADD FOREIGN KEY ("CID") REFERENCES "COURSE" ("CID") ENABLE;
ALTER TABLE "EDUCATORCOURSE" ADD FOREIGN KEY ("EID") REFERENCES "EDUCATOR" ("EID") ENABLE;
ALTER TABLE "EDUCATORCOURSE" ADD FOREIGN KEY ("CID") REFERENCES "COURSE" ("CID") ENABLE;

-- Creating unique indexes
CREATE UNIQUE INDEX "PK_SID" ON "STUDENT" ("SID");
CREATE UNIQUE INDEX "SYS_C007242" ON "DEPT" ("DEPTNO");
CREATE UNIQUE INDEX "SYS_C007244" ON "EMP" ("EMPNO");
CREATE UNIQUE INDEX "SYS_C007329" ON "EDUCATOR" ("EID");
CREATE UNIQUE INDEX "SYS_C007330" ON "COURSE" ("CID");
CREATE UNIQUE INDEX "SYS_C007331" ON "ASSESSMENT" ("AID");
CREATE UNIQUE INDEX "SYS_C007332" ON "QUESTION" ("QID");
CREATE UNIQUE INDEX "SYS_C007413" ON "STUDENTANSWER" ("ANSID");
CREATE UNIQUE INDEX "SYS_C007465" ON "STUDENTCOURSE" ("SID", "CID");
CREATE UNIQUE INDEX "SYS_C007475" ON "EDUCATORCOURSE" ("EID", "CID");
CREATE UNIQUE INDEX "UNIQUEEMAIL" ON "STUDENT" ("EMAIL");
CREATE UNIQUE INDEX "UNIQUEEMAILEDU" ON "EDUCATOR" ("EMAIL");

-- Creating sequences
CREATE SEQUENCE "STUSEQ" MINVALUE 201 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 271 CACHE 10 NOORDER NOCYCLE;
CREATE SEQUENCE "QUESSEQ" MINVALUE 501 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 591 CACHE 10 NOORDER NOCYCLE;
CREATE SEQUENCE "EDUSEQ" MINVALUE 101 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 10 NOORDER NOCYCLE;
CREATE SEQUENCE "COURSESEQ" MINVALUE 301 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 331 CACHE 10 NOORDER NOCYCLE;
CREATE SEQUENCE "ASSESSSEQ" MINVALUE 401 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 511 CACHE 10 NOORDER NOCYCLE;
CREATE SEQUENCE "ANSSEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1274 NOCACHE NOORDER NOCYCLE;
