CREATE TABLE  "ADMIN" 
   (    "ADMIN_ID" NUMBER(10,0), 
    "FIRST_NAME" VARCHAR2(20), 
    "LAST_NAME" VARCHAR2(20), 
    "EMAIL" VARCHAR2(30), 
    "GENDER" VARCHAR2(20), 
    "PHONE_NUMBER" NUMBER(10,0), 
    "PASSWORD" VARCHAR2(20), 
    "ACCOUNT_STATUS" VARCHAR2(20), 
    "USERNAME" VARCHAR2(20) NOT NULL ENABLE, 
     PRIMARY KEY ("ADMIN_ID") ENABLE
   ) ;CREATE TABLE  "USERS" 
   (    "USER_ID" NUMBER(10,0), 
    "FIRST_NAME" VARCHAR2(20) NOT NULL ENABLE, 
    "LAST_NAME" VARCHAR2(20) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(30) NOT NULL ENABLE, 
    "GENDER" VARCHAR2(20), 
    "PHONE_NUMBER" NUMBER(10,0) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(20) NOT NULL ENABLE, 
    "ACCOUNT_STATUS" VARCHAR2(20), 
    "LICENSE_ID" VARCHAR2(20), 
    "USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
     PRIMARY KEY ("USER_ID") ENABLE, 
     CONSTRAINT "UC_USERNAME" UNIQUE ("USERNAME") ENABLE
   ) ;CREATE TABLE  "BOOKING" 
   (    "BOOKING_ID" NUMBER(10,0), 
    "USER_ID" NUMBER(10,0), 
    "START_DATE" TIMESTAMP (6), 
    "END_DATE" TIMESTAMP (6), 
    "TOTAL_AMOUNT" NUMBER(20,0), 
    "RENTAL_STATUS" VARCHAR2(20), 
    "CAR_ID" NUMBER, 
    "PACKAGE_ID" NUMBER, 
     PRIMARY KEY ("BOOKING_ID") ENABLE
   ) ;CREATE TABLE  "CAR" 
   (    "CAR_ID" NUMBER(10,0), 
    "CAR_NAME" VARCHAR2(20), 
    "MODEL" VARCHAR2(20), 
    "RENTAL_RATE" NUMBER(10,0), 
    "AVAILABILITY" VARCHAR2(20), 
    "SEAT" NUMBER(10,0), 
    "BAGGAGE" NUMBER(10,0), 
    "FUEL_TYPE" VARCHAR2(20), 
    "MILEAGE" VARCHAR2(20), 
    "VEHICLE_NUMBER" VARCHAR2(10), 
    "CAR_TYPE" VARCHAR2(20), 
     PRIMARY KEY ("CAR_ID") ENABLE
   ) ;CREATE TABLE  "PAYMENT" 
   (    "PAYMENT_ID" NUMBER(20,0), 
    "TOTAL_AMOUNT" NUMBER(20,0), 
    "PAYMENT_DATE" DATE, 
    "PAYMENT_METHOD" VARCHAR2(20), 
    "PAYMENT_STATUS" VARCHAR2(20), 
    "BOOKING_ID" NUMBER, 
     PRIMARY KEY ("PAYMENT_ID") ENABLE
   ) ;CREATE TABLE  "RENTAL_PACKAGE" 
   (    "DURATION" VARCHAR2(20), 
    "CAR_TYPE" VARCHAR2(20), 
    "AMOUNT" NUMBER(20,0), 
    "PACKAGEID" NUMBER, 
     PRIMARY KEY ("PACKAGEID") ENABLE
   ) ;ALTER TABLE  "BOOKING" ADD FOREIGN KEY ("USER_ID")
      REFERENCES  "USERS" ("USER_ID") ENABLE;CREATE UNIQUE INDEX  "SYS_C007214" ON  "DEPT" ("DEPTNO") 
  ;CREATE UNIQUE INDEX  "SYS_C007216" ON  "EMP" ("EMPNO") 
  ;CREATE UNIQUE INDEX  "SYS_C007307" ON  "USERS" ("USER_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007310" ON  "ADMIN" ("ADMIN_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007311" ON  "CAR" ("CAR_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007312" ON  "RENTAL_PACKAGE" ("PACKAGEID") 
  ;CREATE UNIQUE INDEX  "SYS_C007313" ON  "BOOKING" ("BOOKING_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007315" ON  "PAYMENT" ("PAYMENT_ID") 
  ;CREATE UNIQUE INDEX  "UC_USERNAME" ON  "USERS" ("USERNAME") 
  ; CREATE SEQUENCE   "USERSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE 
      "SEQ_PACKID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "PAYMENTSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "CARSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "BOOKSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  NOORDER  NOCYCLE ;

INSERT INTO admin (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, USERNAME)
VALUES (1, 'Alice', 'Smith', 'alice.smith@example.com', 'Female', '123-456-7890', 'alicepassword', 'Active', 'alicesmith');

INSERT INTO admin (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, USERNAME)
VALUES (2, 'Bob', 'Johnson', 'bob.johnson@example.com', 'Male', '098-765-4321', 'bobpassword', 'Inactive', 'bobjohnson');

INSERT INTO admin (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, USERNAME)
VALUES (3, 'Charlie', 'Brown', 'charlie.brown@example.com', 'Male', '555-123-4567', 'charliepassword', 'Active', 'charliebrown');

INSERT INTO admin (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, USERNAME)
VALUES (4, 'Dana', 'White', 'dana.white@example.com', 'Female', '444-987-6543', 'danapassword', 'Active', 'danawhite');

INSERT INTO users (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, LICENSE_ID, USERNAME)
VALUES (1, 'John', 'Doe', 'john.doe@example.com', 'Male', '123-456-7890', 'password123', 'Active', 'LIC1001', 'johndoe');

INSERT INTO users (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, LICENSE_ID, USERNAME)
VALUES (2, 'Jane', 'Smith', 'jane.smith@example.com', 'Female', '098-765-4321', 'password456', 'Inactive', 'LIC1002', 'janesmith');

INSERT INTO users (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, LICENSE_ID, USERNAME)
VALUES (3, 'Alice', 'Johnson', 'alice.johnson@example.com', 'Female', '555-123-4567', 'alicepwd', 'Active', 'LIC1003', 'alicejohnson');

INSERT INTO users (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, LICENSE_ID, USERNAME)
VALUES (4, 'Bob', 'Brown', 'bob.brown@example.com', 'Male', '444-987-6543', 'bobpassword', 'Active', 'LIC1004', 'bobbrown');

INSERT INTO booking (BOOKING_ID, USER_ID, START_DATE, END_DATE, TOTAL_AMOUNT, RENTAL_STATUS, CAR_ID, PACKAGE_ID)
VALUES (1, 101, '2024-08-01', '2024-08-05', 500.00, 'Confirmed', 201, 301);

INSERT INTO booking (BOOKING_ID, USER_ID, START_DATE, END_DATE, TOTAL_AMOUNT, RENTAL_STATUS, CAR_ID, PACKAGE_ID)
VALUES (2, 102, '2024-08-10', '2024-08-15', 750.50, 'Pending', 202, 302);

INSERT INTO booking (BOOKING_ID, USER_ID, START_DATE, END_DATE, TOTAL_AMOUNT, RENTAL_STATUS, CAR_ID, PACKAGE_ID)
VALUES (3, 103, '2024-09-01', '2024-09-03', 200.00, 'Completed', 203, 303);

INSERT INTO booking (BOOKING_ID, USER_ID, START_DATE, END_DATE, TOTAL_AMOUNT, RENTAL_STATUS, CAR_ID, PACKAGE_ID)
VALUES (4, 104, '2024-09-10', '2024-09-12', 300.00, 'Cancelled', 204, 304);

INSERT INTO car (CAR_ID, CAR_NAME, MODEL, RENTAL_RATE, AVAILABILITY, SEAT, BAGGAGE, FUEL_TYPE, MILEAGE, VEHICLE_NUMBER, CAR_TYPE)
VALUES (1, 'Toyota Camry', '2022', 45.00, 'Available', 5, 2, 'Petrol', 30, 'XYZ1234', 'Sedan');

INSERT INTO car (CAR_ID, CAR_NAME, MODEL, RENTAL_RATE, AVAILABILITY, SEAT, BAGGAGE, FUEL_TYPE, MILEAGE, VEHICLE_NUMBER, CAR_TYPE)
VALUES (2, 'Honda Civic', '2023', 50.00, 'Rented', 5, 2, 'Diesel', 35, 'ABC5678', 'Sedan');

INSERT INTO car (CAR_ID, CAR_NAME, MODEL, RENTAL_RATE, AVAILABILITY, SEAT, BAGGAGE, FUEL_TYPE, MILEAGE, VEHICLE_NUMBER, CAR_TYPE)
VALUES (3, 'Ford Explorer', '2021', 70.00, 'Available', 7, 4, 'Petrol', 20, 'LMN9101', 'SUV');

INSERT INTO car (CAR_ID, CAR_NAME, MODEL, RENTAL_RATE, AVAILABILITY, SEAT, BAGGAGE, FUEL_TYPE, MILEAGE, VEHICLE_NUMBER, CAR_TYPE)
VALUES (4, 'Chevrolet Malibu', '2022', 55.00, 'Maintenance', 5, 3, 'Hybrid', 25, 'QRS2345', 'Sedan');

INSERT INTO payment (PAYMENT_ID, TOTAL_AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, PAYMENT_STATUS, BOOKING_ID)
VALUES (1, 500.00, '2024-08-01', 'Credit Card', 'Completed', 1);

INSERT INTO payment (PAYMENT_ID, TOTAL_AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, PAYMENT_STATUS, BOOKING_ID)
VALUES (2, 750.50, '2024-08-10', 'PayPal', 'Pending', 2);

INSERT INTO payment (PAYMENT_ID, TOTAL_AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, PAYMENT_STATUS, BOOKING_ID)
VALUES (3, 200.00, '2024-09-01', 'Debit Card', 'Completed', 3);

INSERT INTO payment (PAYMENT_ID, TOTAL_AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, PAYMENT_STATUS, BOOKING_ID)
VALUES (4, 300.00, '2024-09-10', 'Bank Transfer', 'Cancelled', 4);

INSERT INTO rental_package (DURATION, CAR_TYPE, AMOUNT, PACKAGEID)
VALUES ('1 Day', 'Sedan', 50.00, 101);

INSERT INTO rental_package (DURATION, CAR_TYPE, AMOUNT, PACKAGEID)
VALUES ('3 Days', 'SUV', 150.00, 102);

INSERT INTO rental_package (DURATION, CAR_TYPE, AMOUNT, PACKAGEID)
VALUES ('1 Week', 'Convertible', 400.00, 103);

INSERT INTO rental_package (DURATION, CAR_TYPE, AMOUNT, PACKAGEID)
VALUES ('Weekend', 'Hatchback', 75.00, 104);



