CREATE TABLE  "ADMIN" 
   (    "ADMIN_ID" NUMBER(10,0), 
    "FIRST_NAME" VARCHAR2(20), 
    "LAST_NAME" VARCHAR2(20), 
    "EMAIL" VARCHAR2(30), 
    "GENDER" VARCHAR2(20), 
    "PHONE_NUMBER" NUMBER(10,0), 
    "PASSWORD" VARCHAR2(20), 
    "ACCOUNT_STATUS" VARCHAR2(20), 
    "USERNAME" VARCHAR2(20) NOT NULL ENABLE, 
     PRIMARY KEY ("ADMIN_ID") ENABLE
   ) ;CREATE TABLE  "USERS" 
   (    "USER_ID" NUMBER(10,0), 
    "FIRST_NAME" VARCHAR2(20) NOT NULL ENABLE, 
    "LAST_NAME" VARCHAR2(20) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(30) NOT NULL ENABLE, 
    "GENDER" VARCHAR2(20), 
    "PHONE_NUMBER" NUMBER(10,0) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(20) NOT NULL ENABLE, 
    "ACCOUNT_STATUS" VARCHAR2(20), 
    "LICENSE_ID" VARCHAR2(20), 
    "USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
     PRIMARY KEY ("USER_ID") ENABLE, 
     CONSTRAINT "UC_USERNAME" UNIQUE ("USERNAME") ENABLE
   ) ;CREATE TABLE  "BOOKING" 
   (    "BOOKING_ID" NUMBER(10,0), 
    "USER_ID" NUMBER(10,0), 
    "START_DATE" TIMESTAMP (6), 
    "END_DATE" TIMESTAMP (6), 
    "TOTAL_AMOUNT" NUMBER(20,0), 
    "RENTAL_STATUS" VARCHAR2(20), 
    "CAR_ID" NUMBER, 
    "PACKAGE_ID" NUMBER, 
     PRIMARY KEY ("BOOKING_ID") ENABLE
   ) ;CREATE TABLE  "CAR" 
   (    "CAR_ID" NUMBER(10,0), 
    "CAR_NAME" VARCHAR2(20), 
    "MODEL" VARCHAR2(20), 
    "RENTAL_RATE" NUMBER(10,0), 
    "AVAILABILITY" VARCHAR2(20), 
    "SEAT" NUMBER(10,0), 
    "BAGGAGE" NUMBER(10,0), 
    "FUEL_TYPE" VARCHAR2(20), 
    "MILEAGE" VARCHAR2(20), 
    "VEHICLE_NUMBER" VARCHAR2(10), 
    "CAR_TYPE" VARCHAR2(20), 
     PRIMARY KEY ("CAR_ID") ENABLE
   ) ;CREATE TABLE  "PAYMENT" 
   (    "PAYMENT_ID" NUMBER(20,0), 
    "TOTAL_AMOUNT" NUMBER(20,0), 
    "PAYMENT_DATE" DATE, 
    "PAYMENT_METHOD" VARCHAR2(20), 
    "PAYMENT_STATUS" VARCHAR2(20), 
    "BOOKING_ID" NUMBER, 
     PRIMARY KEY ("PAYMENT_ID") ENABLE
   ) ;CREATE TABLE  "RENTAL_PACKAGE" 
   (    "DURATION" VARCHAR2(20), 
    "CAR_TYPE" VARCHAR2(20), 
    "AMOUNT" NUMBER(20,0), 
    "PACKAGEID" NUMBER, 
     PRIMARY KEY ("PACKAGEID") ENABLE
   ) ;ALTER TABLE  "BOOKING" ADD FOREIGN KEY ("USER_ID")
      REFERENCES  "USERS" ("USER_ID") ENABLE;CREATE UNIQUE INDEX  "SYS_C007214" ON  "DEPT" ("DEPTNO") 
  ;CREATE UNIQUE INDEX  "SYS_C007216" ON  "EMP" ("EMPNO") 
  ;CREATE UNIQUE INDEX  "SYS_C007307" ON  "USERS" ("USER_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007310" ON  "ADMIN" ("ADMIN_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007311" ON  "CAR" ("CAR_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007312" ON  "RENTAL_PACKAGE" ("PACKAGEID") 
  ;CREATE UNIQUE INDEX  "SYS_C007313" ON  "BOOKING" ("BOOKING_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007315" ON  "PAYMENT" ("PAYMENT_ID") 
  ;CREATE UNIQUE INDEX  "UC_USERNAME" ON  "USERS" ("USERNAME") 
  ; CREATE SEQUENCE   "USERSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "SEQ_PACKID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "PAYMENTSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "CARSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "BOOKSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  NOORDER  NOCYCLE ;