CREATE TABLE  "BOOKING" 
   (    "BOOKING_ID" NUMBER(*,0), 
    "START_DATE" DATE NOT NULL ENABLE, 
    "END_DATE" DATE NOT NULL ENABLE, 
    "BOOKING_STATUS" VARCHAR2(20) NOT NULL ENABLE, 
    "CAR_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "USER_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "RENTAL_RATE" NUMBER(10,2) NOT NULL ENABLE, 
     PRIMARY KEY ("BOOKING_ID") ENABLE
   ) ;CREATE TABLE  "CAR" 
   (    "SID" NUMBER(*,0), 
    "FNAME" VARCHAR2(50), 
    "LNAME" VARCHAR2(50), 
    "EMAIL" VARCHAR2(100)
   ) ;CREATE TABLE  "PAYMENTS" 
   (    "ID" NUMBER, 
    "USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "CARNAME" VARCHAR2(100) NOT NULL ENABLE, 
    "CARDHOLDER_NAME" VARCHAR2(100) NOT NULL ENABLE, 
    "CARD_NUMBER" VARCHAR2(19) NOT NULL ENABLE, 
    "CARD_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
    "EXP_DATE" DATE NOT NULL ENABLE, 
    "CVV" VARCHAR2(4) NOT NULL ENABLE, 
    "CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
     PRIMARY KEY ("ID") ENABLE
   ) ;CREATE TABLE  "RENTAL_PACKAGE" 
   (    "PACKAGE_ID" NUMBER, 
    "CAR_NAME" VARCHAR2(255) NOT NULL ENABLE, 
    "VEHICLE_NO" VARCHAR2(50) NOT NULL ENABLE, 
    "AVAILABLE" VARCHAR2(3) NOT NULL ENABLE, 
    "RENTAL_RATE" NUMBER(10,2) NOT NULL ENABLE, 
    "SEAT_COUNT" NUMBER NOT NULL ENABLE, 
    "FUEL_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
    "CAR_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
    "BAGS" NUMBER NOT NULL ENABLE, 
    "CAR_IMAGE_URL" VARCHAR2(255) NOT NULL ENABLE, 
    "DURATION" VARCHAR2(10) NOT NULL ENABLE, 
     CHECK (available IN ('yes', 'no')) ENABLE, 
     PRIMARY KEY ("PACKAGE_ID") ENABLE, 
     CHECK (duration IN ('day', 'week', 'month')) ENABLE
   ) ;CREATE TABLE  "USERS" 
   (    "USER_ID" NUMBER(*,0), 
    "FIRST_NAME" VARCHAR2(255), 
    "LAST_NAME" VARCHAR2(255), 
    "EMAIL" VARCHAR2(255), 
    "GENDER" VARCHAR2(10), 
    "PHONE_NUMBER" VARCHAR2(15), 
    "PASSWORD" VARCHAR2(255), 
    "ACCOUNT_STATUS" VARCHAR2(20), 
    "LICENSE_ID" VARCHAR2(20), 
    "USERNAME" VARCHAR2(255), 
     PRIMARY KEY ("USER_ID") ENABLE
   ) ; CREATE SEQUENCE   "USER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "PAYMENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "CAR_ID_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "CAR_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "BOOKING_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE ;CREATE OR REPLACE TRIGGER  "CAR_ID_TRIGGER" 
BEFORE INSERT ON CARS
FOR EACH ROW
 WHEN (NEW.CAR_ID IS NULL) BEGIN
  SELECT car_id_seq1.NEXTVAL INTO :NEW.CAR_ID FROM dual;
END;
/
ALTER TRIGGER  "CAR_ID_TRIGGER" ENABLE;CREATE OR REPLACE TRIGGER  "BOOKING_ID_TRIGGER" 
BEFORE INSERT ON BOOKINGS
FOR EACH ROW
BEGIN
    IF :NEW.BOOKING_ID IS NULL THEN
        SELECT booking_id_seq.NEXTVAL
        INTO :NEW.BOOKING_ID
        FROM dual;
    END IF;
END;
/
ALTER TRIGGER  "BOOKING_ID_TRIGGER" ENABLE;