CREATE TABLE  "BOOKING" 
   (    "BOOKING_ID" NUMBER(*,0), 
    "START_DATE" DATE NOT NULL ENABLE, 
    "END_DATE" DATE NOT NULL ENABLE, 
    "BOOKING_STATUS" VARCHAR2(20) NOT NULL ENABLE, 
    "CAR_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "USER_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "RENTAL_RATE" NUMBER(10,2) NOT NULL ENABLE, 
     PRIMARY KEY ("BOOKING_ID") ENABLE
   ) ;CREATE TABLE cars (
    CAR_ID INT PRIMARY KEY AUTO_INCREMENT,
    CAR_NAME VARCHAR(100) NOT NULL,
    VEHICLE_NO VARCHAR(50) UNIQUE NOT NULL,
    AVAILABLE BOOLEAN NOT NULL DEFAULT TRUE,
    RENTAL_RATE DECIMAL(10, 2) NOT NULL,
    SEAT_COUNT INT NOT NULL,
    FUEL_TYPE VARCHAR(20) NOT NULL,
    CAR_TYPE VARCHAR(20) NOT NULL,
    BAGS INT NOT NULL,
    CAR_IMAGE_URL VARCHAR(255)
);
CREATE TABLE  "PAYMENTS" 
   (    "ID" NUMBER, 
    "USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "CARNAME" VARCHAR2(100) NOT NULL ENABLE, 
    "CARDHOLDER_NAME" VARCHAR2(100) NOT NULL ENABLE, 
    "CARD_NUMBER" VARCHAR2(19) NOT NULL ENABLE, 
    "CARD_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
    "EXP_DATE" DATE NOT NULL ENABLE, 
    "CVV" VARCHAR2(4) NOT NULL ENABLE, 
    "CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
     PRIMARY KEY ("ID") ENABLE
   ) ;CREATE TABLE  "USERS" 
   (    "USER_ID" NUMBER(*,0), 
    "FIRST_NAME" VARCHAR2(255), 
    "LAST_NAME" VARCHAR2(255), 
    "EMAIL" VARCHAR2(255), 
    "GENDER" VARCHAR2(10), 
    "PHONE_NUMBER" VARCHAR2(15), 
    "PASSWORD" VARCHAR2(255), 
    "ACCOUNT_STATUS" VARCHAR2(20), 
    "LICENSE_ID" VARCHAR2(20), 
    "USERNAME" VARCHAR2(255), 
     PRIMARY KEY ("USER_ID") ENABLE
   ) ; CREATE SEQUENCE   "USER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "PAYMENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "CAR_ID_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "CAR_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ; CREATE SEQUENCE   "BOOKING_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE ;CREATE OR REPLACE TRIGGER  "CAR_ID_TRIGGER" 
BEFORE INSERT ON CARS
FOR EACH ROW
 WHEN (NEW.CAR_ID IS NULL) BEGIN
  SELECT car_id_seq1.NEXTVAL INTO :NEW.CAR_ID FROM dual;
END;
/
ALTER TRIGGER  "CAR_ID_TRIGGER" ENABLE;CREATE OR REPLACE TRIGGER  "BOOKING_ID_TRIGGER" 
BEFORE INSERT ON BOOKINGS
FOR EACH ROW
BEGIN
    IF :NEW.BOOKING_ID IS NULL THEN
        SELECT booking_id_seq.NEXTVAL
        INTO :NEW.BOOKING_ID
        FROM dual;
    END IF;
END;
/
ALTER TRIGGER  "BOOKING_ID_TRIGGER" ENABLE;



INSERT INTO booking (BOOKING_ID, START_DATE, END_DATE, BOOKING_STATUS, CAR_ID, USER_ID, RENTAL_RATE)
VALUES (1, '2024-08-01', '2024-08-05', 'Confirmed', 201, 101, 45.00);

INSERT INTO booking (BOOKING_ID, START_DATE, END_DATE, BOOKING_STATUS, CAR_ID, USER_ID, RENTAL_RATE)
VALUES (2, '2024-08-10', '2024-08-15', 'Pending', 202, 102, 50.00);

INSERT INTO booking (BOOKING_ID, START_DATE, END_DATE, BOOKING_STATUS, CAR_ID, USER_ID, RENTAL_RATE)
VALUES (3, '2024-09-01', '2024-09-03', 'Completed', 203, 103, 70.00);

INSERT INTO booking (BOOKING_ID, START_DATE, END_DATE, BOOKING_STATUS, CAR_ID, USER_ID, RENTAL_RATE)
VALUES (4, '2024-09-10', '2024-09-12', 'Cancelled', 204, 104, 55.00);
INSERT INTO cars (CAR_NAME, VEHICLE_NO, AVAILABLE, RENTAL_RATE, SEAT_COUNT, FUEL_TYPE, CAR_TYPE, BAGS, CAR_IMAGE_URL)
VALUES ('Toyota Camry', 'XYZ1234', TRUE, 45.00, 5, 'Petrol', 'Sedan', 2, 'http://example.com/images/toyota_camry.jpg');

INSERT INTO cars (CAR_NAME, VEHICLE_NO, AVAILABLE, RENTAL_RATE, SEAT_COUNT, FUEL_TYPE, CAR_TYPE, BAGS, CAR_IMAGE_URL)
VALUES ('Honda Civic', 'ABC5678', FALSE, 50.00, 5, 'Diesel', 'Sedan', 2, 'http://example.com/images/honda_civic.jpg');

INSERT INTO cars (CAR_NAME, VEHICLE_NO, AVAILABLE, RENTAL_RATE, SEAT_COUNT, FUEL_TYPE, CAR_TYPE, BAGS, CAR_IMAGE_URL)
VALUES ('Ford Explorer', 'LMN9101', TRUE, 70.00, 7, 'Petrol', 'SUV', 4, 'http://example.com/images/ford_explorer.jpg');

INSERT INTO cars (CAR_NAME, VEHICLE_NO, AVAILABLE, RENTAL_RATE, SEAT_COUNT, FUEL_TYPE, CAR_TYPE, BAGS, CAR_IMAGE_URL)
VALUES ('Chevrolet Malibu', 'QRS2345', TRUE, 55.00, 5, 'Hybrid', 'Sedan', 3, 'http://example.com/images/chevrolet_malibu.jpg');
INSERT INTO payments (ID, USERNAME, CARNAME, CARDHOLDER_NAME, CARD_NUMBER, CARD_TYPE, EXP_DATE, CVV, CREATED_AT)
VALUES (1, 'john_doe', 'Toyota Camry', 'John Doe', '4111 1111 1111 1111', 'Visa', '2025-08-31', '123', '2024-07-31 12:00:00');

INSERT INTO payments (ID, USERNAME, CARNAME, CARDHOLDER_NAME, CARD_NUMBER, CARD_TYPE, EXP_DATE, CVV, CREATED_AT)
VALUES (2, 'jane_smith', 'Honda Civic', 'Jane Smith', '5500 0000 0000 0004', 'MasterCard', '2024-12-31', '456', '2024-07-31 13:30:00');

INSERT INTO payments (ID, USERNAME, CARNAME, CARDHOLDER_NAME, CARD_NUMBER, CARD_TYPE, EXP_DATE, CVV, CREATED_AT)
VALUES (3, 'alice_johnson', 'Ford Explorer', 'Alice Johnson', '3400 0000 0000 009', 'American Express', '2026-01-31', '7890', '2024-07-31 15:45:00');

INSERT INTO payments (ID, USERNAME, CARNAME, CARDHOLDER_NAME, CARD_NUMBER, CARD_TYPE, EXP_DATE, CVV, CREATED_AT)
VALUES (4, 'bob_brown', 'Chevrolet Malibu', 'Bob Brown', '6011 0000 0000 0004', 'Discover', '2025-11-30', '321', '2024-07-31 17:00:00');
INSERT INTO users (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, LICENSE_ID, USERNAME)
VALUES (1, 'John', 'Doe', 'john.doe@example.com', 'Male', '123-456-7890', 'password123', 'Active', 'LIC1001', 'johndoe');

INSERT INTO users (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, LICENSE_ID, USERNAME)
VALUES (2, 'Jane', 'Smith', 'jane.smith@example.com', 'Female', '098-765-4321', 'securepass456', 'Inactive', 'LIC1002', 'janesmith');

INSERT INTO users (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, LICENSE_ID, USERNAME)
VALUES (3, 'Alice', 'Johnson', 'alice.johnson@example.com', 'Female', '555-123-4567', 'alicepwd789', 'Active', 'LIC1003', 'alicejohnson');

INSERT INTO users (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, PHONE_NUMBER, PASSWORD, ACCOUNT_STATUS, LICENSE_ID, USERNAME)
VALUES (4, 'Bob', 'Brown', 'bob.brown@example.com', 'Male', '444-987-6543', 'bobbrown123', 'Active', 'LIC1004', 'bobbrown');
