/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.18
 * Generated at: 2024-07-18 06:58:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.Admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class bookingManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1720276535162L));
    _jspx_dependants.put("jar:file:/D:/HallBookingManagementSystem_JSP_project/HallBooking_SpringMVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hallbookingmanagement/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664433678000L));
    _jspx_dependants.put("jar:file:/D:/HallBookingManagementSystem_JSP_project/HallBooking_SpringMVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hallbookingmanagement/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/LogoFavIcon.jpg\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.17/jspdf.plugin.autotable.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/docx/7.1.1/docx.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js\"></script>\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"https://cdn.datatables.net/2.0.8/css/dataTables.bootstrap5.css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <title>Booking Management</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/AdminStyle.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/bookingmanagement.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("    	.subcontainer{\r\n");
      out.write("    		margin-left:220px !important;\r\n");
      out.write("    	}\r\n");
      out.write("    </style>\r\n");
      out.write("	 ");
 
    if (request.getSession().getAttribute("userName") == null) {
        response.sendRedirect("viewLogin");
    }
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--Logout modal-->\r\n");
      out.write("		<div class=\"modal\" id=\"logoutModal\" tabindex=\"-1\" aria-labelledby=\"logoutModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("			 <form action=\"logout\" method=\"get\">\r\n");
      out.write("			  <div class=\"modal-dialog\">\r\n");
      out.write("			    <div class=\"modal-content\">\r\n");
      out.write("			      <div class=\"modal-header\">\r\n");
      out.write("			        <h5 class=\"modal-title\" id=\"logoutModalLabel\">Confirm Logout</h5>\r\n");
      out.write("			        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("			      	</div>\r\n");
      out.write("			     	 <div class=\"modal-body\">\r\n");
      out.write("			        	<p>Are you sure you want to logout?</p>\r\n");
      out.write("			      </div>\r\n");
      out.write("			      <div class=\"modal-footer\">\r\n");
      out.write("			        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("			        <button type=\"submit\" class=\"btn btn-outline-danger\">Logout</button>\r\n");
      out.write("			      </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			  </div> \r\n");
      out.write("			  </form>\r\n");
      out.write("		</div>\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Logo.1.1.png\"  alt=\"\" id=\"company-logo\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"profile d-inline-block\">\r\n");
      out.write("    <a class=\"d-flex align-items-center\" href=\"#\" id=\"profile-menu\" role=\"button\" aria-expanded=\"false\" data-bs-toggle=\"tooltip\" title=\"Edit Profile\">\r\n");
      out.write("	    <div class=\"d-flex align-items-center\">\r\n");
      out.write("	        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"50\" height=\"50\" fill=\"currentColor\" class=\"bi bi-person-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	            <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0\"/>\r\n");
      out.write("	            <path fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1\"/>\r\n");
      out.write("	        </svg>\r\n");
      out.write("	        <div class=\"mt-3 ms-2 me-4\">\r\n");
      out.write("	            <h4 class=\"p-0 m-0\">Administrator</h4>\r\n");
      out.write("	            <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName.getUserName()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</a>\r\n");
      out.write("</div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"subcontainer\">\r\n");
      out.write("       <div class=\"innerContainer\" style=\"margin-top:70px !important\">\r\n");
      out.write("            <div class=\"sideNavBar\">\r\n");
      out.write("            <div class=\"vertical-nav\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-light main-left-nav\" id=\"sideNav\">\r\n");
      out.write("                    <ul class=\"nav flex-column\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/dashBoard\">Dashboard</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link booking-active\" id=\"booking-active\"  href=\"");
      out.print( request.getContextPath() );
      out.write("/showManagebooking\">Booking Management</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\"  href=\"");
      out.print( request.getContextPath() );
      out.write("/showHallManagement\">Hall Management</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/customerManagement\">Customer Management</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/paymentManagement\">Payment Management</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                   \r\n");
      out.write("                         <li class=\"nav-item\" style=\"margin-top:300px\">\r\n");
      out.write("                            <a class=\"nav-link\" href= '");
      out.print( request.getContextPath() );
      out.write("/index.jsp'>Sign Out</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 if (request.getAttribute("bookingStatusChanged") != null) {
      out.write("\r\n");
      out.write("		    <div class=\"alert alert-success mt-3\" role=\"alert\" id =\"statusAlert\">\r\n");
      out.write("		        <p>");
      out.print( request.getAttribute("bookingStatusChanged") );
      out.write("</p>\r\n");
      out.write("		    </div>\r\n");
      out.write("		");
}
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"bookingTable mt-4\" >\r\n");
      out.write("            <h1>Booking Details</h1>\r\n");
      out.write("                            <button id=\"export-pdf\" class=\"btn btn-outline-dark btn-sm mb-3 mt-3\">Export to PDF</button>\r\n");
      out.write("            <div class=\"table-responsive-lg\">\r\n");
      out.write("                <table class=\"table table-hover table-bordered\" id =\"bookingTable\" style=\"width:80%;\">\r\n");
      out.write("                    <thead class=\"thead-dark\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                        	<th style=\"display:none\"></th>\r\n");
      out.write("                        	<th>SNo</th>\r\n");
      out.write("                            <th>User Name</th>\r\n");
      out.write("                            <th>Requested Hall</th>\r\n");
      out.write("                            <th>Start Date</th>\r\n");
      out.write("                            <th>End Date</th>\r\n");
      out.write("                            <th>Status</th>\r\n");
      out.write("                            <th>Action</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                   <tbody>\r\n");
      out.write("					    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					    ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal\" id=\"conflict-modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("    <form action=\"change-booking\" method=\"get\">\r\n");
      out.write("		  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("		    <div class=\"modal-content\">\r\n");
      out.write("		      <div class=\"modal-header\">\r\n");
      out.write("		        <h5 class=\"modal-title\">Booking Conflict occur</h5>\r\n");
      out.write("		        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("		          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("		        </button>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"modal-body\">\r\n");
      out.write("		       <input  type=\"hidden\" name=\"currentBookId\" id=\"currentBookId\"/>\r\n");
      out.write("		       <input type=\"hidden\" name=\"changeBookId\" id=\"changeBookId\">\r\n");
      out.write("		      <p><strong><span id=\"conf-username\"></span> is already in Confirmed booking</strong></p>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"modal-footer\">\r\n");
      out.write("		        <button type=\"submit\" class=\"btn btn-outline-warning\" class=\"conflict-close\">Continue</button>\r\n");
      out.write("		        <button type=\"button\" class=\"btn btn-secondary\" id=\"conf-close\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("		      </div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("	  </form>\r\n");
      out.write("	</div>\r\n");
      out.write("    \r\n");
      out.write("    <form id=\"editStatusForm\" action=\"edit-status\" method=\"get\">\r\n");
      out.write("		    <input type=\"hidden\" name=\"status\" id=\"statusInput\">\r\n");
      out.write("		    <input type=\"hidden\" name=\"bookId\" id=\"bookIdInput\">\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"alert-container\" style=\"position: fixed; top: 20px; right: 20px; z-index: 9999;\"></div>\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("	<script src='https://code.jquery.com/jquery-3.7.0.js'></script>\r\n");
      out.write("	<!-- Data Table JS -->\r\n");
      out.write("	<script src='https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js'></script>\r\n");
      out.write("	<script src='https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js'></script>\r\n");
      out.write("	<script src='https://cdn.datatables.net/1.13.5/js/dataTables.bootstrap5.min.js'></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Include jQuery and Bootstrap JS -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        setTimeout(function() {\r\n");
      out.write("            $('#statusAlert').alert('close');\r\n");
      out.write("        }, 3000);\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        document.querySelectorAll('.edit-btn').forEach(button => {\r\n");
      out.write("            button.addEventListener('click', function() {\r\n");
      out.write("                let row = this.closest('tr');\r\n");
      out.write("                let status = row.querySelector('.status-text').innerText.trim();\r\n");
      out.write("                row.querySelector('.status-text').style.display = 'none';\r\n");
      out.write("                row.querySelector('.status-select').style.display = 'block';\r\n");
      out.write("                row.querySelector('.edit-btn').style.display = 'none';\r\n");
      out.write("                row.querySelector('.save-btn').style.display = 'inline-block';\r\n");
      out.write("                row.querySelector('.cancel-btn').style.display = 'inline-block';\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("        document.querySelectorAll('.cancel-btn').forEach(button => {\r\n");
      out.write("            button.addEventListener('click', function() {\r\n");
      out.write("                let row = this.closest('tr');\r\n");
      out.write("                let statusSelect = row.querySelector('.status-select');\r\n");
      out.write("                let statusText = row.querySelector('.status-text');\r\n");
      out.write("                statusSelect.value = statusText.textContent.trim();\r\n");
      out.write("                statusText.style.display = 'block';\r\n");
      out.write("                statusSelect.style.display = 'none';\r\n");
      out.write("                row.querySelector('.edit-btn').style.display = 'inline-block';\r\n");
      out.write("                row.querySelector('.save-btn').style.display = 'none';\r\n");
      out.write("                row.querySelector('.cancel-btn').style.display = 'none';\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        document.querySelectorAll('.save-btn').forEach(button => {\r\n");
      out.write("            button.addEventListener('click', function () {\r\n");
      out.write("                let row = this.closest('tr');\r\n");
      out.write("                let cid = row.querySelector('.bookId');\r\n");
      out.write("                let statusSelect = row.querySelector('.status-select');\r\n");
      out.write("                let statusText = row.querySelector('.status-text');\r\n");
      out.write("\r\n");
      out.write("                // Update the status text and toggle visibility\r\n");
      out.write("                statusText.textContent = statusSelect.value;\r\n");
      out.write("                statusText.style.display = 'block';\r\n");
      out.write("                statusSelect.style.display = 'none';\r\n");
      out.write("                row.querySelector('.edit-btn').style.display = 'inline-block';\r\n");
      out.write("                row.querySelector('.save-btn').style.visibility = 'hidden';\r\n");
      out.write("                row.querySelector('.cancel-btn').style.visibility = 'hidden';\r\n");
      out.write("\r\n");
      out.write("                // Set the form input values\r\n");
      out.write("                document.getElementById('statusInput').value = statusSelect.value;\r\n");
      out.write("                document.getElementById('bookIdInput').value = cid.textContent;\r\n");
      out.write("\r\n");
      out.write("                // Submit the form\r\n");
      out.write("                document.getElementById('editStatusForm').submit();\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        document.getElementById('export-pdf').addEventListener('click', function () {\r\n");
      out.write("            const { jsPDF } = window.jspdf;\r\n");
      out.write("            const doc = new jsPDF();\r\n");
      out.write("\r\n");
      out.write("            doc.autoTable({ html: '#bookingTable' });\r\n");
      out.write("\r\n");
      out.write("            doc.save('bookdetails.pdf');\r\n");
      out.write("        });\r\n");
      out.write("    \r\n");
      out.write(" /* \r\n");
      out.write(" document.getElementById('confirmLogoutButton').addEventListener('click', function() {\r\n");
      out.write("        // Add your logout logic here\r\n");
      out.write("        window.location.href = '");
      out.print( request.getContextPath() );
      out.write("/LogoutServlet'; // Replace 'logoutURL' with the actual URL to log out\r\n");
      out.write("      }); \r\n");
      out.write(" \r\n");
      out.write(" */\r\n");
      out.write("    \r\n");
      out.write(" document.getElementById(\"conf-close\").addEventListener(\"click\", function(){\r\n");
      out.write(" 	$('#conflict-modal').modal('hide');\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("      // Show the modal when the logout dropdown item is clicked\r\n");
      out.write("     	document.getElementById('logout').addEventListener('click', function(event) {\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("        var logoutModal = new bootstrap.Modal(document.getElementById('logoutModal'));\r\n");
      out.write("        logoutModal.show();\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    ");
 if (request.getSession().getAttribute("conflictBooking") != null && request.getSession().getAttribute("changeBooking") != null ) { 
      out.write("	\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("                var conflictModalElement = document.getElementById('conflict-modal');\r\n");
      out.write("                var conflictModal = new bootstrap.Modal(conflictModalElement);\r\n");
      out.write("          		document.getElementById(\"conf-username\").textContent = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conflictBooking.customer.userName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("          		document.getElementById(\"changeBookId\").value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${changeBooking}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("          		document.getElementById(\"currentBookId\").value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conflictBooking.bookingId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                conflictModal.show();\r\n");
      out.write("            });\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/view/Admin/bookingManagement.jsp(133,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("count");
      // /WEB-INF/view/Admin/bookingManagement.jsp(133,9) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/Admin/bookingManagement.jsp(133,9) '1'",_jsp_getExpressionFactory().createValueExpression("1",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/Admin/bookingManagement.jsp(134,9) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/Admin/bookingManagement.jsp(134,9) '${bookingList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${bookingList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/view/Admin/bookingManagement.jsp(134,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("booking");
      // /WEB-INF/view/Admin/bookingManagement.jsp(134,9) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					           \r\n");
            out.write("					            <tr>\r\n");
            out.write("					                	<td style=\"display:none\" class=\"bookId\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.bookingId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.customer.userName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.hall.hallName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.startDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.endDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					                    <td>\r\n");
            out.write("					                        <span class=\"status-text ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.bookStatus.toLowerCase()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"text-align: center; justify-content: center;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.bookStatus}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("					                        <select class=\"form-select status-select\" name=\"newStatus\" style=\"display: none;\">\r\n");
            out.write("					                            <option value=\"PENDING\" ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(">PENDING</option>\r\n");
            out.write("					                            <option value=\"APPROVED\" ");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(">APPROVED</option>\r\n");
            out.write("					                            <option value=\"CONFIRMED\" ");
            if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(">CONFIRMED</option>\r\n");
            out.write("					                            <option value=\"CANCEL\" ");
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(">CANCEL</option>\r\n");
            out.write("					                        </select>\r\n");
            out.write("					                    </td>\r\n");
            out.write("					                    <td>\r\n");
            out.write("					                        <button type=\"button\" class=\"btn btn-outline-primary btn-sm edit-btn\">\r\n");
            out.write("					                            <i class=\"fas fa-edit\"></i>\r\n");
            out.write("					                        </button>\r\n");
            out.write("					                        <button type=\"submit\" class=\"btn btn-outline-success btn-sm save-btn\" style=\"display: none;\">\r\n");
            out.write("					                            <i class=\"fas fa-save\"></i>\r\n");
            out.write("					                        </button>\r\n");
            out.write("					                        <button type=\"button\" class=\"btn btn-outline-danger btn-sm cancel-btn\" style=\"display: none;\">\r\n");
            out.write("					                            <i class=\"fas fa-times-circle\"></i>\r\n");
            out.write("					                        </button>\r\n");
            out.write("					                        <input type=\"hidden\" name=\"userId\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.bookingId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("					                    </td>\r\n");
            out.write("					            </tr>\r\n");
            out.write("					             ");
            if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("					    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/Admin/bookingManagement.jsp(146,57) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.bookStatus == 'PENDING'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/Admin/bookingManagement.jsp(147,58) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.bookStatus == 'APPROVED'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/Admin/bookingManagement.jsp(148,59) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.bookStatus == 'CONFIRMED'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/Admin/bookingManagement.jsp(149,56) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.bookStatus == 'CANCEL'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/Admin/bookingManagement.jsp(165,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("count");
      // /WEB-INF/view/Admin/bookingManagement.jsp(165,18) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/Admin/bookingManagement.jsp(165,18) '${count + 1}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${count + 1}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/view/Admin/bookingManagement.jsp(167,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty bookingList}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					        <tr>\r\n");
          out.write("					            <td colspan=\"6\" class=\"text-center\">No bookings available.</td>\r\n");
          out.write("					        </tr>\r\n");
          out.write("					    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
