/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.18
 * Generated at: 2024-07-18 06:58:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.Admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("    <title>Dash Board</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/AdminDashBoard.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/AdminStyle.css\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/LogoFavIcon.jpg\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js\"></script>\r\n");
      out.write("    <script src=\"https://d3js.org/d3.v4.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/billboard.js/dist/billboard.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/billboard.js/dist/billboard.min.css\" />\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<style>\r\n");
      out.write("	.container-fluid{\r\n");
      out.write("		margin-left:100px !important;\r\n");
      out.write("	}\r\n");
      out.write("	</style>\r\n");
      out.write("	 ");
 
    if (request.getSession().getAttribute("userName") == null) {
        response.sendRedirect("viewLogin");
    }
	
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Logo.1.1.png\" alt=\"Logo\"  id=\"company-logo\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"profile d-inline-block\">\r\n");
      out.write("            <a class=\"d-flex align-items-center\" href=\"");
      out.print( request.getContextPath() );
      out.write("/AdminEditProfile\" >\r\n");
      out.write("                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"50\" height=\"50\" fill=\"currentColor\" class=\"bi bi-person-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                        <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0\"/>\r\n");
      out.write("                        <path fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1\"/>\r\n");
      out.write("                      </svg>\r\n");
      out.write("                    <div class=\"mt-3 ms-2 me-4\">\r\n");
      out.write("                        <h4 class=\"p-0 m-0\">Administrator</h4>\r\n");
      out.write("                        <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName.getUserName()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!--Logout modal-->\r\n");
      out.write("		<div class=\"modal\" id=\"logoutModal\" tabindex=\"-1\" aria-labelledby=\"logoutModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("			 <form action=\"logout\" method=\"get\">\r\n");
      out.write("			  <div class=\"modal-dialog\">\r\n");
      out.write("			    <div class=\"modal-content\">\r\n");
      out.write("			      <div class=\"modal-header\">\r\n");
      out.write("			        <h5 class=\"modal-title\" id=\"logoutModalLabel\">Confirm Logout</h5>\r\n");
      out.write("			        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("			      	</div>\r\n");
      out.write("			     	 <div class=\"modal-body\">\r\n");
      out.write("			        	<p>Are you sure you want to logout?</p>\r\n");
      out.write("			      </div>\r\n");
      out.write("			      <div class=\"modal-footer\">\r\n");
      out.write("			        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("			        <button type=\"submit\" class=\"btn btn-outline-danger\">Logout</button>\r\n");
      out.write("			      </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			  </div> \r\n");
      out.write("			  </form>\r\n");
      out.write("		</div>\r\n");
      out.write("    <div class=\"subContainer\" >\r\n");
      out.write("        <div class=\"innerContainer\" style=\"margin-top:70px !important\">\r\n");
      out.write("            <div class=\"sideNavBar\">\r\n");
      out.write("            <div class=\"vertical-nav\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-light main-left-nav\" id=\"sideNav\">\r\n");
      out.write("                    <ul class=\"nav flex-column\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/dashBoard\">Dashboard</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link booking-active\" id=\"booking-active\"  href=\"");
      out.print( request.getContextPath() );
      out.write("/showManagebooking\">Booking Management</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\"  href=\"");
      out.print( request.getContextPath() );
      out.write("/showHallManagement\">Hall Management</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/customerManagement\">Customer Management</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/paymentManagement\">Payment Management</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        \r\n");
      out.write("                        <li class=\"nav-item\" style=\"margin-top:300px\">\r\n");
      out.write("                            <a class=\"dropdown-item ms-2\" href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\" id=\"logout\">Sign Out</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container-fluid\" style=\"margin-top:70px !important; margin-left:200px !important;\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-3 col-xl-3\">\r\n");
      out.write("                    <div class=\"bookingCard card1\">\r\n");
      out.write("                        <h3 class=\"bookingtitle card1-title\">Booking Cycle</h3>\r\n");
      out.write("                        <div class=\"innerCard\" id=\"checkin-checkout\">\r\n");
      out.write("                            <div class=\"thisMonth\"><p>Previous Month</p></div>\r\n");
      out.write("                            <div class=\"thisMonth\"><p>This Month</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"number\" style=\"display: flex; justify-content: space-around;\">\r\n");
      out.write("                            <div id=\"checkin\" class=\"Previous Month\"  ><p style=\"font-size: 30px;\"><strong>\r\n");
      out.write("                            ");
 if (request.getAttribute("previous") != null) { 
      out.write("\r\n");
      out.write("                            ");
      out.print( request.getAttribute("previous") );
      out.write("\r\n");
      out.write("                        	");
 } 
      out.write(" </strong></p></p></div>\r\n");
      out.write("                            <div id=\"checkout\" class=\"This Month\"><p style=\"font-size: 30px;\"><strong>\r\n");
      out.write("                            ");
 if (request.getAttribute("thisMonth") != null) { 
      out.write("\r\n");
      out.write("                            ");
      out.print( request.getAttribute("thisMonth") );
      out.write("\r\n");
      out.write("                        	");
 } 
      out.write("</strong> </p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 col-xl-3\">\r\n");
      out.write("                    <div class=\"bookingCard\">\r\n");
      out.write("                        <h3 class=\"bookingtitle\">Total Booking</h3>\r\n");
      out.write("                        <div class=\"innerCard\">\r\n");
      out.write("                            <div class=\"thisMonth\"><p>This Month</p></div>\r\n");
      out.write("                            <div class=\"thisMonth\"><p>This Year</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"number\" style=\"display: flex; justify-content: space-around;\">\r\n");
      out.write("                            <div class=\"thisMonthPercent\"><p>23% &#8593;</p></div>\r\n");
      out.write("                            <div class=\"thisMonthPercent\"><p>20% &#8593;</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 col-xl-3\">\r\n");
      out.write("                    <div class=\"bookingCard\">\r\n");
      out.write("                        <h3 class=\"bookingtitle\">Hall Status</h3>\r\n");
      out.write("                        <div class=\"innerCard\">\r\n");
      out.write("                            <div class=\"thisMonth\"><p>Available</p></div>\r\n");
      out.write("                            <div class=\"thisMonth\"><p>Booked</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"percentage\" style=\"display: flex; justify-content: space-around;\">\r\n");
      out.write("                            <div class=\"thisMonthPercent\"><p>5</p></div>\r\n");
      out.write("                            <div class=\"thisMonthPercent\"><p>7</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 col-xl-2\">\r\n");
      out.write("                    <div class=\"PendingBookings\">\r\n");
      out.write("                        <h3 class=\"pending\">Pending Bookings</h3>\r\n");
      out.write("                        <div style=\"display: flex;\">\r\n");
      out.write("                            <div class=\"pendingimage\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/pending_actions_24dp_FILL0_wght400_GRAD0_opsz24.svg\" alt=\"pending icon\"></div>\r\n");
      out.write("                            <p class=\"pendingCount\">\r\n");
      out.write("                            ");
 if (request.getAttribute("pending") != null) { 
      out.write("\r\n");
      out.write("                            ");
      out.print( request.getAttribute("pending") );
      out.write("\r\n");
      out.write("                        	");
 } 
      out.write("   \r\n");
      out.write("                     		</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row ms-3 gap-5 mt-5\">\r\n");
      out.write("                <div class=\"col-5 p-0 mt-4 me-5\" style=\" box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px; max-width: 300px;\" >\r\n");
      out.write("                    <h5 style=\"text-align: center;\">This Month Event Bookings</h5>\r\n");
      out.write("                    <div class=\"row-graph p-0 m-0\"> \r\n");
      out.write("                        <canvas id=\"myChart\" ></canvas>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-5  p-0 mt-4 ms-5\" style=\" box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px; max-width: 300px;\">\r\n");
      out.write("                    <h5 class=\"m-2\" style=\"align-items: center;text-align: center;\">Seating Arrangements</h5>\r\n");
      out.write("                    <div id=\"donut-chart\" width=\"100px\"></div>\r\n");
      out.write("                    <script>\r\n");
      out.write("                        let chart = bb.generate({\r\n");
      out.write("                            data: {\r\n");
      out.write("                                columns: [\r\n");
      out.write("                                    [\"Theater\", 2],\r\n");
      out.write("                                    [\"BoardRoom\", 4],\r\n");
      out.write("                                    [\"U-shaped\", 3],\r\n");
      out.write("                                ],\r\n");
      out.write("                                type: \"donut\",\r\n");
      out.write("                                onclick: function (d, i) {\r\n");
      out.write("                                    console.log(\"onclick\", d, i);\r\n");
      out.write("                                },\r\n");
      out.write("                                onover: function (d, i) {\r\n");
      out.write("                                    console.log(\"onover\", d, i);\r\n");
      out.write("                                },\r\n");
      out.write("                                onout: function (d, i) {\r\n");
      out.write("                                    console.log(\"onout\", d, i);\r\n");
      out.write("                                },\r\n");
      out.write("                            },\r\n");
      out.write("                            donut: {\r\n");
      out.write("                                title: \"70\",\r\n");
      out.write("                            },\r\n");
      out.write("                            bindto: \"#donut-chart\",\r\n");
      out.write("                        });\r\n");
      out.write("                    </script>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        const data = [100, 150, 80]; // Example data for the bars\r\n");
      out.write("\r\n");
      out.write("        const barGraph = document.getElementById('barGraph');\r\n");
      out.write("\r\n");
      out.write("        data.forEach((value, index) => {\r\n");
      out.write("            const bar = document.createElement('div');\r\n");
      out.write("            bar.classList.add('bar');\r\n");
      out.write("            bar.style.height = value + 'px'; // Set the height of the bar\r\n");
      out.write("            bar.style.backgroundColor = getRandomColor(); // Random color for each bar\r\n");
      out.write("\r\n");
      out.write("            const label = document.createElement('span');\r\n");
      out.write("            label.classList.add('bar-label');\r\n");
      out.write("            label.textContent = 'Bar ' + (index + 1);\r\n");
      out.write("\r\n");
      out.write("            barGraph.appendChild(bar);\r\n");
      out.write("            barGraph.appendChild(label);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function getRandomColor() {\r\n");
      out.write("            const letters = '0123456789ABCDEF';\r\n");
      out.write("            let color = '#';\r\n");
      out.write("            for (let i = 0; i < 6; i++) {\r\n");
      out.write("                color += letters[Math.floor(Math.random() * 16)];\r\n");
      out.write("            }\r\n");
      out.write("            return color;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', (event) => {\r\n");
      out.write("        var ctx = document.getElementById('barChart').getContext('2d');\r\n");
      out.write("        var barChart = new Chart(ctx, {\r\n");
      out.write("            type: 'bar',\r\n");
      out.write("            data: {\r\n");
      out.write("                labels: ['Hall 1', 'Hall 2', 'Hall 3', 'Hall 4', 'Hall 5'],\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    label: 'Bookings',\r\n");
      out.write("                    data: [12, 19, 3, 5, 2],\r\n");
      out.write("                    backgroundColor: [\r\n");
      out.write("                        'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("                        'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("                        'rgba(255, 206, 86, 0.2)',\r\n");
      out.write("                        'rgba(75, 192, 192, 0.2)',\r\n");
      out.write("                        'rgba(153, 102, 255, 0.2)'\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderColor: [\r\n");
      out.write("                        'rgba(255, 99, 132, 1)',\r\n");
      out.write("                        'rgba(54, 162, 235, 1)',\r\n");
      out.write("                        'rgba(255, 206, 86, 1)',\r\n");
      out.write("                        'rgba(75, 192, 192, 1)',\r\n");
      out.write("                        'rgba(153, 102, 255, 1)'\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderWidth: 3\r\n");
      out.write("                    \r\n");
      out.write("                }]\r\n");
      out.write("            },\r\n");
      out.write("            options: {\r\n");
      out.write("                scales: {\r\n");
      out.write("                    y: {\r\n");
      out.write("                        beginAtZero: true\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                responsive: true,\r\n");
      out.write("                plugins: {\r\n");
      out.write("                    legend: {\r\n");
      out.write("                        position: 'top',\r\n");
      out.write("                    },\r\n");
      out.write("                    title: {\r\n");
      out.write("                        display: true,\r\n");
      out.write("                        text: 'Number of Bookings per Hall'\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("          </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                    <script>\r\n");
      out.write("                            var ctxBar = document.getElementById('issuesBarChart').getContext('2d');\r\n");
      out.write("            var ctxPie = document.getElementById('issuesPieChart').getContext('2d');\r\n");
      out.write("            var ctxCategory = document.getElementById('issueCategoryChart').getContext('2d');\r\n");
      out.write("\r\n");
      out.write("            var barChart = new Chart(ctxBar, {\r\n");
      out.write("                type: 'bar',\r\n");
      out.write("                data: {\r\n");
      out.write("                    labels: ['Total Issues', 'Issue Raised', 'Issue Assigned', 'In Progress', 'Completed Issues'],\r\n");
      out.write("                    datasets: [{\r\n");
      out.write("                        label: 'Number of Issues',\r\n");
      out.write("                        data: [300, 10, 25, 50, 75],\r\n");
      out.write("                        backgroundColor: [\r\n");
      out.write("                            'rgba(75, 192, 192, 0.2)',\r\n");
      out.write("                            'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("                            'rgba(255, 206, 86, 0.2)',\r\n");
      out.write("                            'rgba(153, 102, 255, 0.2)',\r\n");
      out.write("                            'rgba(255, 159, 64, 0.2)'\r\n");
      out.write("                        ],\r\n");
      out.write("                        borderColor: [\r\n");
      out.write("                            'rgba(75, 192, 192, 1)',\r\n");
      out.write("                            'rgba(54, 162, 235, 1)',\r\n");
      out.write("                            'rgba(255, 206, 86, 1)',\r\n");
      out.write("                            'rgba(153, 102, 255, 1)',\r\n");
      out.write("                            'rgba(255, 159, 64, 1)'\r\n");
      out.write("                        ],\r\n");
      out.write("                        borderWidth: 1\r\n");
      out.write("                    }]\r\n");
      out.write("                },\r\n");
      out.write("                options: {\r\n");
      out.write("                    scales: {\r\n");
      out.write("                        yAxes: [{\r\n");
      out.write("                            ticks: {\r\n");
      out.write("                                beginAtZero: true\r\n");
      out.write("                            }\r\n");
      out.write("                        }]\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("         </script>\r\n");
      out.write("                    \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>            \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("    <script>\r\n");
      out.write("        const xValues = [\"Wedding\", \"Baby Shower\", \"Bachelor Party\", \"Corporate Party\", \"Expo\"];\r\n");
      out.write("        const yValues = [34, 32, 14, 25, 25];\r\n");
      out.write("        const barColors = [\r\n");
      out.write("            \"#b91d47\",\r\n");
      out.write("            \"#00aba9\",\r\n");
      out.write("            \"#2b5797\",\r\n");
      out.write("            \"#e8c3b9\",\r\n");
      out.write("            \"#1e7145\"\r\n");
      out.write("            ];\r\n");
      out.write("\r\n");
      out.write("            new Chart(\"myChart\", {\r\n");
      out.write("                type: \"pie\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    labels: xValues,\r\n");
      out.write("                    datasets: [{\r\n");
      out.write("                        backgroundColor: barColors,\r\n");
      out.write("                        data: yValues\r\n");
      out.write("                    }]\r\n");
      out.write("                },\r\n");
      out.write("                options: {\r\n");
      out.write("                    \r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            xValues = [50,60,70,80,90,100,110,120,130,140,150];\r\n");
      out.write("            yValues = [7,8,8,9,9,9,10,11,14,14,15];\r\n");
      out.write("\r\n");
      out.write("            new Chart(\"myChart\", {\r\n");
      out.write("            type: \"line\",\r\n");
      out.write("            data: {\r\n");
      out.write("                labels: xValues,\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                fill: false,\r\n");
      out.write("                lineTension: 0,\r\n");
      out.write("                backgroundColor: \"rgba(0,0,255,1.0)\",\r\n");
      out.write("                borderColor: \"rgba(0,0,255,0.1)\",\r\n");
      out.write("                data: yValues\r\n");
      out.write("                }]\r\n");
      out.write("            },\r\n");
      out.write("            options: {\r\n");
      out.write("                legend: {display: false},\r\n");
      out.write("                scales: {\r\n");
      out.write("                yAxes: [{ticks: {min: 6, max:16}}],\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            </script>\r\n");
      out.write("            \r\n");
      out.write("            <script type=\"text/javascript\">\r\n");
      out.write("            \r\n");
      out.write("            document.getElementById('logout').addEventListener('click', function(event) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                var logoutModal = new bootstrap.Modal(document.getElementById('logoutModal'));\r\n");
      out.write("                logoutModal.show();\r\n");
      out.write("              });</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
