CREATE TABLE  "ADMIN"
   (    "ADMIN_ID" NUMBER,
    "FIRSTNAME" VARCHAR2(20),
    "LASTNAME" VARCHAR2(20),
    "EMAIL" VARCHAR2(30),
    "USERNAME" VARCHAR2(30),
    "PASSWORD" VARCHAR2(30),
    "PHONENUMBER" NUMBER,
     PRIMARY KEY ("ADMIN_ID") ENABLE,
     UNIQUE ("EMAIL") ENABLE
   ) ;

CREATE TABLE  "CUSTOMER"
   (    "CUSTOMER_ID" NUMBER,
    "FIRSTNAME" VARCHAR2(30),
    "LASTNAME" VARCHAR2(30),
    "GENDER" VARCHAR2(20),
    "EMAIL" VARCHAR2(20),
    "USERNAME" VARCHAR2(20),
    "PASSWORD" VARCHAR2(20),
    "PHONENUMBER" NUMBER,
    "AVAILABLE" VARCHAR2(10),
     PRIMARY KEY ("CUSTOMER_ID") ENABLE,
     UNIQUE ("EMAIL") ENABLE
   ) ;

CREATE TABLE  "BUSOPERATOR"
   (    "OPER_ID" NUMBER,
    "BNAME" VARCHAR2(30),
    "FIRSTNAME" VARCHAR2(30),
    "LASTNAME" VARCHAR2(30),
    "EMAIL" VARCHAR2(30),
    "USERNAME" VARCHAR2(20),
    "PASSWORD" VARCHAR2(20),
    "PHONE_NUMBER" VARCHAR2(10),
     PRIMARY KEY ("OPER_ID") ENABLE,
     UNIQUE ("EMAIL") ENABLE
   ) ;

CREATE TABLE  "BUS"
   (    "BUS_ID" NUMBER NOT NULL ENABLE,
    "BUSNAME" VARCHAR2(30),
    "BUSTYPE" VARCHAR2(10),
    "BUSCAPACITY" NUMBER,
    "FARE" NUMBER,
    "ROUTE_ID" NUMBER,
    "OPER_ID" NUMBER,
    "DAYOFROUTE" DATE,
    "ARRIVALTIME" TIMESTAMP (6),
    "DEPARTURETIME" TIMESTAMP (6),
    "BUS_AVAILABILITY" VARCHAR2(10),
     PRIMARY KEY ("BUS_ID") ENABLE
   ) ;

CREATE TABLE  "BOOKINGS"
   (    "BOOKID" NUMBER,
    "DEPARTURE" VARCHAR2(30),
    "ARRIVAL" VARCHAR2(30),
    "SELECTEDSEATS" NUMBER,
    "TOTALPRICE" NUMBER,
    "ROUTEID" NUMBER,
    "BUSID" NUMBER,
    "CUSTOMER_ID" NUMBER,
    "BOOKINGSTATUS" VARCHAR2(30),
     CONSTRAINT "BOOKINGS_ID" PRIMARY KEY ("BOOKID") ENABLE
   ) ;


CREATE TABLE  "ROUTE" 
   (    "ROUTE_ID" NUMBER NOT NULL ENABLE, 
    "STARTLOCATION" VARCHAR2(30), 
    "ENDLOCATION" VARCHAR2(30), 
    "DISTANCE" NUMBER, 
    "ESTIMATEDDURATION" NUMBER, 
    "ROUTE_AVAILABILITY" VARCHAR2(1), 
     PRIMARY KEY ("ROUTE_ID") ENABLE
   ) ;


CREATE TABLE  "PAYMENTCUSTOMER" 
   (    "PAY_ID" NUMBER, 
    "ACCOUNTNUMBER" VARCHAR2(20), 
    "PAYMENTMETHOD" VARCHAR2(20), 
    "TOTALAMOUNT" NUMBER, 
    "BOOKING_ID" NUMBER, 
    "PAYMENTSTATUS" VARCHAR2(20), 
     CONSTRAINT "PAYMENT" PRIMARY KEY ("PAY_ID") ENABLE
   ) ;

ALTER TABLE  "PAYMENTCUSTOMER" ADD CONSTRAINT "BOOKING_ID" FOREIGN KEY ("BOOKING_ID")
      REFERENCES  "BOOKINGS" ("BOOKID") ENABLE;
ALTER TABLE  "BOOKINGS" ADD CONSTRAINT "BUS" FOREIGN KEY ("BUSID")
      REFERENCES  "BUS" ("BUS_ID") ENABLE;
ALTER TABLE  "BOOKINGS" ADD CONSTRAINT "CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
      REFERENCES  "CUSTOMER" ("CUSTOMER_ID") ENABLE;
ALTER TABLE  "PAYMENT" ADD CONSTRAINT "PAYMENT_FK" FOREIGN KEY ("BOOKING_ID")
      REFERENCES  "BOOK" ("BOOKINGID") ENABLE;
ALTER TABLE  "BOOKINGS" ADD CONSTRAINT "ROUTE" FOREIGN KEY ("ROUTEID")
      REFERENCES  "ROUTE" ("ROUTE_ID") ENABLE;
ALTER TABLE  "BUS" ADD FOREIGN KEY ("OPER_ID")
      REFERENCES  "BUSOPERATOR" ("OPER_ID") ENABLE;
ALTER TABLE  "BUS" ADD FOREIGN KEY ("ROUTE_ID")
      REFERENCES  "ROUTE" ("ROUTE_ID") ENABLE;
CREATE UNIQUE INDEX  "BOOKINGS_ID" ON  "BOOKINGS" ("BOOKID");
CREATE UNIQUE INDEX  "PAYMENT" ON  "PAYMENTCUSTOMER" ("PAY_ID") 
  ; 
CREATE SEQUENCE   "ROUTE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 138 NOCACHE  NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "PAYMENTCUSTOMER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 35 NOCACHE  NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "CUSTOMER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 NOCACHE  NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "BOOKID_SEQS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 97 NOCACHE  NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "ADMIN_ID_SEQU"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 12 NOCACHE  NOORDER  NOCYCLE ;
CREATE OR REPLACE TRIGGER  "PAYMENTCUSTOMER_SEQ_TRIGGER" 
BEFORE INSERT ON PAYMENTCUSTOMER
FOR EACH ROW
BEGIN
  :NEW.PAY_ID := PAYMENTCUSTOMER_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER  "PAYMENTCUSTOMER_SEQ_TRIGGER" ENABLE;CREATE OR REPLACE TRIGGER  "CUSTOMER_ID_TRIGGER" 
BEFORE INSERT ON Customer
FOR EACH ROW
BEGIN
    IF :new.customer_id IS NULL THEN
        SELECT customer_seq.NEXTVAL
        INTO :new.customer_id
        FROM dual;
    END IF;
END;
/
ALTER TRIGGER  "CUSTOMER_ID_TRIGGER" ENABLE;CREATE OR REPLACE TRIGGER  "BOOKING_SEQ_TRIGGER" 
BEFORE INSERT ON BOOKINGS
FOR EACH ROW
BEGIN
  SELECT BOOKID_SEQS.NEXTVAL
  INTO :NEW.BOOKID
  FROM DUAL;
END;
/
ALTER TRIGGER  "BOOKING_SEQ_TRIGGER" ENABLE;CREATE OR REPLACE TRIGGER  "BEFORE_INSERT_ROUTE_ID" 
BEFORE INSERT ON route
FOR EACH ROW
BEGIN
    IF :NEW.ROUTE_ID IS NULL THEN
        SELECT route_id_seq.NEXTVAL INTO :NEW.ROUTE_ID FROM dual;
    END IF;
END;
/
ALTER TRIGGER  "BEFORE_INSERT_ROUTE_ID" ENABLE;CREATE OR REPLACE TRIGGER  "BEFORE_INSERT_ADMIN_ID_SEQU" 
BEFORE INSERT ON admin
FOR EACH ROW
BEGIN
    IF :NEW.admin_id IS NULL THEN
        SELECT Admin_id_sequ.NEXTVAL INTO :NEW.admin_id FROM dual;
    END IF;
END;
/
ALTER TRIGGER  "BEFORE_INSERT_ADMIN_ID_SEQU" ENABLE;

CREATE OR REPLACE TRIGGER  "BEFORE_INSERT_ROUTE_ID"
BEFORE INSERT ON route
FOR EACH ROW
BEGIN
    IF :NEW.ROUTE_ID IS NULL THEN
        SELECT route_id_seq.NEXTVAL INTO :NEW.ROUTE_ID FROM dual;
    END IF;
END;
/
ALTER TRIGGER  "BEFORE_INSERT_ROUTE_ID" ENABLE;
CREATE TABLE  "PASSENGER"
   (    "NAME" VARCHAR2(50),
    "AGE" NUMBER,
    "GENDER" VARCHAR2(10)
   ) ;


INSERT INTO Admin (ADMIN_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD, PHONENUMBER) VALUES 
(Admin_id_sequ.NEXTVAL, 'Dharani', 'Dharan', 'dharani@gmail.com', 'dharani_123', 'Passd@22', '9834453456');
INSERT INTO Admin (ADMIN_ID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD, PHONENUMBER) VALUES 
(Admin_id_sequ.NEXTVAL, 'Dharun', 'S', 'Dharun@gmail.com', 'Dharun_22', 'dharUn123', '9567390876'); 


INSERT INTO Customer (CUSTOMER_ID, FIRSTNAME, LASTNAME, GENDER, EMAIL, USERNAME, PASSWORD, PHONENUMBER, AVAILABLE) VALUES 
(CUSTOMER_SEQ, 'Ganesh', 'S', 'male', 'ganesh@gmail.com', 'ganesh234', 'gaNe@23', '9178761823', 'ACTIVE');
INSERT INTO Customer (CUSTOMER_ID, FIRSTNAME, LASTNAME, GENDER, EMAIL, USERNAME, PASSWORD, PHONENUMBER, AVAILABLE) VALUES 
CUSTOMER_SEQ, 'Tharun', 'Tim', 'male', 'Tharun@gmail.com', 'thar345', 'th@123412', '934543210', 'ACTIVE');
INSERT INTO Customer (CUSTOMER_ID, FIRSTNAME, LASTNAME, GENDER, EMAIL, USERNAME, PASSWORD, PHONENUMBER, AVAILABLE) VALUES 
(CUSTOMER_SEQ, 'Martin', 'M', 'male', 'Martin@gmail.com', 'Martin', 'ma@7890', '7632129876', 'ACTIVE');


INSERT INTO Bus (BUS_ID, BUSNAME, BUSTYPE, BUSCAPACITY, FARE, ROUTE_ID, OPER_ID, DAYOFROUTE, ARRIVALTIME, DEPARTURETIME, BUS_AVAILABILITY) VALUES 
(1, 'kMS Travel', 'AC', 44, 600, 98, 1, TO_DATE('08/25/2024', 'MM/DD/YYYY'), TO_TIMESTAMP('25-AUG-24 08.30.00.000000 AM', 'DD-MON-YY HH.MI.SS.FF6 AM'), TO_TIMESTAMP('25-AUG-24 12.30.00.000000 PM', 'DD-MON-YY HH.MI.SS.FF6 PM'), 'Y');
INSERT INTO Bus (BUS_ID, BUSNAME, BUSTYPE, BUSCAPACITY, FARE, ROUTE_ID, OPER_ID, DAYOFROUTE, ARRIVALTIME, DEPARTURETIME, BUS_AVAILABILITY) VALUES 
(2, 'jihan luxary bus', 'Non AC', 44, 900, 1, 2, TO_DATE('08/30/2024', 'MM/DD/YYYY'), TO_TIMESTAMP('30-AUG-24 08.30.00.000000 AM', 'DD-MON-YY HH.MI.SS.FF6 AM'), TO_TIMESTAMP('30-AUG-24 04.30.00.000000 PM', 'DD-MON-YY HH.MI.SS.FF6 PM'), 'Y');
INSERT INTO Bus (BUS_ID, BUSNAME, BUSTYPE, BUSCAPACITY, FARE, ROUTE_ID, OPER_ID, DAYOFROUTE, ARRIVALTIME, DEPARTURETIME, BUS_AVAILABILITY) VALUES 
(4, 'No 1 Air travel', 'AC', 44, 500, 1, 1, TO_DATE('08/30/2024', 'MM/DD/YYYY'), TO_TIMESTAMP('30-AUG-24 10.30.00.000000 AM', 'DD-MON-YY HH.MI.SS.FF6 AM'), TO_TIMESTAMP('30-AUG-24 06.30.00.000000 PM', 'DD-MON-YY HH.MI.SS.FF6 PM'), 'Y');
INSERT INTO Bus (BUS_ID, BUSNAME, BUSTYPE, BUSCAPACITY, FARE, ROUTE_ID, OPER_ID, DAYOFROUTE, ARRIVALTIME, DEPARTURETIME, BUS_AVAILABILITY) VALUES 
(8, 'AST Travel', 'AC', 44, 800, 4, 2, TO_DATE('08/24/2024', 'MM/DD/YYYY'), TO_TIMESTAMP('08-AUG-24 11.00.00.000000 AM', 'DD-MON-YY HH.MI.SS.FF6 AM'), TO_TIMESTAMP('08-AUG-24 03.00.00.000000 PM', 'DD-MON-YY HH.MI.SS.FF6 PM'), 'Y');
INSERT INTO Bus (BUS_ID, BUSNAME, BUSTYPE, BUSCAPACITY, FARE, ROUTE_ID, OPER_ID, DAYOFROUTE, ARRIVALTIME, DEPARTURETIME, BUS_AVAILABILITY) VALUES 
(15, 'Sri Ganesh Travels', 'AC', 44, 1200, 34, 1, TO_DATE('08/04/2024', 'MM/DD/YYYY'), TO_TIMESTAMP('04-AUG-24 09.30.00.000000 AM', 'DD-MON-YY HH.MI.SS.FF6 AM'), TO_TIMESTAMP('04-AUG-24 05.30.00.000000 PM', 'DD-MON-YY HH.MI.SS.FF6 PM'), 'Y');


INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(ROUTE_ID_SEQ, 'Chennai', 'Coimbatore', 510, 2, 'Y');
INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(ROUTE_ID_SEQ, 'Madurai', 'Tiruchirappalli', 130, 2, 'Y');
INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(ROUTE_ID_SEQ, 'Tirunelveli', 'Kanyakumari', 90, 4, 'Y');
INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(ROUTE_ID_SEQ, 'Salem', 'Erode', 120, 4, 'Y');
INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(ROUTE_ID_SEQ, 'Vellore', 'Chennai', 140, 2, 'Y');
INSERT INTO Route (ROUTE_ID, STARTLOCATION, ENDLOCATION, DISTANCE, ESTIMATEDDURATION, ROUTE_AVAILABILITY) VALUES 
(ROUTE_ID_SEQ, 'Salem', 'Chennai', 345, 8,'Y');


INSERT INTO BOOKINGS (BOOKID, DEPARTURE, ARRIVAL, SELECTEDSEATS, TOTALPRICE, ROUTEID, BUSID, CUSTOMER_ID, BOOKINGSTATUS) VALUES 
(BOOKID_SEQ.NEXTVAL, 'avrRoundana', 'avinashi', '1', 500, 98, 5, 5, 'Bookedandpaid');
INSERT INTO BOOKINGS (BOOKID, DEPARTURE, ARRIVAL, SELECTEDSEATS, TOTALPRICE, ROUTEID, BUSID, CUSTOMER_ID, BOOKINGSTATUS) VALUES 
(BOOKID_SEQ.NEXTVAL, 'avrRoundana', 'avinashi', '1', 500, 98, 5, 5, 'Bookedandpaid');


INSERT INTO PaymentCustomer (PAY_ID, ACCOUNTNUMBER, PAYMENTMETHOD, TOTALAMOUNT, BOOKING_ID, PAYMENTSTATUS) VALUES 
(PAYMENTCUSTOMER_SEQ.NEXTVAL, 908985679, 'upi', 500, 66, 'paid');
INSERT INTO PaymentCustomer (PAY_ID, ACCOUNTNUMBER, PAYMENTMETHOD, TOTALAMOUNT, BOOKING_ID, PAYMENTSTATUS) VALUES 
(PAYMENTCUSTOMER_SEQ.NEXTVAL, 234558789, 'upi', 500, 67, 'paid');
