CREATE TABLE  "ADMIN" 
   (    "ADMIN_ID" NUMBER, 
    "NAME" VARCHAR2(50), 
    "ADMIN_PASSWORD" VARCHAR2(50), 
    "EMAIL" VARCHAR2(50), 
     PRIMARY KEY ("ADMIN_ID") ENABLE
   ) ;
CREATE TABLE  "EMPLOYEE" 
   (    "EMP_ID" NUMBER, 
    "NAME" VARCHAR2(20) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(25), 
    "PASSWORD" VARCHAR2(15) NOT NULL ENABLE, 
    "GENDER" VARCHAR2(5) NOT NULL ENABLE, 
    "PHONE_NUMBER" VARCHAR2(10) NOT NULL ENABLE, 
    "ROLE" VARCHAR2(10) NOT NULL ENABLE, 
    "CITY" VARCHAR2(20) NOT NULL ENABLE, 
    "MAG_ID" NUMBER, 
    "HIREDATE" DATE, 
     PRIMARY KEY ("EMP_ID") ENABLE
   ) ;
CREATE TABLE  "PERSONAL_TASK" 
   (    "TASK_ID" NUMBER, 
    "TASK_NAME" VARCHAR2(20) NOT NULL ENABLE, 
    "TASK_DESP" VARCHAR2(100), 
    "START_DATE" DATE, 
    "END_DATE" DATE, 
    "TASK_PRIORITY" VARCHAR2(20), 
    "EMAIL" VARCHAR2(25), 
    "STATUS" VARCHAR2(15), 
     PRIMARY KEY ("TASK_ID") ENABLE
   ) ;
CREATE TABLE  "TASK" 
   (    "TASK_ID" NUMBER, 
    "TASK_NAME" VARCHAR2(20), 
    "TASK_DESP" VARCHAR2(100), 
    "START_DATE" DATE, 
    "END_DATE" DATE, 
    "TASK_PRIORTIY" VARCHAR2(20), 
     PRIMARY KEY ("TASK_ID") ENABLE
   ) ;
CREATE TABLE  "TASK_STATUS" 
   (    "ID" NUMBER, 
    "STATUS" VARCHAR2(20), 
     PRIMARY KEY ("ID") ENABLE
   ) ;
CREATE TABLE  "TRANSCATION" 
   (    "EMP_ID" NUMBER, 
    "TASK_ID" NUMBER, 
    "STATUS_ID" NUMBER, 
    "ASSIGNER_ID" NUMBER(38,0)
   ) ;
ALTER TABLE  "TRANSCATION" ADD CONSTRAINT "FK_EMP_ID" FOREIGN KEY ("EMP_ID")
      REFERENCES  "EMPLOYEE" ("EMP_ID") ENABLE;
ALTER TABLE  "TRANSCATION" ADD CONSTRAINT "FK_STATUS_ID" FOREIGN KEY ("STATUS_ID")
      REFERENCES  "TASK_STATUS" ("ID") ENABLE;
ALTER TABLE  "TRANSCATION" ADD CONSTRAINT "FK_TASK_ID" FOREIGN KEY ("TASK_ID")
      REFERENCES  "TASK" ("TASK_ID") ENABLE;
CREATE UNIQUE INDEX  "SYS_C007918" ON  "DEPT" ("DEPTNO") 
  ;
CREATE UNIQUE INDEX  "SYS_C007920" ON  "EMP" ("EMPNO") 
  ;
CREATE UNIQUE INDEX  "SYS_C008011" ON  "EMPLOYEE" ("EMP_ID") 
  ;
CREATE UNIQUE INDEX  "SYS_C008012" ON  "TASK" ("TASK_ID") 
  ;
CREATE UNIQUE INDEX  "SYS_C008013" ON  "TASK_STATUS" ("ID") 
  ;
CREATE UNIQUE INDEX  "SYS_C008014" ON  "ADMIN" ("ADMIN_ID") 
  ;
CREATE UNIQUE INDEX  "SYS_C008016" ON  "PERSONAL_TASK" ("TASK_ID") 
  ;
CREATE SEQUENCE   "TASKSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 90 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "PERSONALSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 50 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "EMPSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 65 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "ADSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 CACHE 20 NOORDER  NOCYCLE ;