CREATE TABLE  "DEPARTMENT" 
   (    "DEPTID" NUMBER, 
        "DEPTNAME" VARCHAR2(100) NOT NULL ENABLE, 
        "LOCATION" VARCHAR2(100), 
         PRIMARY KEY ("DEPTID") ENABLE
   ) ;


   CREATE TABLE  "EMPLOYEE" 
   (    "EMPID" NUMBER, 
        "FNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "LNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(50), 
    "DEPTID" NUMBER, 
    "USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(30) NOT NULL ENABLE, 
    "MANAGERID" NUMBER, 
    "JOINDATE" DATE, 
    "SALARY" NUMBER, 
    "EMPACCSTATUS" VARCHAR2(20), 
    "ROLE" VARCHAR2(15), 
     PRIMARY KEY ("EMPID") ENABLE, 
     UNIQUE ("EMAIL") ENABLE
   ) ; 
   CREATE TABLE  "LEAVE" 
   (    "LEAVEBALANCEID" NUMBER, 
    "EMPID" NUMBER NOT NULL ENABLE, 
    "LEAVEBALANCE" NUMBER NOT NULL ENABLE, 
    "LEAVETAKEN" NUMBER NOT NULL ENABLE, 
     CONSTRAINT "CHK_LEAVEBALANCE" CHECK (LEAVEBALANCE <= 120) ENABLE, 
     CONSTRAINT "CHK_LEAVETAKEN" CHECK (LEAVETAKEN <= LEAVEBALANCE) ENABLE, 
     PRIMARY KEY ("LEAVEBALANCEID") ENABLE
   ) ;
   
   CREATE TABLE  "LEAVEAPPLICATION" 
   (    "LEAVEID" NUMBER, 
    "EMPID" NUMBER NOT NULL ENABLE, 
    "LEAVETYPE" VARCHAR2(20) NOT NULL ENABLE, 
    "STARTDATE" DATE NOT NULL ENABLE, 
    "ENDDATE" DATE NOT NULL ENABLE, 
    "LEAVEREASON" VARCHAR2(100) NOT NULL ENABLE, 
    "SUBMITDATE" DATE NOT NULL ENABLE, 
    "STATUS" VARCHAR2(30) NOT NULL ENABLE, 
    "REJECTIONREASON" VARCHAR2(100), 
    "WORKASSIGNED" NUMBER, 
     PRIMARY KEY ("LEAVEID") ENABLE
   ) ;

ALTER TABLE  "EMPLOYEE" ADD CONSTRAINT "FK_DEPT" FOREIGN KEY ("DEPTID") REFERENCES  "DEPARTMENT" ("DEPTID") ENABLE;
ALTER TABLE  "LEAVEAPPLICATION" ADD CONSTRAINT "FK_EMP" FOREIGN KEY ("EMPID") REFERENCES  "EMPLOYEE" ("EMPID") ENABLE;
ALTER TABLE  "LEAVE" ADD CONSTRAINT "FK_EMP_LEAVE" FOREIGN KEY ("EMPID") REFERENCES  "EMPLOYEE" ("EMPID") ENABLE;
ALTER TABLE  "LEAVEAPPLICATION" ADD CONSTRAINT "FK_WORKASSIGNED" FOREIGN KEY ("WORKASSIGNED") REFERENCES  "EMPLOYEE" ("EMPID") ENABLE;
CREATE UNIQUE INDEX  "SYS_C007261" ON  "DEPT" ("DEPTNO");
CREATE UNIQUE INDEX  "SYS_C007263" ON  "EMP" ("EMPNO") ;
CREATE UNIQUE INDEX  "SYS_C007349" ON  "DEPARTMENT" ("DEPTID") ;
CREATE UNIQUE INDEX  "SYS_C007354" ON  "EMPLOYEE" ("EMPID") ;
CREATE UNIQUE INDEX  "SYS_C007355" ON  "EMPLOYEE" ("EMAIL") ;
CREATE UNIQUE INDEX  "SYS_C007366" ON  "LEAVEAPPLICATION" ("LEAVEID") ;
CREATE UNIQUE INDEX  "SYS_C007380" ON  "LEAVE" ("LEAVEBALANCEID") ; 
CREATE SEQUENCE   "LEAVESSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "LEAVESEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "EMPSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;