CREATE TABLE  "DEPARTMENT" 
   (    "DEPTID" NUMBER, 
        "DEPTNAME" VARCHAR2(100) NOT NULL ENABLE, 
        "LOCATION" VARCHAR2(100), 
         PRIMARY KEY ("DEPTID") ENABLE
   ) ;


   CREATE TABLE  "EMPLOYEE" 
   (    "EMPID" NUMBER, 
        "FNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "LNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(50), 
    "DEPTID" NUMBER, 
    "USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(30) NOT NULL ENABLE, 
    "MANAGERID" NUMBER, 
    "JOINDATE" DATE, 
    "SALARY" NUMBER, 
    "EMPACCSTATUS" VARCHAR2(20), 
    "ROLE" VARCHAR2(15), 
     PRIMARY KEY ("EMPID") ENABLE, 
     UNIQUE ("EMAIL") ENABLE
   ) ; 
   CREATE TABLE  "LEAVE" 
   (    "LEAVEBALANCEID" NUMBER, 
    "EMPID" NUMBER NOT NULL ENABLE, 
    "LEAVEBALANCE" NUMBER NOT NULL ENABLE, 
    "LEAVETAKEN" NUMBER NOT NULL ENABLE, 
     CONSTRAINT "CHK_LEAVEBALANCE" CHECK (LEAVEBALANCE <= 120) ENABLE, 
     CONSTRAINT "CHK_LEAVETAKEN" CHECK (LEAVETAKEN <= LEAVEBALANCE) ENABLE, 
     PRIMARY KEY ("LEAVEBALANCEID") ENABLE
   ) ;
   
   CREATE TABLE  "LEAVEAPPLICATION" 
   (    "LEAVEID" NUMBER, 
    "EMPID" NUMBER NOT NULL ENABLE, 
    "LEAVETYPE" VARCHAR2(20) NOT NULL ENABLE, 
    "STARTDATE" DATE NOT NULL ENABLE, 
    "ENDDATE" DATE NOT NULL ENABLE, 
    "LEAVEREASON" VARCHAR2(100) NOT NULL ENABLE, 
    "SUBMITDATE" DATE NOT NULL ENABLE, 
    "STATUS" VARCHAR2(30) NOT NULL ENABLE, 
    "REJECTIONREASON" VARCHAR2(100), 
    "WORKASSIGNED" NUMBER, 
     PRIMARY KEY ("LEAVEID") ENABLE
   ) ;

ALTER TABLE  "EMPLOYEE" ADD CONSTRAINT "FK_DEPT" FOREIGN KEY ("DEPTID") REFERENCES  "DEPARTMENT" ("DEPTID") ENABLE;
ALTER TABLE  "LEAVEAPPLICATION" ADD CONSTRAINT "FK_EMP" FOREIGN KEY ("EMPID") REFERENCES  "EMPLOYEE" ("EMPID") ENABLE;
ALTER TABLE  "LEAVE" ADD CONSTRAINT "FK_EMP_LEAVE" FOREIGN KEY ("EMPID") REFERENCES  "EMPLOYEE" ("EMPID") ENABLE;
ALTER TABLE  "LEAVEAPPLICATION" ADD CONSTRAINT "FK_WORKASSIGNED" FOREIGN KEY ("WORKASSIGNED") REFERENCES  "EMPLOYEE" ("EMPID") ENABLE;
CREATE UNIQUE INDEX  "SYS_C007261" ON  "DEPT" ("DEPTNO");
CREATE UNIQUE INDEX  "SYS_C007263" ON  "EMP" ("EMPNO") ;
CREATE UNIQUE INDEX  "SYS_C007349" ON  "DEPARTMENT" ("DEPTID") ;
CREATE UNIQUE INDEX  "SYS_C007354" ON  "EMPLOYEE" ("EMPID") ;
CREATE UNIQUE INDEX  "SYS_C007355" ON  "EMPLOYEE" ("EMAIL") ;
CREATE UNIQUE INDEX  "SYS_C007366" ON  "LEAVEAPPLICATION" ("LEAVEID") ;
CREATE UNIQUE INDEX  "SYS_C007380" ON  "LEAVE" ("LEAVEBALANCEID") ; 
CREATE SEQUENCE   "LEAVESSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "LEAVESEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "EMPSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;

INSERT INTO department VALUES(10, 'Technology Development', 'Bangalore');
INSERT INTO department VALUES(20, 'Quality Assurance', 'Chennai');
INSERT INTO employee VALUES( 103, 'Tharshine', 'RS', 'rstharshine@gmail.com', 10, 'tharshine_rs', 'Tharshu15%', NULL, TO_DATE('2003-05-15','YYYY-MM-DD') , 80000.00,'ACTIVE', 'MANAGER');
INSERT INTO employee VALUES( 104, 'Sam', 'MS', 'samsamrutha24@gmail.com', 10, 'sam_ms', 'Samrutha24%', '103', TO_DATE('2002-08-24','YYYY-MM-DD') , 40000.00, 'ACTIVE',  'EMPLOYEE' );
INSERT INTO employee VALUES( 105, 'Ram', 'S', 'ramakrishnan@gmail.com', 10, 'ram_s', 'Ram24%', '103', TO_DATE('2002-12-01','YYYY-MM-DD') , 40000.00, 'ACTIVE', 'EMPLOYEE');
INSERT INTO employee VALUES( 106, 'Praveen', 'KR', 'praveenkr@gmail.com', 10, 'praveen_kr', 'Praveen18%', '103', TO_DATE('2003-05-18','YYYY-MM-DD') , 40000.00,'ACTIVE','EMPLOYEE');
INSERT INTO employee VALUES( 107, 'Harsha', 'MK', 'harshamk@gmail.com', 20, 'harsha_mk', 'Harsha14%' , NULL, TO_DATE('2002-06-14','YYYY-MM-DD') , 80000.00, 'ACTIVE','MANAGER');
INSERT INTO employee VALUES( 108, 'Jeeva', 'S', 'jeevas@gmail.com', 20, 'jeeva_s', 'Jeeva04%', 107, TO_DATE('2003-01-04','YYYY-MM-DD') , 40000.00,'ACTIVE', 'EMPLOYEE');
INSERT INTO LEAVE values (1, 104, 43, 2);
INSERT INTO LEAVE values (2, 103, 45, 0);
INSERT INTO LEAVE values (3, 105, 45, 0);
INSERT INTO LEAVE values (4, 106, 45, 0);
INSERT INTO LEAVE values (5, 107, 45, 0);
INSERT INTO leaveapplication VALUES( 141, 104, 'SICKLEAVE', TO_DATE('2024-08-07','YYYY-MM-DD'), TO_DATE('2024-08-07','YYYY-MM-DD'), 'Stomach pain', SYSDATE,  'PENDING', NULL, 'tharshine_rs');
INSERT INTO leaveapplication VALUES( 142, 104, 'SICKLEAVE', TO_DATE('2024-07-07','YYYY-MM-DD'), TO_DATE('2024-07-07','YYYY-MM-DD'), 'Fever and cold', SYSDATE, 'APPROVED', NULL, 'ram_s');
INSERT INTO leaveapplication VALUES( 143, 104, 'CASUALLEAVE', TO_DATE('2024-08-24','YYYY-MM-DD'), TO_DATE('2024-08-24','YYYY-MM-DD'), 'Function', SYSDATE, 'APPROVED', NULL, 'ram_s');
INSERT INTO leaveapplication VALUES( 143, 104, 'SICKLEAVE', TO_DATE('2024-07-24','YYYY-MM-DD'), TO_DATE('2024-07-24','YYYY-MM-DD'), 'Headache', SYSDATE, 'REJECTED', NULL, 'ram_s');
