/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.18
 * Generated at: 2024-07-19 05:24:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class blogs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/CustomerHeaderFooter.css\"/>\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/LogoFavIcon.jpg\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/css/bootstrap-multiselect.css\"\r\n");
      out.write("      rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/CustomerHeaderFooter.css\"/>\r\n");
      out.write("    <title>Blogs - A1 Golden Plaza</title>\r\n");
      out.write("    <style>\r\n");
      out.write("    .outerCard {\r\n");
      out.write("     justify-content: center;\r\n");
      out.write("     align-items: center;\r\n");
      out.write("     display: flex; \r\n");
      out.write("     width: 350px; \r\n");
      out.write("     height: 500px; \r\n");
      out.write("     margin: 0 auto 20px auto;\r\n");
      out.write("     overflow: hidden;\r\n");
      out.write("     border: 1px solid #ddd; \r\n");
      out.write("     border-radius: 5px; \r\n");
      out.write("     box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); \r\n");
      out.write("     box-sizing: border-box;\r\n");
      out.write("     transition: transform 0.3s ease;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .inner-image img:hover {\r\n");
      out.write("     transform: scale(1.05);\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .innerCard {\r\n");
      out.write("     margin-top: 7%;\r\n");
      out.write("     margin-bottom: 2%;\r\n");
      out.write("     margin-left: 10%;\r\n");
      out.write("     margin-right: 10%;\r\n");
      out.write("     display: flex;\r\n");
      out.write("     flex-direction: column; \r\n");
      out.write("     justify-content: center;\r\n");
      out.write("     align-items: center;\r\n");
      out.write("     width: calc(100% - 20px);\r\n");
      out.write("     height: calc(100% - 20px);\r\n");
      out.write("     box-sizing: border-box; \r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .inner-image img {\r\n");
      out.write("     margin-top: 2%;\r\n");
      out.write("     width: 300px;\r\n");
      out.write("     height: 300px;\r\n");
      out.write("     transition: 0.2s ease-in-out;\r\n");
      out.write("     border-radius: 10px;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .blog-title {\r\n");
      out.write("     margin-top: 5px;\r\n");
      out.write("     font-size: 1rem;\r\n");
      out.write("     font-weight: bold;\r\n");
      out.write("     padding: 0 10px;\r\n");
      out.write("     overflow: hidden;\r\n");
      out.write("     text-overflow: ellipsis; \r\n");
      out.write("     display: -webkit-box; \r\n");
      out.write("     -webkit-line-clamp: 2;\r\n");
      out.write("     -webkit-box-orient: vertical;\r\n");
      out.write("     word-wrap: break-word;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .blog-date {\r\n");
      out.write("     font-size: 0.875rem;\r\n");
      out.write("     color: gray;\r\n");
      out.write("     padding: 0 5px;\r\n");
      out.write("     word-wrap: break-word;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .blog-content {\r\n");
      out.write("     padding: 0 5px; \r\n");
      out.write("     font-size: 0.9rem; \r\n");
      out.write("     color: #333; \r\n");
      out.write("     overflow: hidden; \r\n");
      out.write("     text-overflow: ellipsis; \r\n");
      out.write("     display: -webkit-box;\r\n");
      out.write("     -webkit-line-clamp: 3;\r\n");
      out.write("     -webkit-box-orient: vertical;\r\n");
      out.write("     word-wrap: break-word; \r\n");
      out.write("     height: 65px; \r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("     </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-light\" id=\"customNavbar\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assert/image/Logo.1.1.png\" id=\"company-logo\" alt=\"Company Logo\"></a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("              <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" style=\"margin-left:40% \">\r\n");
      out.write("              <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href= '");
      out.print( request.getContextPath() );
      out.write("/index.jsp'>Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/blogs'>Blogs</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                    Hall Events\r\n");
      out.write("                  </a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\" id=\"Events-DropDown\">\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Wedding</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Corporate Party</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Conference</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Concert</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Exhibition</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Product Launch</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Training Session</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/facilites'>Facilities</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/contact'>Contact</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if(session.getAttribute("customer")==null){
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\"  id=\"login\">Login</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
}
                else{ 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userMenu\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"40\" fill=\"currentColor\" class=\"bi bi-person\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path d=\"M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"userMenu\">\r\n");
      out.write("                            <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/viewBooking\" style =\"color: #4e4332 !important;\">My Bookings</a></li>\r\n");
      out.write("                             <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/RequestHall\" style =\"color: #4e4332 !important;\">Booking Request</a></li>\r\n");
      out.write("                               <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\" style =\"color: #4e4332 !important;\" id=\"logout\">Logout</a></li>\r\n");
      out.write("                      	</ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"container mt-4\" style=\"margin-top:100px !important;\">\r\n");
      out.write("     <nav aria-label=\"breadcrumb\" class=\"breadcrumbs large-font\">\r\n");
      out.write("			 <nav style=\"--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);\" aria-label=\"breadcrumb\">\r\n");
      out.write("				  <ol class=\"breadcrumb\">\r\n");
      out.write("				    <li class=\"breadcrumb-item\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" style=\"color:#6c757d\">Home</a></li>\r\n");
      out.write("				    <li class=\"breadcrumb-item active\" aria-current=\"page\" style=\"color:#ffc107\">Blogs</li>\r\n");
      out.write("				  </ol>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</nav>\r\n");
      out.write("    \r\n");
      out.write("        <h1 class=\"text-center mb-4\" >Our Latest Blogs</h1>\r\n");
      out.write("       \r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                    <div class=\"innerCard\">\r\n");
      out.write("                        <div class=\"inner-image\">\r\n");
      out.write("                            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/7-indian-destination-wedding-locations-under-25-lakhs-to-host-your-wedding-at.jpg\" alt=\"Wedding Locations\">\r\n");
      out.write("                            <h5 class=\"blog-title\">7 Indian Destination Wedding Locations costs Under 25 Lakhs to Host Your Wedding At!</h5>\r\n");
      out.write("                            <p class=\"blog-date\">April 25, 2024</p>\r\n");
      out.write("                            <p class=\"blog-content\">Jaibagh Palace, Kukas Jaipur Brimming with energy and exquisitely situated in an organic environment amidst the Aravalli hills, Jaibagh Palace, Kukas, Jaipur, is an exquisite destination wedding l...</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                    <div class=\"innerCard\">\r\n");
      out.write("                        <div class=\"inner-image\">\r\n");
      out.write("                            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/405701581_18397364416002324_5390610751807028513_n.jpg\" alt=\"Goa Decor Ideas\">\r\n");
      out.write("                            <h5 class=\"blog-title\">20 Quirky Decor Ideas to Make Your Goa Destination Wedding Pop!</h5>\r\n");
      out.write("                            <p class=\"blog-date\">Feb. 27, 2024</p>\r\n");
      out.write("                            <p class=\"blog-content\">Get set to sprinkle some Goan magic on your big day with our no-nonsense guide to Goa Wedding Decor Ideas. From beachy vibes to vintage glam, we've got the scoop on turning your 'I Do' into a visu...</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                    <div class=\"innerCard\">\r\n");
      out.write("                        <div class=\"inner-image\">\r\n");
      out.write("                            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Fortune-park-BBD.jpg\" alt=\"Banquet Halls in Lucknow\">\r\n");
      out.write("                            <h5 class=\"blog-title\">Top 5 AC Banquet Halls in Lucknow for Picture-Perfect Weddings</h5>\r\n");
      out.write("                            <p class=\"blog-date\">Feb. 22, 2024</p>\r\n");
      out.write("                            <p class=\"blog-content\"> Ready to turn your wedding into the coolest celebration in town? We've got your back as we dive into the world of AC Banquet Halls in Lucknow – because who needs wedding stress when you can have a...</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                    <div class=\"innerCard\">\r\n");
      out.write("                        <div class=\"inner-image\">\r\n");
      out.write("                            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/varmala-resort-and-banquet-jagatpura-jaipur.jpg\" alt=\"Banquet Halls in Jaipur\">\r\n");
      out.write("                            <h5 class=\"blog-title\">5 Popular AC Banquet Halls in Jaipur for A Stunning Summer Wedding 2024</h5>\r\n");
      out.write("                            <p class=\"blog-date\">Feb. 21, 2024</p>\r\n");
      out.write("                            <p class=\"blog-content\">Starting off the summer season with a bang – and what better way than planning the coolest summer wedding in Jaipur! We get it, the sun's shining, but your wedding doesn't have to turn into a melt...</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                    <div class=\"innerCard\">\r\n");
      out.write("                        <div class=\"inner-image\">\r\n");
      out.write("                            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Grand-Hyatt-Mumbai-P605-Grand-Ballroom-Social-Cluster-Wedding.16x9.jpg\" alt=\"Banquet Malad\">\r\n");
      out.write("                            <h5 class=\"blog-title\">Golden Leaf Banquet Malad - Your Dream Venue for a Memorable Mumbai Wedding</h5>\r\n");
      out.write("                            <p class=\"blog-date\">May 17, 2024</p>\r\n");
      out.write("                            <p class=\"blog-content\">Are you looking for a spectacular banquet hall in Mumbai that turns all your celebrations into a golden affair? You have stumbled upon the right one - Golden Leaf Banquet Malad West...</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                    <div class=\"innerCard\">\r\n");
      out.write("                        <div class=\"inner-image\">\r\n");
      out.write("                            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/top-large-capacity-wedding-venues-in-mumbai-for-your-big-fat-indian-wedding.jpg\" alt=\"Large Capacity Wedding Venues in Mumbai\">\r\n");
      out.write("                            <h5 class=\"blog-title\">Top Large Capacity Wedding Venues in Mumbai for Your Big Fat Indian Wedding</h5>\r\n");
      out.write("                            <p class=\"blog-date\">April 28, 2024</p>\r\n");
      out.write("                            <p class=\"blog-content\">Do you plan on inviting every person known to you on your big day? Are you, your spouse-to-be, or both, as a couple, super popular among your peers? Is your list of guests growing longer every day?...</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                    <div class=\"innerCard\">\r\n");
      out.write("                        <div class=\"inner-image\">\r\n");
      out.write("                            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Mice-Events-2-scaled.jpg\" alt=\"Office Team Building Activities\">\r\n");
      out.write("                            <h5 class=\"blog-title\">15+ Office Team Building Activities That Will Put You at #1 for Employee Engagement</h5>\r\n");
      out.write("                            <p class=\"blog-date\">April 11, 2024</p>\r\n");
      out.write("                            <p class=\"blog-content\">\"A dream you dream alone is only a dream. A dream you dream together is reality.” – John Lennon While as an organization we all are working together to turn that dream into reality, it's o...</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                    <div class=\"innerCard\">\r\n");
      out.write("                        <div class=\"inner-image\">\r\n");
      out.write("                            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Mice-Events-1-scaled.jpg\" alt=\"Corporate Event Planning Tips\">\r\n");
      out.write("                            <h5 class=\"blog-title\">15 Corporate Event Planning Tips to Turn Your Event from Snooze fest to WOW</h5>\r\n");
      out.write("                            <p class=\"blog-date\">Feb. 27, 2024</p>\r\n");
      out.write("                            <p class=\"blog-content\">Get set to sprinkle some Goan magic on your big day with our no-nonsense guide to Goa Wedding Decor Ideas. From beachy vibes to vintage glam, we've got the scoop on turning your 'I Do' into a visu...</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                    <div class=\"innerCard\">\r\n");
      out.write("                        <div class=\"inner-image\">\r\n");
      out.write("                            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/7-incredible-candle-decor-ideas-for-your-2018-wedding.jpg\" alt=\"Candle Decor Ideas\">\r\n");
      out.write("                            <h5 class=\"blog-title\">7 Incredible Candle Decor Ideas for Your 2024 Wedding!</h5>\r\n");
      out.write("                            <p class=\"blog-date\">Feb. 19, 2024</p>\r\n");
      out.write("                            <p class=\"blog-content\">While some people incorporate candle lighting for brightening the decor, I believe they can create a decor that would make your guests go gaga over it! Yes, these light bubbles don’t just add an e...</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("            <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                <div class=\"innerCard\">\r\n");
      out.write("                    <div class=\"inner-image\">\r\n");
      out.write("                        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/7-incredible-candle-decor-ideas-for-your-2018-wedding.jpg\" alt=\"Wedding Locations\">\r\n");
      out.write("                        <h5 class=\"blog-title\">7 Indian Destination Wedding Locations costs Under 25 Lakhs to Host Your Wedding At!</h5>\r\n");
      out.write("                        <p class=\"blog-date\">April 25, 2024</p>\r\n");
      out.write("                        <p class=\"blog-content\">Jaibagh Palace, Kukas Jaipur Brimming with energy and exquisitely situated in an organic environment amidst the Aravalli hills, Jaibagh Palace, Kukas, Jaipur, is an exquisite destination wedding l...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("            <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                <div class=\"innerCard\">\r\n");
      out.write("                    <div class=\"inner-image\">\r\n");
      out.write("                        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/cost-of-destination-wedding-packages-in-udaipur-between-20-30-lakhs-only-destinationweddingseries.jpg\" alt=\"Goa Decor Ideas\">\r\n");
      out.write("                        <h5 class=\"blog-title\">Cost of Destination Wedding Packages in Udaipur between 20-30 Lakhs Only! #DestinationWeddingSeries</h5>\r\n");
      out.write("                        <p class=\"blog-date\">Feb. 27, 2024</p>\r\n");
      out.write("                        <p class=\"blog-content\">Are you as shocked and amazed as we are, on finding out that the cost of destination wedding packages in Udaipur can be this low? No, we’re not pulling a late April Fool prank on you. We have proof...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("            <div class=\"outerCard animate__animated animate__fadeInUp\">\r\n");
      out.write("                <div class=\"innerCard\">\r\n");
      out.write("                    <div class=\"inner-image\">\r\n");
      out.write("                        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/cost-of-destination-2.jpg\" alt=\"Banquet Halls in Lucknow\">\r\n");
      out.write("                        <h5 class=\"blog-title\">Cost of Destination Wedding Packages in Jaipur and Pushkar in Less Than 30 Lakhs! #DestinationWeddingSeries</h5>\r\n");
      out.write("                        <p class=\"blog-date\">Feb. 22, 2024</p>\r\n");
      out.write("                        <p class=\"blog-content\">For those of us who still fantasize about “raja rani ki kahaniyan”, it goes without saying that many of us still have a special place in our hearts for royal Rajasthani destination weddings complet...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--Logout modal-->\r\n");
      out.write("<div class=\"modal\" id=\"logoutModal\" tabindex=\"-1\" aria-labelledby=\"logoutModalLabel\" aria-hidden=\"true\">\r\n");
      out.write(" <form action=\"logout\" method=\"get\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"logoutModalLabel\">Confirm Logout</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      	</div>\r\n");
      out.write("     	 <div class=\"modal-body\">\r\n");
      out.write("        	<p>Are you sure you want to logout?</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-outline-danger\" id=\"confirmLogoutButton\">Logout</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("  </form>\r\n");
      out.write("</div> \r\n");
      out.write("  <footer class=\"text-center text-lg-start bg-body-tertiary text-muted\">\r\n");
      out.write("\r\n");
      out.write("    <section class=\"d-flex justify-content-center justify-content-lg-between p-4 border-bottom\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"me-5 d-none d-lg-block\">\r\n");
      out.write("        <span>Get connected with us on social networks:</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/social_12942327.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/twitter-alt_12107622.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/instagram_2111463.png\" alt=\"\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/youtube_1384060.png\" alt=\"\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"\">\r\n");
      out.write("      <div class=\"container text-center text-md-start mt-5\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mt-3\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-3 col-lg-4 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("              <i class=\"fas fa-gem me-3\"></i>Royal Halls\r\n");
      out.write("            </h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              Manage all your event details,\r\n");
      out.write("              sales and billings and enhance the\r\n");
      out.write("              client experience with 20+ online\r\n");
      out.write("              booking, event planning.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">Search Planning</h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.html\" class=\"text-reset\">Search by Events</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.html\" class=\"text-reset\">Search by Seating Arrangements</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.html\" class=\"text-reset\">Search by Price</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.html\" class=\"text-reset\">Search by Hall</a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">Useful links :</h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Home1.0.html\" class=\"text-reset\">Home</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.html\" class=\"text-reset\">Venues</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"facilities.html\" class=\"text-reset\">Facilities</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"contact.html\" class=\"text-reset\">Contact</a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">Contact</h6>\r\n");
      out.write("            <p><i class=\"fas fa-home me-3\"></i> Singa, Coimbatore</p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <i class=\"fas fa-envelope me-3\"></i>\r\n");
      out.write("              info@example.com\r\n");
      out.write("            </p>\r\n");
      out.write("            <p><i class=\"fas fa-phone me-3\"></i> + 01 234 567 88</p>\r\n");
      out.write("            <p><i class=\"fas fa-print me-3\"></i> + 01 234 567 89</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write(" <div class=\"modal\" id=\"logoutModal\" tabindex=\"-1\" aria-labelledby=\"logoutModalLabel\" aria-hidden=\"true\">\r\n");
      out.write(" <form action=\"logout\" method=\"get\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"logoutModalLabel\">Confirm Logout</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      	</div>\r\n");
      out.write("     	 <div class=\"modal-body\">\r\n");
      out.write("        	<p>Are you sure you want to logout?</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-outline-danger\">Logout</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("  </form>\r\n");
      out.write("</div> \r\n");
      out.write("    \r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("document.getElementById('confirmLogoutButton').addEventListener('click', function() {\r\n");
      out.write("    // Add your logout logic here\r\n");
      out.write("    window.location.href = '");
      out.print( request.getContextPath() );
      out.write("/LogoutServlet'; // Replace 'logoutURL' with the actual URL to log out\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"login\").addEventListener(\"click\",function(){\r\n");
      out.write("	window.location.href = \"");
      out.print( request.getContextPath() );
      out.write("/viewLogin\"\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  // Show the modal when the logout dropdown item is clicked\r\n");
      out.write(" 	document.getElementById('logout').addEventListener('click', function(event) {\r\n");
      out.write("    event.preventDefault();\r\n");
      out.write("    var logoutModal = new bootstrap.Modal(document.getElementById('logoutModal'));\r\n");
      out.write("    logoutModal.show();\r\n");
      out.write("  });\r\n");
      out.write(" </script>   \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"text-center p-4 copyright\">\r\n");
      out.write("      © 2021 Copyright:\r\n");
      out.write("      <a class=\"text-reset fw-bold\" href=\"https://RoyalHalls.com/\">RoyalHalls.com</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("    integrity=\"sha384-KyZXEAg3QhqLMpG8r+Knujsl5+5hb7ie1LQQa9U52EXv7aQZL2RHB5SEc5HB5nh9\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+7HAuoD6z7VVvNK15MWEhPJwW/7mo\" crossorigin=\"anonymous\">\r\n");
      out.write("</script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
