/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.18
 * Generated at: 2024-07-18 07:03:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class facilities_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"image/LogoFavIcon.jpg\">\r\n");
      out.write("      <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/css/bootstrap-multiselect.css\"\r\n");
      out.write("    rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/CustomerHeaderFooter.css\"/>\r\n");
      out.write("    <title>Facilities</title>\r\n");
      out.write("    <style>\r\n");
      out.write("      .container{\r\n");
      out.write("        margin-top: 10% !important;\r\n");
      out.write("      }\r\n");
      out.write("      /* General checkbox styling */\r\n");
      out.write("      input[type=\"checkbox\"] {\r\n");
      out.write("          accent-color: black;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .form-check {\r\n");
      out.write("          margin-bottom: 10px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .form-check-input {\r\n");
      out.write("          margin-right: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      .card {\r\n");
      out.write("          border: none;\r\n");
      out.write("          border-radius: 5px;\r\n");
      out.write("          box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("          transition: transform 0.3s ease;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .card:hover {\r\n");
      out.write("          transform: translateY(-5px);\r\n");
      out.write("          box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .card-img-top {\r\n");
      out.write("          border-top-left-radius: 5px;\r\n");
      out.write("          border-top-right-radius: 5px;\r\n");
      out.write("          width:280px;\r\n");
      out.write("          height: 150px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .card-body {\r\n");
      out.write("          background-color: #f9f9f9;\r\n");
      out.write("          border-bottom-left-radius: 5px;\r\n");
      out.write("          border-bottom-right-radius: 5px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .card-text {\r\n");
      out.write("          color: #333;\r\n");
      out.write("          font-size: 18px;\r\n");
      out.write("          font-weight: bold;\r\n");
      out.write("          text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <header>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-light\" id=\"customNavbar\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assert/image/Logo.1.1.png\" id=\"company-logo\" alt=\"Company Logo\"></a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("              <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" style=\"margin-left:40% \">\r\n");
      out.write("              <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href= '");
      out.print( request.getContextPath() );
      out.write("/index.jsp'>Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/blogs'>Blogs</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                    Hall Events\r\n");
      out.write("                  </a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\" id=\"Events-DropDown\">\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Wedding</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Corporate Party</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Conference</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Concert</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Exhibition</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Product Launch</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Training Session</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/facilites'>Facilities</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/contact'>Contact</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if(session.getAttribute("customer")==null){
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\"  id=\"login\"   href=\"");
      out.print( request.getContextPath() );
      out.write("/viewLogin\" >Login</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
}
                else{ 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userMenu\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"40\" fill=\"currentColor\" class=\"bi bi-person\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path d=\"M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"userMenu\">\r\n");
      out.write("                            <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/viewBooking\" style =\"color: #4e4332 !important;\">My Bookings</a></li>\r\n");
      out.write("                             <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/RequestHall\" style =\"color: #4e4332 !important;\">Booking Request</a></li>\r\n");
      out.write("                               <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\" style =\"color: #4e4332 !important;\" id=\"logout\">Logout</a></li>\r\n");
      out.write("                      	</ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!--Logout modal-->\r\n");
      out.write(" <div class=\"modal\" id=\"logoutModal\" tabindex=\"-1\" aria-labelledby=\"logoutModalLabel\" aria-hidden=\"true\">\r\n");
      out.write(" <form action=\"logout\" method=\"get\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"logoutModalLabel\">Confirm Logout</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      	</div>\r\n");
      out.write("     	 <div class=\"modal-body\">\r\n");
      out.write("        	<p>Are you sure you want to logout?</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-outline-danger\">Logout</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("  </form>\r\n");
      out.write("</div> \r\n");
      out.write("		\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    <nav aria-label=\"breadcrumb\" class=\"breadcrumbs large-font\">\r\n");
      out.write("			 <nav style=\"--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);\" aria-label=\"breadcrumb\">\r\n");
      out.write("				  <ol class=\"breadcrumb\">\r\n");
      out.write("				    <li class=\"breadcrumb-item\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" style=\"color:#6c757d\">Home</a></li>\r\n");
      out.write("				    <li class=\"breadcrumb-item active\" aria-current=\"page\" style=\"color:#ffc107\">Blogs</li>\r\n");
      out.write("				  </ol>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</nav>\r\n");
      out.write("        <div class=\"row mb-5 \">\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Pohang-Apartment.jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Parking Facilities</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Premium Photo _ Air conditioner compressor installed outdoors.jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Ac Facilities</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/8539-dance-floor-white-frog-production-carpet-diem.jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Dance Floor</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/download (2).jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Dj System</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/5 Super Fun Playgrounds in Worthington.jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Parks</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/room.jpg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Room Facilities</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/download (3).jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Decoration</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/9 Tips for Choosing the Best Catering Staff.jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Catring</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Elegant, Minimalistic Architecture And Interior Design For The Function Hall Of Vedant Banquets _ AndSpaces - The Architects Diary.jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Handle huge polpulation</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Security Companies Calgary 2019.jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Security</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Free Photo _ Toilet seem from below.jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Clean Toilet</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/Free Photo _ Bartender making a delicious refreshing cocktail.jpeg\" alt=\"Card image cap\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p class=\"card-text\">Bar</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("  <footer class=\"text-center text-lg-start bg-body-tertiary text-muted\">\r\n");
      out.write("\r\n");
      out.write("    <section class=\"d-flex justify-content-center justify-content-lg-between p-4 border-bottom\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"me-5 d-none d-lg-block\">\r\n");
      out.write("        <span>Get connected with us on social networks:</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/social_12942327.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/twitter-alt_12107622.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/instagram_2111463.png\" alt=\"\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/youtube_1384060.png\" alt=\"\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"\">\r\n");
      out.write("      <div class=\"container text-center text-md-start mt-5\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mt-3\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-3 col-lg-4 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("              <i class=\"fas fa-gem me-3\"></i>Royal Halls\r\n");
      out.write("            </h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              Manage all your event details,\r\n");
      out.write("              sales and billings and enhance the\r\n");
      out.write("              client experience with 20+ online\r\n");
      out.write("              booking, event planning.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">Search Planning</h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.jsp\" class=\"text-reset\">Search by Events</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.jsp\" class=\"text-reset\">Search by Seating Arrangements</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.jsp\" class=\"text-reset\">Search by Price</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.jsp\" class=\"text-reset\">Search by Hall</a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">Useful links :</h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Home1.0.jsp\" class=\"text-reset\">Home</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.jsp\" class=\"text-reset\">Venues</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"facilities.html\" class=\"text-reset\">Facilities</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"contact.html\" class=\"text-reset\">Contact</a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">Contact</h6>\r\n");
      out.write("            <p><i class=\"fas fa-home me-3\"></i> Singa, Coimbatore</p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <i class=\"fas fa-envelope me-3\"></i>\r\n");
      out.write("              info@example.com\r\n");
      out.write("            </p>\r\n");
      out.write("            <p><i class=\"fas fa-phone me-3\"></i> + 01 234 567 88</p>\r\n");
      out.write("            <p><i class=\"fas fa-print me-3\"></i> + 01 234 567 89</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    document.getElementById('confirmLogoutButton').addEventListener('click', function() {\r\n");
      out.write("        // Add your logout logic here\r\n");
      out.write("        window.location.href = '");
      out.print( request.getContextPath() );
      out.write("/LogoutServlet'; // Replace 'logoutURL' with the actual URL to log out\r\n");
      out.write("      });\r\n");
      out.write("      // Show the modal when the logout dropdown item is clicked\r\n");
      out.write("     	document.getElementById('logout').addEventListener('click', function(event) {\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("        var logoutModal = new bootstrap.Modal(document.getElementById('logoutModal'));\r\n");
      out.write("        logoutModal.show();\r\n");
      out.write("      });\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("    <div class=\"text-center p-4 copyright\">\r\n");
      out.write("      © 2021 Copyright:\r\n");
      out.write("      <a class=\"text-reset fw-bold\" href=\"https://RoyalHalls.com/\">RoyalHalls.com</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("      <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("      integrity=\"sha384-KyZXEAg3QhqLMpG8r+Knujsl5+5hb7ie1LQQa9U52EXv7aQZL2RHB5SEc5HB5nh9\" crossorigin=\"anonymous\">\r\n");
      out.write("      </script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+7HAuoD6z7VVvNK15MWEhPJwW/7mo\" crossorigin=\"anonymous\">\r\n");
      out.write("      </script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <div class=\"text-center p-4 copyright\">\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
