/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.18
 * Generated at: 2024-07-18 06:08:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class hall1_0_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1720276535162L));
    _jspx_dependants.put("jar:file:/D:/HallBookingManagementSystem_JSP_project/HallBooking_SpringMVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hallbookingmanagement/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664433678000L));
    _jspx_dependants.put("jar:file:/D:/HallBookingManagementSystem_JSP_project/HallBooking_SpringMVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hallbookingmanagement/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Hall List</title>\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/LogoFavIcon.jpg\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/CustomerHeaderFooter.css\"/>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/css/bootstrap-multiselect.css\"\r\n");
      out.write("    rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .tooltip {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <style>\r\n");
      out.write("        .card-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card {\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-radius: 20px 20px 0 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-content {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .namestar {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .rating {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .rating img {\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            margin-right: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .location {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .location p{\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .location img {\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price, .capacity {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .amenties {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .amenties p {\r\n");
      out.write("            background-color: #f0f0f0;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("      .filter-bar {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("          margin-top: 20px;\r\n");
      out.write("          top: 56px;\r\n");
      out.write("          left: 0;\r\n");
      out.write("          width: 100%;\r\n");
      out.write("          height: 100%;\r\n");
      out.write("          max-width: 270px;\r\n");
      out.write("          height: calc(100vh - 100px);\r\n");
      out.write("          background-color: #ffeed3;\r\n");
      out.write("          padding: 15px;\r\n");
      out.write("          overflow-y: auto;\r\n");
      out.write("      }\r\n");
      out.write("      #customNavbar h3 {\r\n");
      out.write("          margin-left: 7px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .filter-by-events, .filter-by-amenities, .filter-by-events, .filter-by-location, .filter-by-Price {\r\n");
      out.write("          border: #2b15359a solid 1px;\r\n");
      out.write("          padding: 10px;\r\n");
      out.write("          margin-bottom: 15px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .clear-button {\r\n");
      out.write("          margin-top: 10px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      @media (max-width: 767px) {\r\n");
      out.write("          .filter-bar {\r\n");
      out.write("              position: relative;\r\n");
      out.write("              top: auto;\r\n");
      out.write("              width: 100%;\r\n");
      out.write("              height: auto;\r\n");
      out.write("              margin-bottom: 15px;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          #main-container {\r\n");
      out.write("              flex-direction: column;\r\n");
      out.write("              margin-left: 0;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          .dropdown {\r\n");
      out.write("              margin-top: 15px;\r\n");
      out.write("          }\r\n");
      out.write("      }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- --Logout modal--  -->\r\n");
      out.write("	<div class=\"modal\" id=\"logoutModal\" tabindex=\"-1\" aria-labelledby=\"logoutModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("	 <form action=\"logout\" method=\"get\">\r\n");
      out.write("	  <div class=\"modal-dialog\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	      <div class=\"modal-header\">\r\n");
      out.write("	        <h5 class=\"modal-title\" id=\"logoutModalLabel\">Confirm Logout</h5>\r\n");
      out.write("	        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("	      	</div>\r\n");
      out.write("	     	 <div class=\"modal-body\">\r\n");
      out.write("	        	<p>Are you sure you want to logout?</p>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div class=\"modal-footer\">\r\n");
      out.write("	        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("	        <button type=\"submit\" class=\"btn btn-outline-danger\">Logout</button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div> \r\n");
      out.write("	  </form>\r\n");
      out.write("	  </div>\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-light\" id=\"customNavbar\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assert/image/Logo.1.1.png\" id=\"company-logo\" alt=\"Company Logo\"></a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("              <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" style=\"margin-left:40% \">\r\n");
      out.write("              <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href= '");
      out.print( request.getContextPath() );
      out.write("/index.jsp'>Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/blogs'>Blogs</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                    Hall Events\r\n");
      out.write("                  </a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\" id=\"Events-DropDown\">\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Wedding</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Corporate Party</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Conference</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Concert</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Exhibition</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Product Launch</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Training Session</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/facilites'>Facilities</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/contact'>Contact</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if(session.getAttribute("customer")==null){
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\"  id=\"login\"    href=\"");
      out.print( request.getContextPath() );
      out.write("/viewLogin\" >Login</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
}
                else{ 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userMenu\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"40\" fill=\"currentColor\" class=\"bi bi-person\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path d=\"M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"userMenu\">\r\n");
      out.write("                            <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/viewBooking\" style =\"color: #4e4332 !important;\">My Bookings</a></li>\r\n");
      out.write("                             <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/RequestHall\" style =\"color: #4e4332 !important;\">Booking Request</a></li>\r\n");
      out.write("                               <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\" style =\"color: #4e4332 !important;\" id=\"logout\">Logout</a></li>\r\n");
      out.write("                      	</ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-3 col-sm-12 filter-bar\">\r\n");
      out.write("            <div class=\"filter-by\"><h3>Filter By</h3></div>\r\n");
      out.write("            <ul class=\"nav flex-column\">\r\n");
      out.write("                <li class=\"nav-item filter-by-events\">\r\n");
      out.write("                    <div class=\"filter-by\"><h4>Events</h4></div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"checkboxWedding\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"checkboxWedding\">Wedding</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"checkboxCorporateParty\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"checkboxCorporateParty\">Corporate Party</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"checkboxConference\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"checkboxConference\">Conference</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"checkboxConcert1\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"checkboxConcert1\">Concert</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"checkboxExhibition\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"checkboxExhibition\">Exhibition</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"checkboxProductLaunch\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"checkboxProductLaunch\">Product Launch</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"checkboxTrainingSession\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"checkboxTrainingSession\">Training Session</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"checkboxConcert2\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"checkboxConcert2\">Concert</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"btn btn-secondary btn-sm clear-button\" onclick=\"clearCheckboxesByEvents()\">Clear</button>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <script>\r\n");
      out.write("                    function clearCheckboxesByEvents() {\r\n");
      out.write("                        const checkboxes = document.querySelectorAll('.filter-by-events .form-check-input');\r\n");
      out.write("                        checkboxes.forEach(checkbox => {\r\n");
      out.write("                            checkbox.checked = false;\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item filter-by-amenities\">\r\n");
      out.write("                    <div class=\"filter-by\"><h4>Amenities</h4></div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"amenityParking\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"amenityParking\">Parking</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"amenityWifi\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"amenityWifi\">Wi-Fi</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"amenityCatering\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"amenityCatering\">Catering</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"amenityAudioVisual\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"amenityAudioVisual\">Audio Visual Equipment</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"amenityBar\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"amenityAudioVisual\">Bar</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"amenityIceScreamBar\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"amenityAudioVisual\">Ice Scream Bar</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"amenityAdditionalSecurity\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"amenityAudioVisual\">Additional Security</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"btn btn-secondary btn-sm clear-button\" onclick=\"clearCheckboxesByAmenities()\">Clear</button>\r\n");
      out.write("                </li>\r\n");
      out.write("                <script>\r\n");
      out.write("                    function clearCheckboxesByAmenities() {\r\n");
      out.write("                        const checkboxes = document.querySelectorAll('.filter-by-amenities .form-check-input');\r\n");
      out.write("                        checkboxes.forEach(checkbox => {\r\n");
      out.write("                            checkbox.checked = false;\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item filter-by-Price mb-6\">\r\n");
      out.write("                    <h4>Price</h4>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"minPrice\">Minimum Price:</label>\r\n");
      out.write("                        <input type=\"number\" class=\"form-control\" id=\"minPrice\" placeholder=\"Enter minimum price\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group pb-2\">\r\n");
      out.write("                        <label for=\"maxPrice\">Maximum Price:</label>\r\n");
      out.write("                        <input type=\"number\" class=\"form-control\" id=\"maxPrice\" placeholder=\"Enter maximum price\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li style=\"justify-content: center; align-items: center;\" ><button type=\"button\" class=\"btn btn-light\"> Apply </button></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-9 col-sm-12 \" id =\"main-container\" style=\"margin-left: 320px; margin-top: 7%; \" >\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-between align-items-center\">\r\n");
      out.write("                    <div class=\"halls-cards\">\r\n");
      out.write("                        <h4>Best Wedding Venues</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <button class=\"btn btn-secondary dropdown-toggle\" type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                        Sort by\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Popularity</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Price: Low to High</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Price: High to Low</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"margin-top:40px\"></div> \r\n");
      out.write("            ");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /WEB-INF/view/hall1.0.jsp(363,12) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/hall1.0.jsp(363,12) '${hallList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${hallList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /WEB-INF/view/hall1.0.jsp(363,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("hall");
        // /WEB-INF/view/hall1.0.jsp(363,12) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVarStatus("status");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write(" \r\n");
              out.write("		        ");
              //  c:if
              org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
              boolean _jspx_th_c_005fif_005f0_reused = false;
              try {
                _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
                _jspx_th_c_005fif_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
                // /WEB-INF/view/hall1.0.jsp(364,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hall.isAvail}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
                int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
                if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
                  do {
                    out.write("\r\n");
                    out.write("                <div class=\"col-sm\"> \r\n");
                    out.write("                    <div class=\"card-container\">\r\n");
                    out.write("                        <div class=\"card\">\r\n");
                    out.write("	                          <a class=\"hall_link\" data-hall-id=\"");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hall.hallId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("\" data-index=\"");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("\">\r\n");
                    out.write("                    					<img src=\"");
                    out.print( request.getContextPath() );
                    out.write("/assert/image/hallcard-5.jpg\" style=\"border-radius:20px;\">\r\n");
                    out.write("                				</a>\r\n");
                    out.write("	                            <div class=\"card-content\">\r\n");
                    out.write("	                                <div class=\"namestar d-flex mt-2\">\r\n");
                    out.write("	                                    <h4 style=\"text-decoration:none;\">");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hall.hallName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("</h4>\r\n");
                    out.write("	                                        <div class=\"rating d-inline\">\r\n");
                    out.write("	                                            <img src=\"");
                    out.print( request.getContextPath() );
                    out.write("/assert/image/star_148841.png\" style=\"width:20px;\">\r\n");
                    out.write("	                                            <p class=\"d-inline\" style=\"margin-right: 20px;\">4.5</p>\r\n");
                    out.write("	                                        </div>\r\n");
                    out.write("	                                </div>\r\n");
                    out.write("	                                <div class=\"location d-flex d-block\">\r\n");
                    out.write("	                                    <img src=\"");
                    out.print( request.getContextPath() );
                    out.write("/assert/image/placeholder_186250.png\">\r\n");
                    out.write("	                                    <p>");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hall.location}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("</p>\r\n");
                    out.write("	                                </div>\r\n");
                    out.write("	                                        <div class=\"price ms-2\">\r\n");
                    out.write("	                                            <p><strong>&#8377;");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hall.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("</strong>Per Day</p>\r\n");
                    out.write("	                                        </div>\r\n");
                    out.write("	                                        <div class=\"capacity ms-2\">\r\n");
                    out.write("	                                            <p><strong>");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hall.capacity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write(" </strong> Aprox</p>\r\n");
                    out.write("	                                        </div >\r\n");
                    out.write("	                                        <div class=\"amenties d-flex ms-2\">\r\n");
                    out.write("	                                            ");
                    if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                      return;
                    out.write("\r\n");
                    out.write("	                                    </div>\r\n");
                    out.write("	                            </div>\r\n");
                    out.write("	                        </div >\r\n");
                    out.write("                        	 <form id=\"form-");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("\" style=\"display:none\" class=\"submission\" action=\"showHallDetail\" method=\"post\">\r\n");
                    out.write("				                <input name=\"hallId\" id=\"hall-Id-");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("\" value=\"");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hall.hallId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("\">\r\n");
                    out.write("				                <button type=\"submit\" class=\"form-btn\"></button>\r\n");
                    out.write("				            </form>\r\n");
                    out.write("                    </div>\r\n");
                    out.write("                </div>\r\n");
                    out.write("                ");
                    int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
                    if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                      break;
                  } while (true);
                }
                if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  return;
                }
                _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
                _jspx_th_c_005fif_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
              }
              out.write("\r\n");
              out.write("                ");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row \">\r\n");
      out.write("              <div class=\"col mt-4 mb-4\">\r\n");
      out.write("                  <ul class=\"pagination\" style=\"justify-content: center;\">\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">Previous</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">Next</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col d-flex flex-column justify-content-center align-items-center\">\r\n");
      out.write("                    <h2 class=\"text-center mt-3\">Best Wedding Venues in Coimbatore</h2>\r\n");
      out.write("                    <p class=\"text-center mt-2\" style=\"line-height: 25px; letter-spacing: 2px;\">\r\n");
      out.write("                        Known for its beauty over the globe, offers a great variety of wedding venues.\r\n");
      out.write("                        The best wedding venues are mentioned below along with their pictures and reviews.\r\n");
      out.write("                        The available venues are of all types including banquet halls to farmhouses. Both pocket-friendly & \r\n");
      out.write("                        grand wedding venues are available for booking, contact your favourite wedding venue vendor or request a\r\n");
      out.write("                        call back from us. We will take care of the rest\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>  \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  \r\n");
      out.write("  <footer class=\"text-center text-lg-start bg-body-tertiary text-muted\">\r\n");
      out.write("\r\n");
      out.write("    <section class=\"d-flex justify-content-center justify-content-lg-between p-4 border-bottom\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"me-5 d-none d-lg-block\">\r\n");
      out.write("        <span>Get connected with us on social networks:</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"assert/image/social_12942327.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"assert/image/twitter-alt_12107622.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"assert/image/instagram_2111463.png\" alt=\"\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset social-media\">\r\n");
      out.write("          <img src=\"assert/image/youtube_1384060.png\" alt=\"\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"\">\r\n");
      out.write("      <div class=\"container text-center text-md-start mt-5\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mt-3\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-3 col-lg-4 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("              <i class=\"fas fa-gem me-3\"></i>Royal Halls\r\n");
      out.write("            </h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              Manage all your event details,\r\n");
      out.write("              sales and billings and enhance the\r\n");
      out.write("              client experience with 20+ online\r\n");
      out.write("              booking, event planning.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">Search Planning</h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.html\" class=\"text-reset\">Search by Events</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.html\" class=\"text-reset\">Search by Seating Arrangements</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.html\" class=\"text-reset\">Search by Price</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.html\" class=\"text-reset\">Search by Hall</a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">Useful links :</h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Home1.0.html\" class=\"text-reset\">Home</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"Hall.html\" class=\"text-reset\">Venues</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"facilities.html\" class=\"text-reset\">Facilities</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"contact.html\" class=\"text-reset\">Contact</a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4\">\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">Contact</h6>\r\n");
      out.write("            <p><i class=\"fas fa-home me-3\"></i> Singa, Coimbatore</p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <i class=\"fas fa-envelope me-3\"></i>\r\n");
      out.write("              info@example.com\r\n");
      out.write("            </p>\r\n");
      out.write("            <p><i class=\"fas fa-phone me-3\"></i> + 01 234 567 88</p>\r\n");
      out.write("            <p><i class=\"fas fa-print me-3\"></i> + 01 234 567 89</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("      integrity=\"sha384-KyZXEAg3QhqLMpG8r+Knujsl5+5hb7ie1LQQa9U52EXv7aQZL2RHB5SEc5HB5nh9\" crossorigin=\"anonymous\">\r\n");
      out.write("      </script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+7HAuoD6z7VVvNK15MWEhPJwW/7mo\" crossorigin=\"anonymous\">\r\n");
      out.write("      </script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <div class=\"text-center p-4 copyright\">\r\n");
      out.write("      © 2021 Copyright:\r\n");
      out.write("      <a class=\"text-reset fw-bold\" href=\"https://RoyalHalls.com/\">RoyalHalls.com</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <script>\r\n");
      out.write("  \r\n");
      out.write("  document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("      var links = document.querySelectorAll('.hall_link');\r\n");
      out.write("\r\n");
      out.write("      links.forEach(function(link) {\r\n");
      out.write("          link.addEventListener('click', function(event) {\r\n");
      out.write("              event.preventDefault();\r\n");
      out.write("              var index = link.getAttribute('data-index');\r\n");
      out.write("              var form = document.getElementById('form-' + index);\r\n");
      out.write("              form.submit();\r\n");
      out.write("          });\r\n");
      out.write("      });\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  document.getElementById('confirmLogoutButton').addEventListener('click', function() {\r\n");
      out.write("	    // Add your logout logic here\r\n");
      out.write("	    window.location.href = '");
      out.print( request.getContextPath() );
      out.write("/LogoutServlet'; // Replace 'logoutURL' with the actual URL to log out\r\n");
      out.write("	  });\r\n");
      out.write("\r\n");
      out.write("	  // Show the modal when the logout dropdown item is clicked\r\n");
      out.write("	  document.getElementById('logout').addEventListener('click', function(event) {\r\n");
      out.write("	    event.preventDefault();\r\n");
      out.write("	    var logoutModal = new bootstrap.Modal(document.getElementById('logoutModal'));\r\n");
      out.write("	    logoutModal.show();\r\n");
      out.write("	  });\r\n");
      out.write("	  \r\n");
      out.write("\r\n");
      out.write("	  \r\n");
      out.write("\r\n");
      out.write("    window.onscroll = function() {checkPosition()};\r\n");
      out.write("        function checkPosition() {\r\n");
      out.write("            var fixedDiv = document.getElementById(\"filter-bar\");\r\n");
      out.write("            var containerEnter = document.getElementById(\"foot\");\r\n");
      out.write("            var containerEnterRect = containerEnter.getBoundingClientRect();\r\n");
      out.write("            var fixedDivRect = fixedDiv.getBoundingClientRect();\r\n");
      out.write("\r\n");
      out.write("            if (containerEnterRect.top <= fixedDivRect.bottom) {\r\n");
      out.write("                fixedDiv.style.position = \"absolute\";\r\n");
      out.write("                fixedDiv.style.top = (window.pageYOffset + containerEnterRect.top - fixedDivRect.height) + \"px\";\r\n");
      out.write("            } else {\r\n");
      out.write("                fixedDiv.style.position = \"fixed\";\r\n");
      out.write("                fixedDiv.style.top = \"20px\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        document.querySelector('.dropdown-toggle').addEventListener('click', function() {\r\n");
      out.write("        document.querySelector('.dropdown-menu').classList.toggle('show');\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("    document.getElementById('logout').addEventListener('click', function(event) {\r\n");
      out.write("	      event.preventDefault();\r\n");
      out.write("	      var logoutModal = new bootstrap.Modal(document.getElementById('logoutModal'));\r\n");
      out.write("	      logoutModal.show();\r\n");
      out.write("	    });\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/view/hall1.0.jsp(390,45) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/hall1.0.jsp(390,45) '${hall.amenities}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${hall.amenities}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/view/hall1.0.jsp(390,45) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("amenity");
      // /WEB-INF/view/hall1.0.jsp(390,45) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("amenityStatus");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	                                    			");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("	                                			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/view/hall1.0.jsp(391,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amenityStatus.index < 3}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                                        			<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amenity.amenityType}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("	                                    			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
