/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.18
 * Generated at: 2024-07-18 05:44:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/customerLoginCss.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/CustomerHeaderFooter.css\"/>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/css/bootstrap-multiselect.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <title>Login</title>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("   body {\r\n");
      out.write("        	background-image: url(\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/loginbg.jpg\");\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("        }\r\n");
      out.write("    	.custom-header {\r\n");
      out.write("  				background-color: #ff9999;\r\n");
      out.write("		}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"modal fade\" id=\"successModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"successModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"successModalLabel\">Login Successful</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" style=\"background-color: #28a745;\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                    <p>You have logged in successfully.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-success\" id=\"goHomeBtn\">Go to Home</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("       <header>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-light\" id=\"customNavbar\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assert/image/Logo.1.1.png\" id=\"company-logo\" alt=\"Company Logo\"></a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("              <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" style=\"margin-left:20% !important\">\r\n");
      out.write("              <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href= '");
      out.print( request.getContextPath() );
      out.write("/index.jsp'>Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/blogs'>Blogs</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                    Hall Events\r\n");
      out.write("                  </a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\" id=\"Events-DropDown\">\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Wedding</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Corporate Party</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Conference</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Concert</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Exhibition</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Product Launch</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Training Session</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/facilites'>Facilities</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/contact'>Contact</a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\" id=\"loginContainer\" style=\"margin-top: 150px;\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-3 d-none d-md-block\"></div>\r\n");
      out.write("        <div class=\"col-md-5\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <h2 class=\"text-center\" style=\"color: #4e4332;\">Login</h2>\r\n");
      out.write("               <form id=\"loginForm\" action=\"login\" method=\"post\" class=\"needs-validation\" novalidate>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                    	<input type=\"hidden\" name=\"redirectAfterLogin\" value=\"");
      out.print( session.getAttribute("redirectAfterLogin") );
      out.write("\" />\r\n");
      out.write("                        <div class=\"col mb-3\">\r\n");
      out.write("                            <label for=\"name\" class=\"form-label\">User Name:<sup style=\"color:red\">*</sup></label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"name\" id=\"name\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col mb-3\">\r\n");
      out.write("                            <label for=\"password\" class=\"form-label\">Password:<sup  style=\"color:red\">*</sup></label>\r\n");
      out.write("                            <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("                            <div class=\"text-danger\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("                    ");
 } 
      out.write("        \r\n");
      out.write("                    <button type=\"button\" class=\"forget-password\" style=\"border:none; background: none; padding: 0;\">\r\n");
      out.write("                        <a href=\"javascript:void(0)\" class=\"link-primary\">Forget Password?</a>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"text-center mb-3\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\" id=\"loginBtn\" disabled>Login</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"new-account\">\r\n");
      out.write("                        <p>Don't have an account? <a id=\"createAccount\" class=\"link-primary\">Create a new account</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"hr-with-text\">\r\n");
      out.write("                        <span>Are you an Admin?</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                       <a style=\"text-decoration:none;\"><button class=\"btn btn-outline-dark d-flex align-items-center\" id=\"admin-login\">\r\n");
      out.write("                                Business Sign In\r\n");
      out.write("                       </button></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\" id=\"resetPasswordContainer\" style=\"margin-top: 150px; display:none;\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-3 d-none d-md-block\"></div>\r\n");
      out.write("        <div class=\"col-md-5\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <h2 class=\"\" style=\"color: #4e4332;\">Reset your password</h2>\r\n");
      out.write("                <form id=\"resetPasswordForm\" class=\"needs-validation\" action=\"forgetPassword\" method=\"get\" novalidate>\r\n");
      out.write("                    <p class=\"instruction mt-2\">If the account exists, we will email you instructions to reset the password.</p>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col mb-3\">\r\n");
      out.write("                            <label for=\"email\" class=\"form-label\">Email:<sup  style=\"color:red\">*</sup></label>\r\n");
      out.write("                            <input type=\"email\" name=\"email\" class=\"form-control\" id=\"email\" required>\r\n");
      out.write("                            <div class=\"invalid-feedback\">Please enter the email</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text-center mb-3\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-light\" id=\"backToLoginBtn\">Back to Login</button>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\" id=\"resetPasswordBtn\">Reset Password</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal\" id=\"invalidMail\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header custom-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Modal title</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body mt-2 mb-2\">\r\n");
      out.write("        <h4>Entered Email Id is not Existed</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <footer class=\"text-center pt-2\">\r\n");
      out.write("        © 2021 Copyright:\r\n");
      out.write("        <a class=\"text-reset fw-bold\" href=\"https://RoyalHalls.com/\">RoyalHalls.com</a>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        // Disable login button until both username and password fields are filled\r\n");
      out.write("        $('#name, #password').on('keyup', function() {\r\n");
      out.write("            if ($('#name').val().trim() !== '' && $('#password').val().trim() !== '') {\r\n");
      out.write("                $('#loginBtn').prop('disabled', false);\r\n");
      out.write("            } else {\r\n");
      out.write("                $('#loginBtn').prop('disabled', true);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Show modal on successful login\r\n");
      out.write("        ");
 if (request.getAttribute("loginSuccess") != null && (Boolean)request.getAttribute("loginSuccess")) { 
      out.write("\r\n");
      out.write("            $('#successModal').modal('show');\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        // Redirect to home page on clicking the \"Go to Home\" button\r\n");
      out.write("        $('#goHomeBtn').on('click', function() {\r\n");
      out.write("            window.location.href = '");
      out.print( request.getContextPath() );
      out.write("/index.jsp'; // Correctly redirect to DashBoardServlet\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Redirect to admin login page on admin login button click\r\n");
      out.write("        $('#admin-login').on('click', function(event) {\r\n");
      out.write("            event.preventDefault(); // Prevent form submission\r\n");
      out.write("            window.location.href = '");
      out.print( request.getContextPath() );
      out.write("/viewAdminLogin'; // Correctly redirect to admin login page\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.querySelector('.dropdown-toggle').addEventListener('click', function() {\r\n");
      out.write("            document.querySelector('.dropdown-menu').classList.toggle('show');\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    document.querySelector(\".forget-password\").addEventListener(\"click\", function(){\r\n");
      out.write("        document.getElementById(\"loginContainer\").style.display = \"none\";\r\n");
      out.write("        document.getElementById(\"resetPasswordContainer\").style.display = \"block\";\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"backToLoginBtn\").addEventListener(\"click\", function(){\r\n");
      out.write("        document.getElementById(\"resetPasswordContainer\").style.display = \"none\";\r\n");
      out.write("        document.getElementById(\"loginContainer\").style.display = \"block\";\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    (function () {\r\n");
      out.write("      'use strict'\r\n");
      out.write("\r\n");
      out.write("      // Fetch all the forms we want to apply custom Bootstrap validation styles to\r\n");
      out.write("      var forms = document.querySelectorAll('.needs-validation')\r\n");
      out.write("\r\n");
      out.write("      // Loop over them and prevent submission\r\n");
      out.write("      Array.prototype.slice.call(forms)\r\n");
      out.write("        .forEach(function (form) {\r\n");
      out.write("          form.addEventListener('submit', function (event) {\r\n");
      out.write("            if (!form.checkValidity()) {\r\n");
      out.write("              event.preventDefault()\r\n");
      out.write("              event.stopPropagation()\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            form.classList.add('was-validated')\r\n");
      out.write("          }, false)\r\n");
      out.write("        })\r\n");
      out.write("    })()\r\n");
      out.write("    \r\n");
      out.write("  ");
 if(request.getAttribute("emailNotExisted") != null) { 
      out.write("\r\n");
      out.write("        $('#invalidMail').modal('show');\r\n");
      out.write(" ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"createAccount\").addEventListener(\"click\", function(){\r\n");
      out.write("    	event.preventDefault(); \r\n");
      out.write("    	window.location.href = \"");
      out.print( request.getContextPath() );
      out.write("/viewRegister\";\r\n");
      out.write("    })\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
