/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.18
 * Generated at: 2024-07-19 07:00:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class PaymentPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1720276535162L));
    _jspx_dependants.put("jar:file:/D:/HallBookingManagementSystem_JSP_project/HallBooking_SpringMVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hallbookingmanagement/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664433678000L));
    _jspx_dependants.put("jar:file:/D:/HallBookingManagementSystem_JSP_project/HallBooking_SpringMVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hallbookingmanagement/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>My Booking</title>\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/image/LogoFavIcon.jpg\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/css/bootstrap-multiselect.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">   \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assert/css/CustomerHeaderFooter.css\"/>\r\n");
      out.write("    <style>\r\n");
      out.write("        footer {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 2.5rem;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    	 ");
 
    if (request.getSession().getAttribute("customer") == null) {
        response.sendRedirect("viewLogin");
    }
	
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-light\" id=\"customNavbar\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assert/image/Logo.1.1.png\" id=\"company-logo\" alt=\"Company Logo\"></a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("              <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" style=\"margin-left:40% \">\r\n");
      out.write("              <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href= '");
      out.print( request.getContextPath() );
      out.write("/index.jsp'>Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/blogs'>Blogs</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                    Hall Events\r\n");
      out.write("                  </a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\" id=\"Events-DropDown\">\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Wedding</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Corporate Party</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Conference</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Concert</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Exhibition</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Product Launch</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href='");
      out.print( request.getContextPath() );
      out.write("/viewHalls'>Training Session</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("               <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/facilites'>Facilities</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href='");
      out.print( request.getContextPath() );
      out.write("/contact'>Contact</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if(session.getAttribute("customer")==null){
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\"  id=\"login\">Login</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
}
                else{ 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userMenu\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"40\" fill=\"currentColor\" class=\"bi bi-person\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path d=\"M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"userMenu\">\r\n");
      out.write("                            <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/viewBooking\" style =\"color: #4e4332 !important;\">My Bookings</a></li>\r\n");
      out.write("                             <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/RequestHall\" style =\"color: #4e4332 !important;\">Booking Request</a></li>\r\n");
      out.write("                               <li><a class=\"dropdown-item ms-0\" href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\" style =\"color: #4e4332 !important;\" id=\"logout\">Logout</a></li>\r\n");
      out.write("                      	</ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("<!--Logout modal-->\r\n");
      out.write("	 <div class=\"modal\" id=\"logoutModal\" tabindex=\"-1\" aria-labelledby=\"logoutModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("	 <form action=\"logout\" method=\"get\">\r\n");
      out.write("	  <div class=\"modal-dialog\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	      <div class=\"modal-header\">\r\n");
      out.write("	        <h5 class=\"modal-title\" id=\"logoutModalLabel\">Confirm Logout</h5>\r\n");
      out.write("	        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("	      	</div>\r\n");
      out.write("	     	 <div class=\"modal-body\">\r\n");
      out.write("	        	<p>Are you sure you want to logout?</p>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div class=\"modal-footer\">\r\n");
      out.write("	        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("	        <button type=\"submit\" class=\"btn btn-outline-danger\">Logout</button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div> \r\n");
      out.write("	  </form>\r\n");
      out.write("	</div> \r\n");
      out.write("    <div class=\"container mt-5 mb-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6 d-flex flex-column align-items-center\">\r\n");
      out.write("                <span class=\"mb-3\">Payment Method</span>\r\n");
      out.write("                <div class=\"card w-100\">\r\n");
      out.write("                    <div class=\"accordion\" id=\"accordionExample\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-header p-0\" id=\"headingPaypal\">\r\n");
      out.write("                                <h2 class=\"mb-0\">\r\n");
      out.write("                                    <button class=\"btn btn-light btn-block text-left collapsed p-3 rounded-0 border-bottom-custom d-flex\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsePaypal\" aria-expanded=\"false\" aria-controls=\"collapsePaypal\" style=\"width:100%\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center justify-content-center\">Paypal <img class=\"ms-3\" src=\"https://i.imgur.com/7kQEsHU.png\" width=\"30\"></div>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"collapsePaypal\" class=\"collapse\" aria-labelledby=\"headingPaypal\" data-parent=\"#accordionExample\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <input type=\"text\" id =\"paypal-mail\" name=\"paypalMail\" class=\"form-control\" placeholder=\"Paypal email\">\r\n");
      out.write("                                    <div class=\"invalid-class\" id=\"errorupiIdpaypal\" style=\"display:none;color:red\">Invalid Account number</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-header p-0\" id=\"headingGPay\">\r\n");
      out.write("                                <h2 class=\"mb-0\">\r\n");
      out.write("                                    <button class=\"btn btn-light btn-block text-left collapsed p-3 rounded-0 border-bottom-custom d-flex\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseGPay\" aria-expanded=\"false\" aria-controls=\"collapseGPay\" style=\"width:100%\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center justify-content-center\">GPay <img class=\"ms-3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assert/image/google-pay-icon.png\" width=\"30\"></div>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"collapseGPay\" class=\"collapse\" aria-labelledby=\"headingGPay\" data-parent=\"#accordionExample\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <input type=\"text\" id=\"upiIdG\" name=\"upiIdG\" class=\"form-control\" placeholder=\"number\">\r\n");
      out.write("                                    <div class=\"invalid-class\" id=\"errorupiIdG\" style=\"display:none;color:red\">Invalid Account number</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-header p-0\" id=\"headingPhonepe\">\r\n");
      out.write("                                <h2 class=\"mb-0\">\r\n");
      out.write("                                    <button class=\"btn btn-light btn-block text-left collapsed p-3 rounded-0 border-bottom-custom d-flex\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsePhonepe\" aria-expanded=\"false\" aria-controls=\"collapsePhonepe\" style=\"width:100%\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center justify-content-center\">Phonepe <img class=\"ms-3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assert/image/phonepe-icon.png\" width=\"30\"></div>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"collapsePhonepe\" class=\"collapse\" aria-labelledby=\"headingPhonepe\" data-parent=\"#accordionExample\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <input type=\"text\" id=\"upiIdP\" name=\"upiIdP\" class=\"form-control\" placeholder=\"number\">\r\n");
      out.write("                                    <div class=\"invalid-class\" id=\"errorupiIdP\" style=\"display:none;color:red\">Invalid Upi Id</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-header p-0\" id=\"headingCreditCard\">\r\n");
      out.write("                                <h2 class=\"mb-0\">\r\n");
      out.write("                                    <button class=\"btn btn-light btn-block text-left p-3 rounded-0\" data-toggle=\"collapse\" data-target=\"#collapseCreditCard\" aria-expanded=\"true\" aria-controls=\"collapseCreditCard\" style=\"width:100%\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("                                            <span>Credit card</span>\r\n");
      out.write("                                            <div class=\"icons\">\r\n");
      out.write("                                                <img src=\"https://i.imgur.com/2ISgYja.png\" width=\"30\">\r\n");
      out.write("                                                <img src=\"https://i.imgur.com/W1vtnOV.png\" width=\"30\">\r\n");
      out.write("                                                <img src=\"https://i.imgur.com/35tC99g.png\" width=\"30\">\r\n");
      out.write("                                                <img src=\"https://i.imgur.com/2ISgYja.png\" width=\"30\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"collapseCreditCard\" class=\"collapse show\" aria-labelledby=\"headingCreditCard\" data-parent=\"#accordionExample\">\r\n");
      out.write("                                <div class=\"card-body payment-card-body\">\r\n");
      out.write("                                    <span class=\"font-weight-normal card-text\">Card Number</span>\r\n");
      out.write("                                    <div class=\"input\">\r\n");
      out.write("                                        <i class=\"fa fa-credit-card\"></i>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"accountnumber\" name=\"accountnumber\" placeholder=\"0000 0000 0000 0000\">\r\n");
      out.write("                                        <div class=\"invalid-class\" id=\"errorAccountNumber\" style=\"display:none;color:red\">Invalid Account number</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row mt-3 mb-3\">\r\n");
      out.write("                                        <div class=\"col-6\">\r\n");
      out.write("                                            <span class=\"font-weight-normal card-text\">Expiry Date</span>\r\n");
      out.write("                                            <div class=\"input\">\r\n");
      out.write("                                                <i class=\"fa fa-calendar\"></i>\r\n");
      out.write("                                                <input type=\"text\" id=\"expdate\" name=\"expdate\" class=\"form-control\" placeholder=\"MM/YY\">\r\n");
      out.write("                                                <div class=\"invalid-class\" id=\"errorExpDate\" style=\"display:none;color:red\">Enter the valid Exp-date and year should be year</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                       <div class=\"col-6\">\r\n");
      out.write("										    <span class=\"font-weight-normal card-text\">CVC/CVV</span>\r\n");
      out.write("										    <div class=\"input\">\r\n");
      out.write("										        <i class=\"fa fa-lock\"></i>\r\n");
      out.write("										        <input type=\"text\" id=\"cvc\" name=\"cvc\" class=\"form-control\" placeholder=\"000\">\r\n");
      out.write("										        <div class=\"invalid-class\" id=\"errorCvc\" style=\"display:none;color:red\">\r\n");
      out.write("										            Please enter a valid 3-digit CVC/CVV number.\r\n");
      out.write("										        </div>\r\n");
      out.write("										    </div>\r\n");
      out.write("										</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <span class=\"text-muted certificate-text\"><i class=\"fa fa-lock\"></i> Your transaction is secured with SSL certificate</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     <div class=\"p-3\">\r\n");
      out.write("            <button class=\"btn btn-success btn-block free-button ps-5 pe-5\" data-toggle=\"modal\" data-target=\"#enterPinModal\" id=\"pay-btn\" disabled><strong>Pay</strong></button>\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("            \r\n");
      out.write("<p style=\"display:none\" id=\"bookingId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.bookingId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("	<div class=\"col-md-6 d-flex flex-column align-items-center\">\r\n");
      out.write("    <span class=\"mb-3\">Summary</span>\r\n");
      out.write("    <div class=\"card w-100\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between p-3\">\r\n");
      out.write("            <div class=\"d-flex flex-column\">\r\n");
      out.write("                <span>HallName</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mt-1\">\r\n");
      out.write("                <span class=\"price\">&#8377;<strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.hall.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></span>\r\n");
      out.write("                <span class=\"month\">/Day</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"mt-0 line\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("            <span class=\"ms-3\">Payment Method</span>\r\n");
      out.write("            <span>\r\n");
      out.write("                <select class=\"form-select\" id=\"paymentMethod\" name=\"paymentMethod\" aria-label=\"Default select example\">\r\n");
      out.write("                    <option value=\"2\">Full</option>\r\n");
      out.write("                    <option value=\"1\">Advanced</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"p-3\">\r\n");
      out.write("            <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                <span>Start Date</span>\r\n");
      out.write("                <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.startDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                <span>End Date<i class=\"fa fa-clock-o\"></i></span>\r\n");
      out.write("                <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.endDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                <span>No of Days<i class=\"fa fa-clock-o\"></i></span>\r\n");
      out.write("                <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberOfDays}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"mt-0 line\">\r\n");
      out.write("        <div class=\"p-3 d-flex justify-content-between\">\r\n");
      out.write("            <div class=\"d-flex flex-column\">\r\n");
      out.write("                <span>Total Payment</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span id=\"totalPayment\" data-original-total=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPayment}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">&#8377;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPayment}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Enter PIN Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"enterPinModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"enterPinModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <form action=\"payBooking\" method=\"get\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"enterPinModalLabel\">Enter Your PIN</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Hidden inputs for passing data -->\r\n");
      out.write("                <input name=\"paytype\" id=\"paytype\" type=\"hidden\">\r\n");
      out.write("                <input type=\"hidden\" name=\"paybookId\" id=\"paybookId\" autocomplete=\"off\">\r\n");
      out.write("                <input type=\"hidden\" name=\"totpay\" id=\"totpay\" autocomplete=\"off\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <input type=\"password\" id=\"userPin\" name=\"userPin\" class=\"form-control\" placeholder=\"0000\" autocomplete=\"off\">\r\n");
      out.write("                     <div class=\"invalid-class\" id=\"errorPin\" style=\"display:none;color:red\">Enter the valid Pin</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" disabled id=\"pin-sub\" onclick=\"submitPin()\">Submit</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"text-center pt-4 pb-4\">\r\n");
      out.write("    © 2021 Copyright:\r\n");
      out.write("    <a class=\"text-reset fw-bold\" href=\"https://RoyalHalls.com/\">RoyalHalls.com</a>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('paymentMethod').addEventListener('change', function() {\r\n");
      out.write("        let paymentMethod = this.value;\r\n");
      out.write("        let totalPaymentElement = document.getElementById('totalPayment');\r\n");
      out.write("        let originalTotal = parseFloat(totalPaymentElement.getAttribute('data-original-total'));\r\n");
      out.write("\r\n");
      out.write("        if (paymentMethod === '1') { // Advanced payment\r\n");
      out.write("            totalPaymentElement.textContent = '₹' + (originalTotal / 2).toFixed(2);\r\n");
      out.write("        } else { // Full payment\r\n");
      out.write("            totalPaymentElement.textContent = '₹' + originalTotal.toFixed(2);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function submitPin() {\r\n");
      out.write("        var pin = document.getElementById(\"userPin\").value;\r\n");
      out.write("        if (pin) {\r\n");
      out.write("            var totalPaymentElement = document.querySelector(\"#totalPayment\");\r\n");
      out.write("            var total = totalPaymentElement.textContent.trim().replace('₹', ''); // Extracting the total payment amount\r\n");
      out.write("            var paymentMethod = document.querySelector(\"#paymentMethod\").value; // Corrected to get value\r\n");
      out.write("            var bookingId = document.querySelector(\"#bookingId\").textContent.trim(); // Extracting the booking ID\r\n");
      out.write("\r\n");
      out.write("            // Setting values to hidden inputs in the modal form\r\n");
      out.write("            document.getElementById(\"paytype\").value = paymentMethod;\r\n");
      out.write("            document.getElementById(\"paybookId\").value = bookingId;\r\n");
      out.write("            document.getElementById(\"totpay\").value = total;\r\n");
      out.write("\r\n");
      out.write("            $('#enterPinModal').modal('hide'); // Hiding the PIN modal\r\n");
      out.write("            $('#paymentModal').modal('show'); // Showing the payment confirmation modal (if exists)\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(\"Please enter your PIN.\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    var creaditCardBoolean = false;\r\n");
      out.write("    \r\n");
      out.write("    var isaccountEntered = false;\r\n");
      out.write("    var isDateEntered = false;\r\n");
      out.write("    var isCvcEntered = false;\r\n");
      out.write("    var isGpayUpi = false;\r\n");
      out.write("    var isPhonepeeUpi = false;\r\n");
      out.write("    var isPaypal =false;\r\n");
      out.write("    \r\n");
      out.write("    var isAccountEntered = false;\r\n");
      out.write("    var isDateEntered = false;\r\n");
      out.write("    var isCvcEntered = false;\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"accountnumber\").addEventListener(\"input\", function() {\r\n");
      out.write("        var cardNumber = document.getElementById(\"accountnumber\").value;\r\n");
      out.write("        var regexPattern = /^[0-9]{4}\\s[0-9]{4}\\s[0-9]{4}\\s[0-9]{4}$/;\r\n");
      out.write("\r\n");
      out.write("        if (!regexPattern.test(cardNumber)) {\r\n");
      out.write("            document.getElementById(\"errorAccountNumber\").style.display = \"block\";\r\n");
      out.write("            isAccountEntered = false;\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"errorAccountNumber\").style.display = \"none\";\r\n");
      out.write("            isAccountEntered = true;\r\n");
      out.write("            console.log(\"errorAccountNumber\");\r\n");
      out.write("        }\r\n");
      out.write("        checkFormValidity();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('expdate').addEventListener('input', function() {\r\n");
      out.write("        const input = this.value;\r\n");
      out.write("        const regex = /^(0[1-9]|1[0-2])\\/\\d{2}$/;\r\n");
      out.write("        const errorDiv = document.getElementById('errorExpDate');\r\n");
      out.write("\r\n");
      out.write("        if (regex.test(input)) {\r\n");
      out.write("            const [month, year] = input.split('/').map(Number);\r\n");
      out.write("            const currentYear = new Date().getFullYear() % 100; // Get last two digits of current year\r\n");
      out.write("\r\n");
      out.write("            if (year >= currentYear) {\r\n");
      out.write("                errorDiv.style.display = 'none';\r\n");
      out.write("                isDateEntered = true;\r\n");
      out.write("                console.log(\"errorExpDate\");\r\n");
      out.write("            } else {\r\n");
      out.write("                errorDiv.style.display = 'block';\r\n");
      out.write("                isDateEntered = false;\r\n");
      out.write("            }\r\n");
      out.write("        } else {\r\n");
      out.write("            errorDiv.style.display = 'block';\r\n");
      out.write("            isDateEntered = false;\r\n");
      out.write("        }\r\n");
      out.write("        checkFormValidity();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"cvc\").addEventListener(\"input\", function() {\r\n");
      out.write("        var cardNumber = document.getElementById(\"cvc\").value;\r\n");
      out.write("        var regexPattern = /^[0-9]{3}$/;\r\n");
      out.write("\r\n");
      out.write("        if (!regexPattern.test(cardNumber)) {\r\n");
      out.write("            document.getElementById(\"errorCvc\").style.display = \"block\";\r\n");
      out.write("            isCvcEntered = false;\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"errorCvc\").style.display = \"none\";\r\n");
      out.write("            isCvcEntered = true;\r\n");
      out.write("            console.log(\"errorCvc\");\r\n");
      out.write("        }\r\n");
      out.write("        checkFormValidity();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function checkFormValidity() {\r\n");
      out.write("        if (isAccountEntered && isDateEntered && isCvcEntered) {\r\n");
      out.write("            console.log(\"All fields are valid\");\r\n");
      out.write("            document.getElementById(\"pay-btn\").disabled = false;\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"pay-btn\").disabled = true;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    document.getElementById(\"upiIdP\").addEventListener(\"input\", function() {\r\n");
      out.write("        var cardNumber = document.getElementById(\"upiIdP\").value;\r\n");
      out.write("        var regexPattern = /^[6789]{1}[0-9]{9}$/;\r\n");
      out.write("\r\n");
      out.write("        if (!regexPattern.test(cardNumber)) {\r\n");
      out.write("            document.getElementById(\"errorupiIdP\").style.display = \"block\";\r\n");
      out.write("			var isPhonepeeUpi = false;\r\n");
      out.write("			document.getElementById(\"pay-btn\").disabled = true;\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"errorupiIdP\").style.display = \"none\";\r\n");
      out.write("            var isPhonepeeUpi = true;\r\n");
      out.write("            document.getElementById(\"pay-btn\").disabled = false;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    document.getElementById(\"upiIdG\").addEventListener(\"input\", function() {\r\n");
      out.write("        var cardNumber = document.getElementById(\"upiIdG\").value;\r\n");
      out.write("        var regexPattern = /^[6789]{1}[0-9]{9}$/;\r\n");
      out.write("\r\n");
      out.write("        if (!regexPattern.test(cardNumber)) {\r\n");
      out.write("            document.getElementById(\"errorupiIdG\").style.display = \"block\";\r\n");
      out.write("            var isGpayUpi = false;\r\n");
      out.write("            document.getElementById(\"pay-btn\").disabled = true;\r\n");
      out.write("\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"errorupiIdG\").style.display = \"none\";\r\n");
      out.write("            var isGpayUpi = true;\r\n");
      out.write("            document.getElementById(\"pay-btn\").disabled = false;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    document.getElementById(\"paypal-mail\").addEventListener(\"input\", function() {\r\n");
      out.write("        var cardNumber = document.getElementById(\"paypal-mail\").value;\r\n");
      out.write("        var regexPattern = /^[a-zA-Z0-9]+@[a-zA-Z0-9]+\\.[a-zA-Z]{2,3}$/;\r\n");
      out.write("\r\n");
      out.write("        if (!regexPattern.test(cardNumber)) {\r\n");
      out.write("            document.getElementById(\"errorupiIdpaypal\").style.display = \"block\";\r\n");
      out.write("            var isPaypal =false;\r\n");
      out.write("            document.getElementById(\"pay-btn\").disabled = true;\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"errorupiIdpaypal\").style.display = \"none\";\r\n");
      out.write("            var isPaypal =true;\r\n");
      out.write("            document.getElementById(\"pay-btn\").disabled = false;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("	document.getElementById(\"userPin\").addEventListener(\"input\",function(){\r\n");
      out.write("		var pinNumber = document.getElementById(\"userPin\").value;\r\n");
      out.write("		var regexPattern = /^[0-9]{4}$/\r\n");
      out.write("		if(!regexPattern.test(pinNumber)){\r\n");
      out.write("			document.getElementById(\"errorPin\").style.display = \"block\";\r\n");
      out.write("			document.getElementById(\"pin-sub\").disabled  = true;\r\n");
      out.write("		}\r\n");
      out.write("		else{\r\n");
      out.write("			document.getElementById(\"pin-sub\").disabled = false;\r\n");
      out.write("			document.getElementById(\"errorPin\").style.display = \"none\";\r\n");
      out.write("		}\r\n");
      out.write("	} );\r\n");
      out.write("	document.getElementById('confirmLogoutButton').addEventListener('click', function() {\r\n");
      out.write("        // Add your logout logic here\r\n");
      out.write("        window.location.href = '");
      out.print( request.getContextPath() );
      out.write("/LogoutServlet'; // Replace 'logoutURL' with the actual URL to log out\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // Show the modal when the logout dropdown item is clicked\r\n");
      out.write("      document.getElementById('logout').addEventListener('click', function(event) {\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("        var logoutModal = new bootstrap.Modal(document.getElementById('logoutModal'));\r\n");
      out.write("        logoutModal.show();\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
