CREATE TABLE  "DEPARTMENT" 
   (    "DEPTID" NUMBER, 
    "DEPTNAME" VARCHAR2(100) NOT NULL ENABLE, 
    "LOCATION" VARCHAR2(50), 
     PRIMARY KEY ("DEPTID") ENABLE
   ) ;
CREATE TABLE  "EMPLOYEE" 
   (    "EMPID" NUMBER, 
    "FIRSTNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "LASTNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
    "DEPTID" NUMBER, 
    "MANAGERID" NUMBER, 
    "JOINDATE" DATE NOT NULL ENABLE, 
    "SALARY" NUMBER(10,2), 
    "GENDER" VARCHAR2(10) NOT NULL ENABLE, 
    "ROLE" VARCHAR2(50) NOT NULL ENABLE, 
    "STATUS" VARCHAR2(10) NOT NULL ENABLE, 
    "USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(30) NOT NULL ENABLE, 
     CHECK (GENDER IN ('MALE', 'FEMALE')) ENABLE, 
     CHECK (ROLE IN ('EMPLOYEE', 'MANAGER', 'ADMIN', 'HR')) ENABLE, 
     CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE, 
     PRIMARY KEY ("EMPID") ENABLE, 
     UNIQUE ("EMAIL") ENABLE, 
     CONSTRAINT "EMPLOYEE_USERNAME_UNIQUE" UNIQUE ("USERNAME") ENABLE
   ) ;
CREATE TABLE  "LEAVEBALANCE" 
   (    "LEAVETYPEID" NUMBER, 
    "EMPID" NUMBER, 
    "SICKLEAVE" NUMBER, 
    "VACATIONLEAVE" NUMBER, 
    "CASUALLEAVE" NUMBER, 
    "BALANCELEAVE" NUMBER, 
    "TOTALLEAVE" NUMBER, 
     PRIMARY KEY ("LEAVETYPEID") ENABLE, 
     CONSTRAINT "UQ_EMPID_LEAVETYPEID" UNIQUE ("EMPID", "LEAVETYPEID") ENABLE
   ) ;
CREATE TABLE  "LEAVES" 
   (    "LEAVEID" NUMBER, 
    "EMPID" NUMBER NOT NULL ENABLE, 
    "LEAVETYPE" VARCHAR2(20) NOT NULL ENABLE, 
    "STARTDATE" DATE NOT NULL ENABLE, 
    "ENDDATE" DATE NOT NULL ENABLE, 
    "REASON" VARCHAR2(255), 
    "ASSIGNWORK" VARCHAR2(30), 
    "STATUS" VARCHAR2(20) NOT NULL ENABLE, 
    "REJECTIONREASON" VARCHAR2(50), 
     CONSTRAINT "LEAVE_TYPE_CHECK" CHECK ("LEAVETYPE" IN ('CASUALLEAVE', 'SICKLEAVE', 'VACATIONLEAVE')) ENABLE, 
     CONSTRAINT "STATUS_CHECK" CHECK ("STATUS" IN ('APPROVED', 'CANCELLED', 'PENDING', 'REJECTED')) ENABLE, 
     PRIMARY KEY ("LEAVEID") ENABLE
   ) ;
ALTER TABLE  "LEAVEBALANCE" ADD CONSTRAINT "FK_EMPID" FOREIGN KEY ("EMPID")
      REFERENCES  "EMPLOYEE" ("EMPID") ENABLE;
ALTER TABLE  "LEAVES" ADD CONSTRAINT "FK_LEAVES_ASSIGNWORK" FOREIGN KEY ("ASSIGNWORK")
      REFERENCES  "EMPLOYEE" ("USERNAME") ENABLE;
ALTER TABLE  "LEAVES" ADD CONSTRAINT "FK_LEAVES_EMP" FOREIGN KEY ("EMPID")
      REFERENCES  "EMPLOYEE" ("EMPID") ENABLE;
ALTER TABLE  "EMPLOYEE" ADD FOREIGN KEY ("DEPTID")
      REFERENCES  "DEPARTMENT" ("DEPTID") ENABLE;
ALTER TABLE  "EMPLOYEE" ADD FOREIGN KEY ("MANAGERID")
      REFERENCES  "EMPLOYEE" ("EMPID") ENABLE;
CREATE UNIQUE INDEX  "EMPLOYEE_USERNAME_UNIQUE" ON  "EMPLOYEE" ("USERNAME") 
  ;
CREATE UNIQUE INDEX  "SYS_C006997" ON  "DEPT" ("DEPTNO") 
  ;
CREATE UNIQUE INDEX  "SYS_C006999" ON  "EMP" ("EMPNO") 
  ;
CREATE UNIQUE INDEX  "SYS_C007085" ON  "DEPARTMENT" ("DEPTID") 
  ;
CREATE UNIQUE INDEX  "SYS_C007098" ON  "EMPLOYEE" ("EMPID") 
  ;
CREATE UNIQUE INDEX  "SYS_C007099" ON  "EMPLOYEE" ("EMAIL") 
  ;
CREATE UNIQUE INDEX  "SYS_C007103" ON  "LEAVEBALANCE" ("LEAVETYPEID") 
  ;
CREATE UNIQUE INDEX  "SYS_C007113" ON  "LEAVES" ("LEAVEID") 
  ;
CREATE UNIQUE INDEX  "UQ_EMPID_LEAVETYPEID" ON  "LEAVEBALANCE" ("EMPID", "LEAVETYPEID") 
  ; 
CREATE SEQUENCE   "LEAVESEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "LBALANCESEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "EMPSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 130 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "DEPTSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;