CREATE TABLE  "ADMIN" 
   (    "ADMIN_ID" NUMBER, 
    "PASSWORD" VARCHAR2(20) NOT NULL ENABLE, 
    "USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
     PRIMARY KEY ("ADMIN_ID") ENABLE
   ) ;CREATE TABLE  "CUSTOMER" 
   (    "C_ID" NUMBER, 
    "USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(30) NOT NULL ENABLE, 
    "FIRST_NAME" VARCHAR2(20) NOT NULL ENABLE, 
    "LAST_NAME" VARCHAR2(20) NOT NULL ENABLE, 
    "ADDRESS" VARCHAR2(200) NOT NULL ENABLE, 
    "GENDER" VARCHAR2(20) NOT NULL ENABLE, 
    "MOBILE_NO" NUMBER(10,0) NOT NULL ENABLE, 
    "EMAIL_ID" VARCHAR2(50) NOT NULL ENABLE, 
    "ACCOUNT_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
    "ACCOUNT_STATUS" VARCHAR2(30) NOT NULL ENABLE, 
     PRIMARY KEY ("C_ID") ENABLE, 
     UNIQUE ("USERNAME") ENABLE, 
     UNIQUE ("MOBILE_NO") ENABLE, 
     UNIQUE ("EMAIL_ID") ENABLE
   ) ;CREATE TABLE  "CART" 
   (    "CART_ID" NUMBER, 
    "C_ID" NUMBER, 
     PRIMARY KEY ("CART_ID") ENABLE
   ) ;CREATE TABLE  "SUBCATEGORY" 
   (    "SUBCATEGORY_ID" NUMBER, 
    "CATEGORY_ID" NUMBER NOT NULL ENABLE, 
    "SUBCATEGORY_NAME" VARCHAR2(40) NOT NULL ENABLE, 
    "SUB_V_STATUS" VARCHAR2(20) NOT NULL ENABLE, 
     PRIMARY KEY ("SUBCATEGORY_ID") ENABLE
   ) ;CREATE TABLE  "VENDOR" 
   (    "V_ID" NUMBER, 
    "USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
    "REG_NO" VARCHAR2(20) NOT NULL ENABLE, 
    "ADDRESS" VARCHAR2(200) NOT NULL ENABLE, 
    "MOBILE_NO" NUMBER NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(20) NOT NULL ENABLE, 
    "AADHAR_NO" NUMBER NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
    "ACCOUNT_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
    "ACCOUNT_STATUS" VARCHAR2(30) NOT NULL ENABLE, 
     PRIMARY KEY ("V_ID") ENABLE, 
     CONSTRAINT "UNIQUEMOBILE_NO" UNIQUE ("MOBILE_NO") ENABLE, 
     CONSTRAINT "UNIQUEEMAIL_ID" UNIQUE ("EMAIL") ENABLE, 
     CONSTRAINT "UNIQUEAADHAR" UNIQUE ("AADHAR_NO") ENABLE
   ) ;CREATE TABLE  "PRODUCT" 
   (    "P_ID" NUMBER, 
    "P_NAME" VARCHAR2(30), 
    "P_BRAND" VARCHAR2(40), 
    "P_QUANTITY" NUMBER, 
    "P_SUBTITLE" VARCHAR2(80), 
    "P_DESCRIPTION" VARCHAR2(250), 
    "WARRANTY" VARCHAR2(40), 
    "SUBCATEGORY_ID" NUMBER, 
    "CATEGORY_ID" NUMBER, 
    "PRODUCT_STATUS" VARCHAR2(30), 
    "V_ID" NUMBER, 
    "P_PRICE" NUMBER(10,2), 
    "VERIFIED_STATUS" VARCHAR2(40), 
     PRIMARY KEY ("P_ID") ENABLE
   ) ;CREATE TABLE  "CART_DETAIL" 
   (    "CART_ID" NUMBER, 
    "P_ID" NUMBER, 
    "QUANTITY" NUMBER, 
     CONSTRAINT "PK" PRIMARY KEY ("CART_ID", "P_ID") ENABLE
   ) ;CREATE TABLE  "CATEGORY" 
   (    "CATEGORY_ID" NUMBER, 
    "CATEGORY_NAME" VARCHAR2(40) NOT NULL ENABLE, 
    "CAT_V_STATUS" VARCHAR2(20) NOT NULL ENABLE, 
     PRIMARY KEY ("CATEGORY_ID") ENABLE
   ) ;CREATE TABLE  "ORDERS" 
   (    "ORDER_ID" NUMBER, 
    "C_ID" NUMBER, 
    "ORDER_DATE" DATE, 
    "ADDRESS" VARCHAR2(100), 
    "ORDER_STATUS" VARCHAR2(25), 
    "REASON" VARCHAR2(250), 
     PRIMARY KEY ("ORDER_ID") ENABLE
   ) ;CREATE TABLE  "ORDER_PRODUCT" 
   (    "ORDER_ID" NUMBER, 
    "P_ID" NUMBER, 
    "QUANTITY" NUMBER, 
     PRIMARY KEY ("ORDER_ID", "P_ID") ENABLE
   ) ;CREATE TABLE  "PAYMENT" 
   (    "PAYMENT_ID" NUMBER, 
    "ORDER_ID" NUMBER, 
    "PAYMENT_DATE" DATE, 
    "PAYMENT_TYPE" VARCHAR2(50), 
    "PAYMENT_STATUS" VARCHAR2(50), 
    "AMOUNT" NUMBER(20,2), 
    "CARD_NUMBER" VARCHAR2(16), 
     PRIMARY KEY ("PAYMENT_ID") ENABLE
   ) ;ALTER TABLE  "PRODUCT" ADD CONSTRAINT "FK_ID" FOREIGN KEY ("V_ID")
      REFERENCES  "VENDOR" ("V_ID") ENABLE;ALTER TABLE  "SUBCATEGORY" ADD FOREIGN KEY ("CATEGORY_ID")
      REFERENCES  "CATEGORY" ("CATEGORY_ID") ENABLE;ALTER TABLE  "PRODUCT" ADD FOREIGN KEY ("SUBCATEGORY_ID")
      REFERENCES  "SUBCATEGORY" ("SUBCATEGORY_ID") ENABLE;ALTER TABLE  "PRODUCT" ADD FOREIGN KEY ("CATEGORY_ID")
      REFERENCES  "CATEGORY" ("CATEGORY_ID") ENABLE;ALTER TABLE  "ORDERS" ADD FOREIGN KEY ("C_ID")
      REFERENCES  "CUSTOMER" ("C_ID") ENABLE;ALTER TABLE  "ORDER_PRODUCT" ADD FOREIGN KEY ("ORDER_ID")
      REFERENCES  "ORDERS" ("ORDER_ID") ENABLE;ALTER TABLE  "ORDER_PRODUCT" ADD FOREIGN KEY ("P_ID")
      REFERENCES  "PRODUCT" ("P_ID") ENABLE;ALTER TABLE  "CART" ADD FOREIGN KEY ("C_ID")
      REFERENCES  "CUSTOMER" ("C_ID") ENABLE;ALTER TABLE  "CART_DETAIL" ADD FOREIGN KEY ("CART_ID")
      REFERENCES  "CART" ("CART_ID") ENABLE;ALTER TABLE  "CART_DETAIL" ADD FOREIGN KEY ("P_ID")
      REFERENCES  "PRODUCT" ("P_ID") ENABLE;ALTER TABLE  "PAYMENT" ADD FOREIGN KEY ("ORDER_ID")
      REFERENCES  "ORDERS" ("ORDER_ID") ENABLE;CREATE UNIQUE INDEX  "SYS_C007268" ON  "CUSTOMER" ("C_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007269" ON  "CUSTOMER" ("USERNAME") 
  ;CREATE UNIQUE INDEX  "SYS_C007270" ON  "CUSTOMER" ("MOBILE_NO") 
  ;CREATE UNIQUE INDEX  "SYS_C007271" ON  "CUSTOMER" ("EMAIL_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007272" ON  "ADMIN" ("ADMIN_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007273" ON  "VENDOR" ("V_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007274" ON  "CATEGORY" ("CATEGORY_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007275" ON  "SUBCATEGORY" ("SUBCATEGORY_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007277" ON  "PRODUCT" ("P_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007280" ON  "ORDERS" ("ORDER_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007282" ON  "ORDER_PRODUCT" ("ORDER_ID", "P_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007285" ON  "CART" ("CART_ID") 
  ;CREATE UNIQUE INDEX  "SYS_C007293" ON  "PAYMENT" ("PAYMENT_ID") 
  ;CREATE UNIQUE INDEX  "UNIQUEAADHAR" ON  "VENDOR" ("AADHAR_NO") 
  ;CREATE UNIQUE INDEX  "UNIQUEEMAIL_ID" ON  "VENDOR" ("EMAIL") 
  ;CREATE UNIQUE INDEX  "UNIQUEMOBILE_NO" ON  "VENDOR" ("MOBILE_NO") 
  ; CREATE SEQUENCE   "WISHLIST_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
    CREATE SEQUENCE   "VENDOR_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "SUBCATEGORY_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "PRODUCT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "PAYMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 461 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "ORDER_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 741 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "CUSTOMER_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 321 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "CATEGORY_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "CART_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE ; 
CREATE SEQUENCE   "ADMIN_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;